### ISSUE TITLE
Shiny interaction: visUnselectAll() does not actually internally unselect the nodes

### ISSUE THREAD

**Issue by jockbanan** [datastorm-open/visNetwork#101]
Hi! I have an issue concerning Shiny, which is a little harder to explain, so let me show it on an example: 

ui.R: 
```
ui <- fluidPage(
    visNetworkOutput("network")
)
```

server.R

```
require(shiny)
require(visNetwork)

server <- function(input, output) {
    output$network <- renderVisNetwork({
        nodes <- data.frame(id = 1:3, shape = c("circle", "square", "circle"))
        edges <- data.frame(from = c(1,2), to = c(1,3))
        
        visNetwork(nodes, edges) %>%
            visOptions(nodesIdSelection = TRUE)
    })
    
    observeEvent(input$network_selected, {
        print(paste("clicked on node:", input$network_selected))
        if (input$network_selected == "2"){
            print("unselecting node")
            visNetworkProxy("network") %>%
                visUnselectAll()
            print(paste("after unselect:", input$network_selected))
        }
    })
} 
```

Here, clicking on the square node writes a message and instantly unselects it. The problem is that even after visUnselectAll() is called, input$network_selected is still 2. So when I click on the square node again, input$network_selected does not change, so the observeEvent is not fired and the node stays selected. I have to actually unselect the node by clicking away (or on another node) to change the value of input$network_selected and be able to fire my observeEvent again.

Thank you!
Adam

**Comment by FrissAnalytics** [comment]
perhaps this helps: many events are passed in JavaScript to R via [Shiny.onInputChange](https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/), however, this function only listens for *changes* in the value of a message. 

Hence, if you call it twice with the same arguments, the second time a corresponding observeEvent block will not trigger as the object you send is unchanged. 

This can be overcome by adding a random value to your object, which makes the object as a whole appear changed to shiny. In R, you simply ignore that part of the object. 

Such a value is sometimes known as a *nonce*, see [here](https://github.com/rstudio/leaflet/search?utf8=%E2%9C%93&q=nonce). 

In visNetwork you can define your own click handler logic, implementing this strategy. You do have to know a little bit of JavaScript to do this though. 

Not sure if this makes sense to you...

**Comment by bthieurmel** [comment]
Hi, 

Normally fix now on latest dev version.

Thanks.
