### ISSUE TITLE
Strange behaviors when defining variable node colours

### ISSUE THREAD

**Issue by lordbitin** [datastorm-open/visNetwork#104]
Hi!

I am struggling to get coherent behavior when setting variable colors to the nodes of a graph.
I am setting a variable vector of colors to my graph, like this:

```{r}
nodes$color = sample(colours(),nrow(nodes))
```

When zooming out, i see this:

![image](https://cloud.githubusercontent.com/assets/7083752/19359991/d8863b06-917c-11e6-9e97-81826c077f02.png)

As you can see, there are some nodes with no color background, only some of them have been painted.
Furthermore, if I zoom in a little bit in the previous graph (the bottom of the graph), i see something like this:

![image](https://cloud.githubusercontent.com/assets/7083752/19360067/3ab78e06-917d-11e6-8aa3-2abd9eaf5ab3.png)

The nodes that were painted have not changed, but the empty nodes now are painted as "black"

If I set a fixed color (nodes$color <- "red") everything works fine...

Does anybody know how to successfully apply variable node colors?

Thanks in advance!
Víctor

**Comment by bthieurmel** [comment]
You just have to pass "valid" colors for javascript, can be like this '#2B7CE9' or 'rgba(120,32,14,20)' or 'red' but not some R complex color like ``antiquewhite1``.

**Comment by lordbitin** [comment]
Thanks! I did not know that I could use 'rgba(..)' as input.

Using this now I am able to create a heat color mapping for the nodes of my graph:

```{r}
appHelper.rgba_heat_color_mapping <- function (x, n = 100, alpha = T) {
    rgba_heat_colors <- heat.colors(n = n,alpha = alpha) %>% 
        map(~ paste0("rgba(",paste(col2rgb(.,alpha = alpha),collapse = ","),")"))
    
    rgba_heat_colors[cut(x,n)]
}

```

![image](https://cloud.githubusercontent.com/assets/7083752/19383338/1a3bf400-9204-11e6-9e0e-20134db8de31.png)


Works like a charm!!!! Thanks a lot! This package is awesome!
Víctor
