### ISSUE TITLE
visExport(), cropped image on save

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#105]
When I use the visExport(), the image I get is cropped in the bottom and I dont know how to fix it, any ideas? 
![export-network](https://cloud.githubusercontent.com/assets/9630888/19475448/ee9e2818-953c-11e6-847f-3fda14c281f0.jpeg)

**Comment by bthieurmel** [comment]
Do you use the latest CRAN version ``1.0.2`` ?

**Comment by kagestrife** [comment]
i am using the visNetwork 1.0.1. Is this a problem fixed with the update?

**Comment by bthieurmel** [comment]
Yes, perhaps. I've made some modification with ``visExport``., so can you try ?

**Comment by kagestrife** [comment]
I will try it next week, maybe Wednesday, so don't close the issue yet

Thanks

**Comment by kagestrife** [comment]
@bthieurmel yes, this was fixed in the new version. Is there a way to get the png image automatically saved, not by pressing the button? like visSave does.

**Comment by bthieurmel** [comment]
Yes, we can think about add a method, but we can use that only with ``visNetworkProxy``

**Comment by kagestrife** [comment]
yeah, this would be great.
