### ISSUE TITLE
visSave(), missing examples

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#106]
I want to add the option of visSave() for my graph, by adding the user click a button and download the graph, while still seeing it in his/her browser, same as visExport(). Is something like that doable? There are no examples on the manual.

**Comment by bthieurmel** [comment]
Hi,
``visSave`` is use to save a network into a .html file. You can use it in shiny if you want like saving data in .csv or grah in .png, ... with ``downloadLink`` or ``downloadButton`` and ``downloadHandler``. This is a simple example : 

````
require(shiny)
require(visNetwork)

ui <- fluidPage(
  visNetworkOutput("network"), 
  downloadLink('downloadNetwork', 'Download network as .html')
)

server <- function(input, output) {
  mynetwork <- reactive({
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    visNetwork(nodes, edges)
  })
  output$network <- renderVisNetwork({
    mynetwork()
  })
  
  output$downloadNetwork <- downloadHandler(
    filename = function() {
      paste('network-', Sys.Date(), '.html', sep='')
    },
    content = function(con) {
      mynetwork() %>% visSave(con)
    }
  )
} 

shiny::shinyApp(ui, server)
````
