### ISSUE TITLE
VisLegend customization options

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#109]
Hello, could we have more customization options for the legend? One thing missing in particular is the option to have the name of the element (node or edge), outside of the element itself.

**Comment by kagestrife** [comment]
Update. I added the edges from the visnetwork to the legend, they are all "dot" shaped, but when I go to see the output, I get this. Everything on top of each other. Any ways to change the size of the elements inside the legend?
![edges](https://cloud.githubusercontent.com/assets/9630888/19648854/3ba2d45a-9a0c-11e6-8a01-4455f9a6ba7f.png)

**Comment by bthieurmel** [comment]
Hi,

Are you using Rstudio or looking your network within shiny ? If looking in Rstudio, do you observe the same problem opening the network in a browser ? I saw some strange legend position in Rstudio viewer.

**Comment by lordbitin** [comment]
+1

This is also happening to me!

**Comment by kagestrife** [comment]
Same as @lordbitin , I have tried the RStudio viewer and an external viewer (this is part of an rmd, so I viewed it inside my browsers)

**Comment by lordbitin** [comment]
I have fixed it by defining the legend in a custom data.frame, using the attribute `addNodes` from the function `visLegend`

**Comment by kagestrife** [comment]
@lordbitin what do you mean? redifining the nodes data.frame in a new data.frame? or something different? Can you give me a code example?

**Comment by lordbitin** [comment]
@kagestrife exactly that, suppose your nodes are divided into two groups "A" and "B", then you define, for example:

```{r}
lengendNodes <- data.frame(
    label = c("A","B"),
    color.background = c("red","blue"),
    color.border = c("black", "white")
)

graph <- graph %>% visLegend(
    useGroups = FALSE,
    addNodes = legendNodes
)

```

There are more examples  given in the documentation of `visLegend`

**Comment by kagestrife** [comment]
Yeah, what about the issue I had with the "dot" shape? Does it work ok this way? Thanks for helping.

**Comment by lordbitin** [comment]
Adding the shape to the legendNodes data.frame should work:

```{r}
legendNodes <- data.frame(
    label = c("A","B"),
    color.background = c("red","blue"),
    color.border = c("black", "white")
    shape = c("dot", "dot")
)
```

You can also set the `size` of each node type in the legend, in the case you want to highlight some group.

**Comment by kagestrife** [comment]
Ok, ill try it and come back to you later today, thank you.

**Comment by kagestrife** [comment]
UPDATE: I have tried all the above, but still
a) I want the grouping from my original nodes (useGroups = TRUE)
b) I found out that the problem with the overlapping is the size of the nodes/text
c) As you can see in the screenshots my nodes are dots in the network, but do not appear as such in the legend, I do not know of a way to change it. 
d) I do not know how to change the properties of the grouped nodes in the legend. I think that this should be added.
e) More options for the legend would be: making it so that it has a scrollbar if the nodes are many (such as my case), adding styling options for the nodes added from the useGroups, maybe have more options in how the nodes are placed, putting them one below the other is not optimal, as it restricts the whole legend bar, especially in styles such as dot, circle, square,which are also the most frequently used. What I suggest, is putting them in duos, 2 nodes in one line and so on.
![problem](https://cloud.githubusercontent.com/assets/9630888/19733692/687c128c-9bad-11e6-8ac2-2d7f34726283.png)
![problem-big](https://cloud.githubusercontent.com/assets/9630888/19733693/687befaa-9bad-11e6-8a8d-82dada47affc.png)
![problem-groups](https://cloud.githubusercontent.com/assets/9630888/19733695/689c293c-9bad-11e6-82be-c420c415ba55.png)

**Comment by bthieurmel** [comment]
Hi,
I'm working on some improvement. (Fixing some overlap bu and adding columns possibililies).
Coming soon...

But for big legend, I think it's better to plot another network.

**Comment by bthieurmel** [comment]
I've just push some modifications on github. You can now divide legend in columns.

For other control (size, placement, color, ...), you can use all ``font`` argument`` for nodes and for edges.

**Comment by lordbitin** [comment]
Thanks a lot! I'ill give it a try asap

**Comment by kagestrife** [comment]
Ill close the issue now.
