### ISSUE TITLE
undirected edges instead of to;from

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#111]
I have a graph in which I want to have only "to" arrows and if I have A->B and B->A, I want it to give me an undirected edge, instead of 2 edges with "to" arrows on them. Is there any way to achieve it through the visNetwork edges' options, or do I have to make an algorithm and define each edge separately?

**Comment by bthieurmel** [comment]
You have to use the ``arrows`` argument for ``visEdges``, and treat you special case before (A->B and B->A equal to A-B).

**Comment by kagestrife** [comment]
Can you give me a code example of the syntax?
