### ISSUE TITLE
highlighNearest does not mark in bold the neighbours

### ISSUE THREAD

**Issue by lordbitin** [datastorm-open/visNetwork#113]
Hi,

I am having troubles when trying to highlight the neighbours of a selected node.

I am using this code:

``` r
                                 visOptions(
                                     highlightNearest = list(
                                         enabled = T,
                                         degree = 1,
                                         hover = F,
                                         algorithm = "hierarchical"
                                     )
```

but it seems that only the label of the selected node is marked in bold. How can I mark the neighbors in bold too?

Thanks in advance!

**Comment by bthieurmel** [comment]
label in bold is not directly part of ``highlightNearest`` but it's a global ``vis.js`` style. When we select a node, his label is marked in bold.
 
``highlightNearest`` keep n degree neighbors visibled, and the others as gray.

**Comment by lordbitin** [comment]
Mmmm I understand. So, in order to achieve my goal,  I think I could add a `visEvent` with the event "selectNode", associated to a javascript function that sets the connected nodes as selected too.

I will try it and post the results

Thankssss!
