### ISSUE TITLE
tooltip/title hover location changed from 1.0.2 -> 1.0.3 (dev)

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#115]
#Hi - it seems as if the hover location changed in versions? The hover title is located in higher Y position. Not sure if this a bug or expected behavior. This seems to happen in shiny but not a desktop plot.
Looks like this could have been introduced when the tooltip popup delay was?

**Comment by bthieurmel** [comment]
Yes, the tooltip popup delay improvement (to enable click on) bring some bug / modification I've to solve actually. One is the location, and the second is the edges tooltip.

I'm working on this when have time....!

**Comment by bthieurmel** [comment]
Add modification to fix it today, and you can now add css and control delay with ``visInteraction``

**Comment by dockstreet** [comment]
Seems to be much better, not sure what else I should verify? Not seeing the behavior like before, so perhaps it is fixed.

**Comment by bthieurmel** [comment]
Nothing to verify. Tooltip seems good in Rstudio, any browser and with shiny.
