### ISSUE TITLE
#bug/#question: tooltip/title hovering and not clickable

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#116]
I'm trying to attach html hyperlinks to the node titles to make them clickable but the constant hovering of the title won't let it be caught by the mouse pad. Any hints on how to avoid such behavior? See figure. Link is not clickable. 

Thanks for your help

![screen shot 2016-11-21 at 3 40 10 pm](https://cloud.githubusercontent.com/assets/21988312/20488964/d8a3ad88-b000-11e6-902e-15a7fffbfc97.png)

**Comment by bthieurmel** [comment]
It's possible with dev ``1.0.3`` version, and you can also add css and control delay with ``visInteraction``

**Comment by alexDeCastroAtGit** [comment]
Thanks!
