### ISSUE TITLE
#question/#enhancement: is it possible to link legend with select by group? 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#118]
I quite like both features the legend, and the scroll buttom for selecting groups in the network, but is it/would it be possible to the link the two. 

Scenario: I have groups displayed in the legend using different symbols and colors, and I'd like to click on them so we can scope out the specific group members in the network. 

Let me know if it's already possible in the current version. Thanks!

**Comment by bthieurmel** [comment]
It's currently not possible, but already asked ...! #36.
A quite big improvement, but possible with in futur.

**Comment by alexDeCastroAtGit** [comment]
Thanks @bthieurmel !
