### ISSUE TITLE
Controlling Node Order in Hierarchical Layout

### ISSUE THREAD

**Issue by rtaph** [datastorm-open/visNetwork#119]
Hi there,

Great package!

Is there way to control the horizontal ordering of nodes in a hierarchical graph (as apposed to the vertical ordering, controlled by the "level" variable?). More generally, how does the ID or sorting arrangement of the nodes and edges determine the (within-level) ordering?

Thanks,

**Comment by bthieurmel** [comment]
Hi,

Related to this post https://github.com/almende/vis/issues/1536, and after a little test, it's possible to do that passing also ``x`` coordinate. "The order can be defined by giving them an initial position. The initial position will be used for the ordering of the nodes so x = 4 will be to the left of x = 5."

``
require(visNetwork)
nodes <- data.frame(id = 1:4, label = 1:4, level = c(1, 2, 2, 2), x = c(1,3,1,2))
edges <- data.frame(from = c(1,1,1), to = c(2,3,4))

visNetwork(nodes, edges) %>%
  visHierarchicalLayout()


nodes <- data.frame(id = 1:4, label = 1:4, level = c(1, 2, 2, 2), x = c(1,2,3,1))
edges <- data.frame(from = c(1,1,1), to = c(2,3,4))

visNetwork(nodes, edges) %>%
  visHierarchicalLayout()
``

**Comment by rtaph** [comment]
Works like a charm, and so easy to implement. Thank you!

**Comment by ashminkaul** [comment]
Hi, I have an addon query on this, if you remove the  visHierarchicalLayout() and level variable in the data frame, every time you run you get random positions of nodes in the network. If I just want the first node numbered 1 to always appear at the top of the graph, please help me with the same.

**Comment by ZaidRehman** [comment]
You can use randomSeed property of Layout. Below link of documentation can help you. 
 http://visjs.org/docs/network/layout.html
