### ISSUE TITLE
Retrieve and use the Edge ID with visEvents()

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#120]
I am using the visEvents() function to select an edge. When I select the edge i want to use js, so that I can retrieve the label of the current selected edge. Is there any way to have access to a specific edge's attributes (ie label) by this id?

By using the code below, I have retrieved the edge id.
`visEvents(selectEdge = "function(properties) { alert('selected edge:'+ properties.edges ); }")`

**Comment by bthieurmel** [comment]
You can access data with a visEvents with ``this.body.data.``. Moreover, on ``this.body.data.nodes`` and ``this.body.data.edges``, you can also use the http://visjs.org/docs/data/dataset.html API. This is a simple example without the API : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), label = "lab")

visNetwork(nodes, edges) %>%
  visEvents(selectEdge = "function(properties) { alert(this.body.data.edges._data[properties.edges[0]].label); }")
````

**Comment by kagestrife** [comment]
thank you a lot, this is exactly what I needed. Closed.
