### ISSUE TITLE
#question/#bug(?): node size increasing proportional to label size in the circle case? 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#121]
Is it possible to control the node size when we have arbitrary size labels, say document titles? 
![screen shot 2016-12-01 at 9 44 05 am](https://cloud.githubusercontent.com/assets/21988312/20788995/c3712bfa-b7aa-11e6-8e7a-b46d7337aab5.png)

**Comment by alexDeCastroAtGit** [comment]
I guess, I could formulate my question differently: can I have labels outside a node in the circle case?

**Comment by lordbitin** [comment]
Why not using `shape=dot`?

**Comment by alexDeCastroAtGit** [comment]
Thanks @lordbitin , that works! I'm still having trouble customising the shape: all the dots seem to be drawn to the same size though they have different values. ANy pointers?

**Comment by lordbitin** [comment]
Try changing the value of the argument `size` in the function `visNodes`

**Comment by bthieurmel** [comment]
You can also play with ``scaling`` options : 

``
nodes <- data.frame(id = 1:3, value = c(10,20,30), 
                    label = c("a", "aaaaa", "aaaaaa"))
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visNodes(shape = "circle", scaling = list(label = list(min = 1, max = 15)))

visNetwork(nodes, edges) %>%
  visNodes(shape = "dot", scaling = list(min = 5, max = 15))
``

**Comment by alexDeCastroAtGit** [comment]
ah ok, thanks!

**Comment by alexDeCastroAtGit** [comment]
PS.: is it possible to show linkage only upon clicking? I have a really dense network, and with the edges displayed the image is really ink dense. I was looking for a workaround for local edge display, as well as maybe, a dynamic rendering of the network where upon selection (via button) only the nodes and their neighbors show up. Anyhow, food for thought/speculations.

**Comment by skanskan** [comment]
I had this problem some time ago and solved it with a trick, not perfect but it works:

```
labtemp <- strrep(" ",((max(nchar(label))-nchar(label))*1.7)%/%2)     
# You will need to finetune the number.
label <- paste0(labtemp,nodesd, labtemp)
```
Now use that new label.
