### ISSUE TITLE
Export() to produce distributable web page

### ISSUE THREAD

**Issue by hyanwong** [datastorm-open/visNetwork#123]
Is there a way to produce a web page visualization that can be emailed to people which can simply be viewed in their browser. I was able to construct something of the sort by simply replacing the .js and .css links at the top of a index.html file with internet urls, although I don't know if the urls are always going to stay correct. I.e. I replaced

```
<script src="lib/htmlwidgets-0.8/htmlwidgets.js"></script>
<link href="lib/vis-4.16.1/vis.min.css" rel="stylesheet" />
<script src="lib/vis-4.16.1/vis.min.js"></script>
<script src="lib/visNetwork-binding-1.0.2/visNetwork.js"></script>
```

with

```
<script src="http://www.htmlwidgets.org/libs/htmlwidgets/htmlwidgets.js"></script>
<link href="http://visjs.org/dist/vis.min.css" rel="stylesheet" />
<script src="http://visjs.org/dist/vis.min.js"></script>
<script src="http://datastorm-open.github.io/visNetwork/libs/visNetwork-binding/visNetwork.js"></script>
```

And the html file then works from any computer in any directory. Perhaps this could be an option to the export() command?

**Comment by bthieurmel** [comment]
``?visSave`` ??

**Comment by hyanwong** [comment]
Missed this. Sorry. Could you put a link to it in the manual page for visExport, maybe?

**Comment by bthieurmel** [comment]
Yes. Done.

**Comment by hyanwong** [comment]
Thanks, and sorry for being dense. Doh.

**Comment by hyanwong** [comment]
Actually, now I look at visSave(), I see that you can't export using remote links. You can only do local links, or base64 encoded. I appreciate that some might object to referring to a remote source, and there might be version compatibility issues, but it would be neat if it could be done.
