### ISSUE TITLE
list of items in title or in another field.

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#124]
What I want, is to have some links stored in an edge, so that I'll be able to retrieve them via visEvents and have them in an alert box, onclick. For now, Im stuck in the first step, since I can add one link in the title element of the edge, but not a list of links. Is there a way to bypass this?

Thanks.

**Comment by bthieurmel** [comment]
Using a data.frame structure, you can any columns you want : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), info1 = "info1", info2 = "info2")

visNetwork(nodes, edges) %>%
  visEvents(selectEdge = "function(properties) { alert(this.body.data.edges._data[properties.edges[0]].info1); }")
````

**Comment by bthieurmel** [comment]
And normally you can pass data as list, but there is a bug at moment. Coming soon with another example using list rather data.frame like this : 

````
edges <- list(list(id = 1, to = 1, info = list("info1", "info2")),
              list(id = 2, to = 3, info = list("info1", "info2")))
````

**Comment by bthieurmel** [comment]
Now with dev version : 

````
nodes <- data.frame(id = 1:3)
edges <- list(list(from = 1, to = 1, info = list("info1", "info2")),
              list(from = 2, to = 3, info = list("info1", "info2")))
visNetwork(nodes, edges) %>%
  visEvents(selectEdge = "function(properties) { alert(this.body.data.edges._data[properties.edges[0]].info); }")
````
