### ISSUE TITLE
#bug/typo: vignette for visEvent example (nothing major)

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#125]
`visNetwork(nodes, edges) %>%
 visEvents(select = "function(properties) {
     alert('selected nodes: ' + properties.nodes);}", 
     dragEnd = "function(properties) {
     alert('finsih to drag');}")`

**alert message is mistyped**

**Comment by bthieurmel** [comment]
Don't understand... In what case you have a problem / this message ?

Thanks.

**Comment by ZedLeb** [comment]
I see 'finsih' instead of I'm guessing.. 'finish'.
Common typo that 😀

**Comment by bthieurmel** [comment]
Thanks. fix.
