### ISSUE TITLE
#question: centered view and position of widgets

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#126]
Hi, is it possible to center the view of a network to a specific node by default and have the network zoomed to a small neighborhood of that node? 

The reason I'm asking, is that I'd like to embed the centered/zoomed network in an iframe (http://www.w3schools.com/tags/tag_iframe.asp), so different pages focus on different parts of the network. 

I'll keep digging the documentation. 

Thanks,
Alex

**Comment by bthieurmel** [comment]
You can look at this discussion : set up initial zooming level #46

More globally, you can use ``events`` and ``methods``  when you want. This is some examples : 

````
nnodes <- 200
nnedges <- 400

nodes <- data.frame(id = 1:nnodes)
edges <- data.frame(from = sample(1:nnodes, nnedges, replace = T), 
                    to = sample(1:nnodes, nnedges, replace = T))
 
visNetwork(nodes, edges)%>% 
  visIgraphLayout()

# with defaut layout
visNetwork(nodes, edges) %>% 
  visIgraphLayout()%>%
  visEvents(type = "once", startStabilizing = "function() {
    this.moveTo({scale:0.5})}")

visNetwork(nodes, edges) %>% 
  visIgraphLayout() %>%
  visEvents(type = "once", startStabilizing = "function() {
    this.fit({nodes:[1,5,10]})}")
````
