### ISSUE TITLE
#issue: selfContained option in visSave not working 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#127]
saveFile <- visSave(net.html, file=fileName, selfcontained = T) where net.html is the output of the VisNetwork function. 

All of the support folders (e.g.: htmlwidgets, vis, binding) etc are still being generated.

**Comment by bthieurmel** [comment]
Hi. Can you send me an example please ?

**Comment by alexDeCastroAtGit** [comment]
Hi, funny enough, after flushing out my environment the issue disappeared. 

I tested with 
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))
net <- visNetwork(nodes, edges, main = "visNetwork minimal example")
saveFile <- visSave(net, file="net_1", selfcontained = T)
saveFile <- visSave(net, file="net_2", selfcontained = F)

Apologies! One issue less :-)
