### ISSUE TITLE
question : possible to hide edge text initially and display on hover?

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#128]
Hi,

Is it possible to have the edge label text hidden and only display on hovering? This could help clean up the labels some if it's very involved. 

Thanks!

**Comment by ZedLeb** [comment]
This would be a great help in my project too.  I'm trying to work with `visSetSelection` to highlight only certain edges based on a user input (and struggling - see my other question...).  

If the labels could be hidden and only display when edges are selected that would also be fantastic.

This package is incredible - I love the interactivity it provides via Shiny!

**Comment by bthieurmel** [comment]
Related to Retrieve and use the Edge ID with visEvents() #120.

You can access data with a visEvents with ``this.body.data.``. Moreover, on ``this.body.data.nodes`` and ``this.body.data.edges``, you can also use the http://visjs.org/docs/data/dataset.html API. 

A example for your case : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), label = "Edge label", font.size = 0)
visNetwork(nodes, edges) %>%
  visInteraction(hover = T) %>%
  visEvents(hoverEdge = "function(e){
    this.body.data.edges.update({id: e.edge, font: {size : 14}});
  }") %>%
  visEvents(blurEdge = "function(e){
    this.body.data.edges.update({id: e.edge, font: {size : 0}});
  }")
````

**Comment by dockstreet** [comment]
Perfect! Happy Holidays !

**Comment by ZedLeb** [comment]
I changed to using `title` instead to see the difference - and it works well. I see the information when I hover. Though the ability to display only when selected will be good too.

I don't quite understand the difference between `title` and `label` - need to read up on this!

**Comment by bthieurmel** [comment]
Yes, ``title`` doing the job if you don't need this for other things.

``title`` is a html tooltip, customizabled. Here is simple example you can find in ``?visInteraction`` : 

```` 
nodes <- data.frame(id = 1:10, 
 title = '<a target="_blank" href="https://github.com/datastorm-open/visNetwork">github</a>')
edges <- data.frame(from = round(runif(8)*10), to = round(runif(8)*10))

# custom tooltip
visNetwork(nodes, edges) %>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: cursive;font-size:18px;font-color:purple;background-color: red;')
````

**Comment by dockstreet** [comment]
Any thoughts how I could get past the blurEdge issue when I go to a node from an edge mentioned above with the label? Or if there is a way to clear all of the edge lables with a time out? 

I tried this, but it seems as if the update didn't work. I guess I'm looking for a global event on the canvas perhaps like how the timer was done on the tool tip to clear out tooltip, maybe and run an update for all of the edge labels to clear after a point in time. That's because it seems as if blurEdge won't catch all cases


`  visEvents(blurEdge = "function(e){
            edgeIds = this.body.data.edges.getIds();
            
            edgeIds.forEach(function(item) {
             this.body.data.edges.update([{id: item, font: {size : 0}}]);
            })

  }")`

**Comment by dockstreet** [comment]
Besides the above, it looks as if vis may have updated blurEdge to fire when it should. Would be nice to know if there was a way to run for all edges, still if they fixed what I was seeing . Importing the below could help perhaps - cheers!

https://github.com/almende/vis/issues/1911

**Comment by bthieurmel** [comment]
``visNetwork dev`` already use latest ``vis.js 4.17.0``. It seems that bug don't be fix. I've just write a comment on vis.js github

**Comment by dockstreet** [comment]
Hi - looks like vis.js may have the fix in 4.18 release, can it be pulled in to verify?

**Comment by bthieurmel** [comment]
Done on github.

**Comment by obkhan** [comment]
Hi - I confirm that the issue I have seeing has been fixed - thanks @bthieurmel !

**Comment by dockstreet** [comment]
I just tested the latest version in for what I was seeing, I have not tested the other issues reported with the self reference as completely. I'm going to close this issue for what I have been able to test - thanks again @bthieurmel !
