### ISSUE TITLE
question:  visSetSelection for multiple edges (“group” of edges?)

### ISSUE THREAD

**Issue by ZedLeb** [datastorm-open/visNetwork#129]
I have tried to emulate this original example code for selecting multiple edges
```
observe({
  nodes_selection <- input$selnodes
  edges_selection <- input$seledges
  visNetworkProxy("network_proxy_select") %>%
    visSetSelection(nodesId = nodes_selection, edgesId = edges_selection)
})
```
which works exactly as expected when I run it.

I am building a `visNetwork` of all the systems that we use in our company and their (data) interactions.  I want to be able to demonstrate that a data input in one system can impact other systems.  One way we want to do this is by picking a ‘theme’ of data such as a change to a mould used in the factory (currently affecting at least five different systems).

There is a column in my edge dataframe for theme.  Each edge also has an ID - as I thought that would be necessary when when we pick a theme.

My code below currently picks the IDs but I did try a version of `selectInput` that uses `choices = edges$theme` - which correctly displays the theme choice but I’m stuck at translating this choice into a filtered list of IDs.

So - my problem is twofold:

1. **When I run my version of the original code – my edges are not selected (they are not highlighted) – is there any clue why my code doesn’t do the same as the original?**
2. **I actually want my user to be able to select a ‘Theme’ from the input box which then translates to a number of IDs – all of which I want to be shown as selected.  I think this is like a group but for edges.  Can anyone tell me if this is possible?**

**My UI function**
```
ui <- fluidPage(
  
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "seledges", label = "Theme", choices = edges$ID, multiple = TRUE)
    ),
    mainPanel(visNetworkOutput("network_proxy_select"))
  )
  
)

```

**My server function**
```
server <- function(input, output) {
  output$network_proxy_select <- renderVisNetwork({

  
    visNetwork(nodes, edges, height = "100%", width = "100%") %>%
      visOptions(highlightNearest = TRUE) %>%
      visLayout(randomSeed = 123)
  })
  

   observe({

     nodes_selection <- input$selnodes
     edges_selection <- input$seledges

     visNetworkProxy("network_proxy_select") %>%
       visSetSelection(nodesId = nodes_selection, edgesId = edges_selection)
  })
  
}

```

**Comment by ZedLeb** [comment]
![network](https://cloud.githubusercontent.com/assets/8373677/21147049/fc3713de-c153-11e6-83ef-1604b40e15e6.png)
Here's a screendump of what I have so far.  In the image one of the nodes has been selected by mouseclick.

However, I would like to be able to select 'Moule' from the inputbox and see all of the edges which contain this theme highlighted...

The code I've been trying to get to work is 
```
   observe({

     edges_input <- input$seledges

     edges_selection <- edges %>%
       filter(str_detect(theme, edges_input)) %>%
       select(ID) %>%
       .$ID
 
     visNetworkProxy("network_proxy_select") %>%
       visSetSelection(edgesId = edges_selection)
  })
  
}
```

I know this code works to select the IDs into a vector but within Shiny it falls over I'm guessing because it needs a default value to start with...I don't know how to give it a default value when the `selectInput` = `multiple = TRUE` :(

Any help very much appreciated!

**Comment by ZedLeb** [comment]
Leave an idiot alone long enough....I've answered my first problem - I was using `ID` instead of `id` 

`visSelectEdges(id = edges_selection)`

Only took 24 hours to work that out!!  I can now replicate the original code and select multiple IDs - sorry ids :) in my Shiny app

However, I'm still battling with the other problem of needing to select a group of multiple IDs by a shared theme...

Using this sort of filter 

```
    edges_selection <- edges %>%
     filter(str_detect(theme, edges_input)) %>%
     select(id) %>%
     .$id
```
having used `edges$theme `as my `choice `in `selectInput`

**Comment by bthieurmel** [comment]
``?updateSelectInput`` is perhaps the answer ?

**Comment by ZedLeb** [comment]
Thank you for your prompt response! Look forward to trying this out tomorrow at work - will keep you posted.

Also i picked up some code from a response from you on SE regarding using Shiny Dashboard - it's worked really well for my project.

 Thanks so much for all your hard work - it's much appreciated

**Comment by ZedLeb** [comment]
Made some really good progress - I think my main problem was I was trying to update the same input box with new information - so I just added a text box and used your 'update' solution.

However I'm still stuck with making `visSelectEdges` use the multiple IDs that are taken from the text input.

Following a selection from the selectInput box, my IDs appear in the textInput box (`input$seledges`) like this 

3,4,5,6,7,8,9,10,17,19,21,23,24,25

How can these be translated in `id  = current_edge` in the server function to enable all the relevant edges to be highlighted?

```
server <- function(input, output, session) {
  
  output$network_proxy <- renderVisNetwork({
    
    updateTextInput(session, "seledges", value = edges$id[edges$theme %in% input$seltheme])
    current_edge <- input$seledges
    visNetworkProxy("network_proxy") %>% 
      visSelectEdges(id  = current_edge)
    
    visNetwork(nodes, edges)%>%
      visNodes(shape = "circle",
               scaling = list(min = "10", max = "100",
                              label = list(enabled = TRUE)))%>%
      visOptions(highlightNearest = TRUE) %>%
      #visLayout(randomSeed = 123 )%>%
      visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, main = "System Type") %>%
      visExport()
  })   
  
} #end server
```
Any ideas gratefully received!

**Comment by bthieurmel** [comment]
I think you have to use ``selectInput`` and ``updateSelectInput``, just using perhaps the right syntax.

````
# ui.R
selectInput("seledges", "Edges : ", choices = NULL, multiple = T)

# server.R
observe({
    values <- edges$id[edges$theme %in% input$seltheme]
    updateSelectInput(session, "seledges", "Edges :  ", choices = values , selected = values )
})
````

**Comment by bthieurmel** [comment]
And it's better to use ``update`` function in a ``observe`` rather than in a render definition.

**Comment by ZedLeb** [comment]
Fantastic!  This works great - thank you so much.  

I did as you said about using `inputSelect` and also the `observe` (although I don't yet understand `observe`...I'm sure it'll be clearer one day!)
```
server <- function(input, output, session) {

    output$network_proxy <- renderVisNetwork({
    
    observe({
    values = edges$id[edges$theme %in% input$seltheme]
    updateSelectInput(session, "seledges", "Edges : ", choices = values, selected = values)
    visNetworkProxy("network_proxy") %>% 
       visSelectEdges(id  = values)
    })
    
    visNetwork(nodes, edges)%>%
      visNodes(shape = "circle",
               scaling = list(min = "10", max = "100",
                              label = list(enabled = TRUE)))%>%
      visOptions(highlightNearest = TRUE) %>%
      visLayout(randomSeed = 2)%>%
      visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, main = "System Type") %>%
      visExport()
  })   
 } #end server
```
As you can see from the screenshot below - I have yet to connect all my other nodes.  It's going to get very busy and confusing - so I'm going to spend a bit of time tomorrow working out how to _hide_  all the other edges and leaving only the selected visible.  So for example below, you would only see the selected edges (the other 'flower' would disappear!) 

Thanks again for all your help.

![dash](https://cloud.githubusercontent.com/assets/8373677/21225334/a4c22174-c2d0-11e6-9cdf-f45fbb79f175.png)

**Comment by ZedLeb** [comment]
I've made some progress in only showing edges for the selected theme.
The code below displays all the nodes with all edges hidden until a theme is selected.

However, when a selection is made - ~ALL edges are shown.  How can I force visEdges to only 'unhide' the selected edges?
 (_By the way Benoit I notice you are in Paris - I'm in Granville in Manche - we are practically les voisins!_)
```
server <- function(input, output, session) {
  
  output$network_proxy <- renderVisNetwork({
    
    observe({
       values = edges$id[edges$theme %in% input$seltheme]
       updateSelectInput(session, "seledges", "Edges : ", choices = values, selected = values)
       visNetworkProxy("network_proxy") %>%
         visSetSelection(edgesId = values) %>%
         visEdges(id = values, hidden = FALSE)
    })
    
      visNetwork(nodes, edges) %>%
      visNodes(shape = "circle",
               scaling = list(min = "10", max = "100",
                              label = list(enabled = TRUE))) %>%
      visEdges(hidden = TRUE) %>%
      visOptions(highlightNearest = TRUE) %>%
      visLayout(randomSeed = 4) %>%
      visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, main = "System Type") %>%
      visExport()
  })   
  
} #end server
```

**Comment by Coraline66** [comment]
How did you define the "edges$id"? I'm trying to do similar things but kept getting error.
Thanks!
