### ISSUE TITLE
#question/#enhancement: having problems with customising node size

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [datastorm-open/visNetwork#130]
Hi Benoit, another question: 

from what I understand from issue #103 the customScalingFunction should be provided as a string literal of a json funciton. 

```
visNodes(scaling=list(customScalingFunction= 
                            'function (value) { 
                          return Math.log(1 + value); 
                          }'), 
             physics=T
    ) %>% 
```
I have to use the log because I'm scaling size based on the number of incoming edges, and these numbers are big in my case. 

It's a newbie question, but which variable 

> value 

is the function reading: the one passed locally or the node parameters? Would you mind posting an example here? 

Maybe as a feature request, I'd like to request a bit more info on that option for the visNetwork documentation. 

Many thanks
Alex

**Comment by alexDeCastroAtGit** [comment]
I cannot see my nodes changing size. :-(

**Comment by bthieurmel** [comment]
size is based on ``value`` column passed to node data.frame, and after rescale by ``vis.js`` using ``scaling.min``, ``scaling.max`` and ``scaling.customScalingFunction``.

``scaling.customScalingFunction`` must return a value between 0 and 1.

In your case, you can perhaps pass ``value=log( number of incoming edges)``, and then just changing ``scaling.min``, ``scaling.max`` if needed ?

**Comment by alexDeCastroAtGit** [comment]
Strange, value still not being scaled... I have node values ranging from 1 to 5, in an example and they don't scale properly.. will try to debug again. Thanks

**Comment by alexDeCastroAtGit** [comment]
Still doesn't work Benoit, I don't know if it's a local environment issue or how I'm customising my network
Here's my code: 

`visNetwork(nodes=Nodes, edges=Edges, width = "100%") %>% 
    visPhysics(stabilization = T,
               barnesHut = list("gravitationalConstant"=-5e4,
                                "avoidOverlap"=1,
                                "springLength"=600),
               enabled = T) %>%
    visIgraphLayout(
      physics = T,
      smooth = T,
      randomSeed = set.seed(-1),
      type = "full") %>% # using igraph layout
    visOptions(autoResize = F, 
               highlightNearest = list("enabled"=T, 
                                       "hover"=T, 
                                       "algorithm"="all", # or "hierarchical"
                                       "degree" = 1),
               nodesIdSelection = list(enabled=T, selected=here), 
               selectedBy="group") %>% #list(variable="group", "multiple"=T) %>% 
    visEdges(#color = "blue", 
             #physics = T,
             #length = 250,
             selectionWidth = 2.0,
             hidden = isHidden, # constant passed to parent function
             smooth = T,
             color = list(hover = "blue"),
             hoverWidth = 2.5,
             #dashes = T,
             arrowStrikethrough=F) %>%  
    assign("net.html", ., .GlobalEnv)
`
 

>     from    to label_from label_to    weight
>  1   5936  5906       docs     docs 0.7533201
>  2   5936 27564       docs     docs 0.7567778
>  3   5936 27616       docs     docs 0.7616034
>  4   5936  6053       docs     docs 0.7854225
>  5   5936  5938       docs     docs 0.7910611
>  6  24883 24972       docs     docs 0.7569752
>  7  24883  1564       docs     docs 0.7589835
>  8  24883  3263       docs     docs 0.7771488
>  9  24883  3265       docs     docs 0.7840934
>  10 24883  2878       docs     docs 0.7884597

With values

> 
>  1564  2878  3263  3265  5906  5936  5938  6053 24883 24972 27564 27616 
>     1     1     1     1     1     5     1     1     5     1     1     1

**Comment by ZedLeb** [comment]
I've also been struggling with this issue - looked all over for some examples of how to keep the same node size (as circle) while the text inside scales accordingly.  This is the best I've come up with so far but it required quite a bit of fiddling with the relative values in my nodes df to try to manually create a set of values which would give circles of roughly the same size.

```
visNetwork(nodes, edges)%>%
  visNodes(shape = "circle",
           scaling = list(min = "10", max = "100", 
                          label = list(enabled = TRUE)))%>%
  visOptions(highlightNearest = TRUE) %>%
  visLayout(randomSeed = 123 )%>%
  visLegend(addEdges = ledges, addNodes = lnodes, useGroups = FALSE, main = "System Type") %>%
  visExport()
```
Gives me this - but it's still not exactly what I want!
![network 3](https://cloud.githubusercontent.com/assets/8373677/21216389/cf23839c-c2a6-11e6-99f9-1aa7f424631e.png)
