### ISSUE TITLE
question: how to highlight a pathway/how to sum edge values

### ISSUE THREAD

**Issue by epaulukonis** [datastorm-open/visNetwork#131]
I'm attempting to create an interactive network that allows for users to choose a pathway between nodes and get a summed value of the weights of the edges connecting them (similar to something in trophic ecosystem network analysis).

I've managed to figure out how to select nodes that I'm interested in using visSetSelection from the proxy example. 

Here's an example of my network and a sample selected pathway.
![shinycap](https://cloud.githubusercontent.com/assets/24611905/21363087/bc80efa0-c6b0-11e6-88ef-ae00fdd824ae.JPG)

I'm trying to do two things:
**1.  Highlight ONLY the edges connecting these nodes and hide all others (make a distinct pathway).** 
**2. Return a sum of the values of the edges (aka the weights).**

I've searched around the current and old issues for an answer, but as I'm relatively new to using shiny, I'm a bit stuck. I think my question is partially similar to Zedleb's question about highlighting only edges in a certain theme. I'm still not certain if it's possible to only highlight the edges between distinct nodes (highlightNearest is closest I've gotten, but issue is that other nodes not pertaining to pathway still show). 

I'm thinking I need to distinctly assign a value for each to/from connection (which I did in seledges), but I'm not sure how to specify that visually. Haven't even gotten to summing yet. 

_My server:_

server<-function(input,output){
  output$network_proxy<-renderVisNetwork({
   
    visNetwork(nodes,edges) %>%
      visIgraphLayout() %>%
      visNodes (nodes$label) %>%
      visNodes (nodes$title) %>%
      visLegend(addEdges = ledges,useGroups=F)%>%
      visInteraction(multiselect=T,selectable=T)
  })
  
  observe({
    nodes_selection<-input$selnodes
    edges_selection<-input$seledges
    visNetworkProxy("network_proxy") %>%
      visSetSelection(edgesId = edges_selection,nodesId=nodes_selection)
  })
}

_My ui:_

ui <- fluidPage(
  visNetworkOutput("network_proxy", height = "400px"),
      selectInput(inputId = "selnodes", label = "Pathway", choices = nodes$id, multiple = TRUE) 
)

shinyApp(ui=ui,server=server)

Note that I haven't added an input for edges. Even when I do add an input for distinct edges between nodes, nothing happens (edges aren't selected). 

Any advice or direction towards documentation that might help is appreciated! Sorry for the relatively simple question...

**Comment by bthieurmel** [comment]
Hi,

First, in order to select edge, you need to set an ``id`` as for node.

Then, you can highlight some edges using some tricks and color definition. This is a simple apps playing with this : 

````
require(shiny)
require(visNetwork)

server <- function(input, output) {
  output$vis <- renderVisNetwork({
    nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                        group = sample(LETTERS[1:3], 15, replace = TRUE))
    
    edges <- data.frame(id = 1:15, from = trunc(runif(15)*(15-1))+1,
                        to = trunc(runif(15)*(15-1))+1)
    
    
    visNetwork(nodes, edges) %>% 
      visEdges(color = list(color = "white",highlight ="red",hover = "blue")) %>%
      visInteraction(hover = T)
  })
  
  observe({
    nodes_selection <- input$selnodes
    visNetworkProxy("vis") %>%
      visSelectNodes(id = nodes_selection)
  })
  
  observe({
    edges_selection <- input$seledges
    visNetworkProxy("vis") %>%
      visSelectEdges(id = edges_selection)
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput(inputId = "selnodes", label = "Nodes selection", choices = 1:15, multiple = TRUE),
      selectInput(inputId = "seledges", label = "Edges selection", choices = 1:15, multiple = TRUE)
    ),
    column(
      width = 8,
      visNetworkOutput("vis", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
````

**Comment by epaulukonis** [comment]
Hi bthieurmel,

Thanks for the reply! 

While it gets me close, I'm still having issues with my code and selecting individual edges. Right now it selects nodes (which is great), but highlights all edges each node is connected to.

For some reason, the edge selection isn't working at all. I'm guessing it definitely has something to do with my data structure. 

Can I ask about input$selnodes/input$seledges? Where does it look for the nodes/edges to select? I had first assumed I needed an additional data frame containing info about which nodes/edges I selected, but your code doesn't have that. 

(It's a very basic question, I apologize! Still very new to visNetwork).

**Comment by epaulukonis** [comment]
After looking over your nodes/edges, I think it's definitely the way my data is structured. Do the edges also require an "id" for each connection? I'm missing that (I only have to/from).

**Comment by epaulukonis** [comment]
So I ended up getting the edge selection to work by matching the number of nodes with the number of edges, as in your example above, using an id as you indicated. I can now see how to select individual edges, which is great. 

However, this only works when the number of edge IDs matches the number of node IDs. I must be missing something, because when I try to do more edges than match the 60 nodes I have (256 edges to 60 individual nodes) it doesn't work. But if I match the number of edge/node IDs to each other, it works fine, as in your example.

**Comment by ZedLeb** [comment]
Ah this is great!  I've come back to this project after doing some other work and Benoit's code has helped me move on and I can now show all my edges by theme. 
Thank you so much.

epaulukonis - I'm interested in your unique pathways idea as this might come in useful for how we prioritise data updates in our (multiplicity of!) systems.  Please post again if you arrive at a solution.
