### ISSUE TITLE
#question visSave with positions, visExport with high resolution

### ISSUE THREAD

**Issue by Dmirijs-Ozernovs** [datastorm-open/visNetwork#138]
Hi! 
I have to save large graphs with a lot of details from web browser. Graph is too big to fit on one screen with acceptable resolution. So, for now I just cut four screens and glue them in one picture in Paint. Saving in html format solves resolution problem, but saved html file keeps initial layout and I have to repeat all adjustments (nodes dragging for better visibility).
1. Is it possible to set resolution for the visExport function to be able to save png/pdf or any other format keeping small details visible?
2. Is it possible to save graph in html keeping the current (on screen) positions of the nodes?

**Comment by bthieurmel** [comment]
Hi,
Difficult or impossible with ``visExport`` and ``png\pdf``, but can find a way using ``shiny`` and ``visNetworkProxy`` : 
- add a process to store position with ``visGetPositions``
- render a new network with coordinate, and use ``fixed`` property or disable physics. And you can also increase the size and the resolution.

This is a simple example : 

````
library(shiny)
library(visNetwork)

# network data
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

# Define UI
ui <- shinyUI(fluidPage(
   visNetworkOutput("network"), 
   actionButton("store_position", "Store positions !"),
   downloadLink('downloadNetwork', 'Download network')
))

# Define server
server <- shinyServer(function(input, output) {
   output$network <- renderVisNetwork({
     visNetwork(nodes, edges) %>% visOptions(highlightNearest = TRUE) %>%
       visPhysics(enabled = FALSE) %>% visEdges(smooth = FALSE)
   })
   
   # get position info
   observeEvent(input$store_position, {
     visNetworkProxy("network") %>% visGetPositions()
   })
   
   # format positions
   nodes_positions <- reactive({
     positions <- input$network_positions
     if(!is.null(positions)){
       nodes_positions <- do.call("rbind", lapply(positions, function(x){ data.frame(x = x$x, y = x$y)}))
       nodes_positions$id <- names(positions)
       nodes_positions
     } else {
       NULL
     }
   })
   
   output$downloadNetwork <- downloadHandler(
     filename = function() {
       paste('network-', Sys.Date(), '.html', sep='')
     },
     content = function(con) {
       nodes_positions <- nodes_positions()
       if(!is.null(nodes_positions)){
         nodes_save <- merge(nodes, nodes_positions, by = "id", all = T)
       } else  {
         nodes_save <- nodes
       }
       
       visNetwork(nodes = nodes_save, edges = edges, height = "800px") %>%
         visOptions(highlightNearest = TRUE) %>% visExport() %>%
         visPhysics(enabled = FALSE) %>% visEdges(smooth = FALSE) %>% visSave(con)
     }
   )
   
})

# Run the application 
shinyApp(ui = ui, server = server)

````

**Comment by Dmirijs-Ozernovs** [comment]
Thanks a lot! This definitely solved my problem.

PS. I've spent two days trying to figure out why this approach doesn't work in my code. Then I realized than in "input$**network**_positions" the "network" is the name of the graph... :)

**Comment by amithit** [comment]
I have a graph component in React app,

```
<Graph
   graph={this.state.graph}
   options={graph_options}
   events={this.events}
/>
```
I hope to make it automatically zoom in/out when the graph changes, just like in vis.js document use network.fit()

But how I can call this fit method?

**Comment by gadepallivs** [comment]
Can you export highlighted subset of a large network as png ?
