### ISSUE TITLE
Edge value and font specification conflict

### ISSUE THREAD

**Issue by michaellevy** [datastorm-open/visNetwork#140]
When specifying an edge value, font parameters get ignored, e.g. `visEdges(font = list(size = 32), value = 3)`  prints the labels at the default size.

**Comment by bthieurmel** [comment]
Hi, in case of ``value``, you have to disable scaling for edges : 

``
visNetwork(nodes, edges) %>%
  visEdges(font = list(size = 50), value = 3, 
           scaling = list(label = list(enabled = FALSE)))
``
