### ISSUE TITLE
node shows up sometimes as "cluster" when double clicking node

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#141]
I'm seeing new behavior when double-clicking on items ? Is there a way to disable when clicking it showing up as a "cluster" node? I'm not sure where this node is being added, I didn't add it,  except that now when I double click a node it appears.

![image](https://cloud.githubusercontent.com/assets/1080803/22957549/02f27a68-f2f7-11e6-9344-2eb3104dc040.png)

**Comment by bthieurmel** [comment]
Yes, I think it's due to a unwanted push of dev/test code about a future collapsed feature.  Normally fix on github version.

**Comment by dockstreet** [comment]
Yep , pulled the latest down - issue no longer persists! Thanks!!!!
