### ISSUE TITLE
nodesIdSelection in ordered list

### ISSUE THREAD

**Issue by sebsfox** [datastorm-open/visNetwork#142]
Hi,

I __love__ the package - thanks for all the hard work on it!

I'm having problems with nodesIdSelection creating a dropdown menu of ordered ids. The ids it displays are currently in the row order in the nodes file.

My visNetwork has a circle layout, which was decided to be the best way of visualising this network, and the nodes are ordered in a specific way within the nodes variable so they sit in the right place in the circle (eg, they sit next to the correct neighbours).

I've attached my nodes and edges data in an xlsx format. The following script needs running to produce my network with my unordered list. 

As this is a product for many other users within my organisation, it would be a very useful enhancement to the package.

Many thanks

```
library(gtools)
profileCol <- "orange"
indicatorCol <- "dodgerblue"

# nodes data.frame for legend
lnodes <- data.frame(label = c("Profile", "Indicator"),
                     shape = c( "circle"),
                     color = c(profileCol,indicatorCol),
                     title = "Nodes",
                     id = 1:2)

# edges data.frame for legend
ledges <- data.frame(color = c(profileCol,indicatorCol),
                     label = c("Indicator received\nby profile",
                               "Indicator provided\nby profile"),
                     arrows =c("from", "to"))



indicatorSelection <- sort(nodes$id[nodes$type=="Indicator"])

net <- visNetwork(nodes, edges,
                  main = "Shared indicators within PHOLIO profiles",
                  width = "100%", height = "800px")  %>%
        visPhysics(enabled = FALSE) %>%
        visLegend(addEdges = ledges,
                  addNodes = lnodes,
                  useGroups = FALSE) %>%
        visNodes(group = "Profile name") %>%
        visIgraphLayout(layout = "layout_in_circle") %>%
        visOptions(highlightNearest = list(enabled =TRUE,
                                           degree = 0),
                   #nodesIdSelection = list(enabled = TRUE),
                   selectedBy = list(variable = "Profile name",
                                     values = mixedsort(levels(nodes$`Profile name`)),
                                     style = 'width: 300px; height: 26px'),
                   nodesIdSelection = list(enabled = TRUE,
                                           values = indicatorSelection))

net
```

[nodes and edges.xlsx](https://github.com/datastorm-open/visNetwork/files/793461/nodes.and.edges.xlsx)

**Comment by bthieurmel** [comment]
Correct this as soon as possible

**Comment by bthieurmel** [comment]
Fix on github/ dev version. Now order is preserve using ``values``.

**Comment by sebsfox** [comment]
Thank you for doing this so quickly! Really helpful :+1:
