### ISSUE TITLE
Setting transparent edges not compatable with visNetwork?

### ISSUE THREAD

**Issue by epaulukonis** [datastorm-open/visNetwork#145]
Hello,

I brought up a similar issue about modifying the visualization of my edges in issue #131 ; essentially, I'm trying to make it so that I can highlight a pathway between edges through a network while hiding all other edges.  

Bthieurmel offered a very helpful solution that works fairly well; using white as the primary color in visEdges. However, I'm wondering if it's possible to make the edges completely transparent; I'm still seeing the outline of some of the overlapping edges, especially for my more connected nodes. 

I've tried to set the primary color as transparent using this simple piece of code:

 mycol<- rgb(0,0,0,alpha=0)
  visEdges(color = list(color = 'mycol', highlight ="blue"))

But it only sets the edges as black. Is setting clear or transparent edges possible to do in visNetwork? 

Any advice is appreciated. Thanks!

**Comment by bthieurmel** [comment]
Hi,
It seems that for setting alpha transparent parameter, you should use directly ``rgba`` function like in ``visOptions`` : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visEdges(color = list(color = 'rgba(0,0,0,0)', highlight ="blue"))
````

**Comment by epaulukonis** [comment]
This worked great! Thank you so much.
