### ISSUE TITLE
question: can you show a different label for a node when hovering on it? 

### ISSUE THREAD

**Issue by mfalahi** [datastorm-open/visNetwork#146]
I'm plotting a network where each node's label is a long string of a few words. To avoid the labels becoming congested, I'm trying to label each node initially with a short string (only the first word), and then show the node's full label when hovering over it. Is it possible to assign nodes an alternate hover label with visEvents, hoverNode and blurNode?

Thanks

**Comment by bthieurmel** [comment]
Linked to this  #128, and using current dev version (``devtools::install_github("datastorm-open/visNetwork")``), you can do that for example like this : 

````

nodes <- data.frame(id = 1:3, label = paste0("short ....", 1:3), label_long = "very very very long....")
edges <- data.frame(from = c(1,2), to = c(1,3), label = "Edge label", font.size = 0)

visNetwork(nodes, edges) %>%
  visInteraction(hover = T) %>%
  visEvents(hoverNode  = "function(e){
            var label_info = this.body.data.nodes.get({
              fields: ['label', 'label_long'],
              filter: function (item) {
                return item.id === e.node
              },
              returnType :'Array'
            });
            this.body.data.nodes.update({id: e.node, label : label_info[0].label_long, label_long : label_info[0].label});
            }") %>% 
  visEvents(blurNode  = "function(e){
            var label_info = this.body.data.nodes.get({
              fields: ['label', 'label_long'],
              filter: function (item) {
                return item.id === e.node
              },
              returnType :'Array'
            });
            this.body.data.nodes.update({id: e.node, label : label_info[0].label_long, label_long : label_info[0].label});
            }")
````

**Comment by mfalahi** [comment]
This is great! Thanks.

**Comment by wlandau** [comment]
It has been a while since this issue was posted. Thoughts on implementing a way to do this with less user-side code?

**Comment by wlandau-lilly** [comment]
What about the text alignment? For me, hover labels automatically align to center, which is awkward for my use case.

**Comment by wlandau** [comment]
What about text alignment. I have multi-line hover labels and I would like to align the text left. The current default is center.
