### ISSUE TITLE
Link in tooltip

### ISSUE THREAD

**Issue by ThomasSiegmund** [datastorm-open/visNetwork#147]
Hi,

I tried to put hyperlinks in tooltips, but they come out broken: the html tags are there, but the slashes in the target path seem to be replaced by blanks. I tried to URLescape the path, but this also doesn't work.

Thanks a lot

Thomas

**Comment by bthieurmel** [comment]
Can you send me an example ?

**Comment by ThomasSiegmund** [comment]
Can't reproduce. Sorry for the noise.
