### ISSUE TITLE
Change network background colour?

### ISSUE THREAD

**Issue by niklasvm** [datastorm-open/visNetwork#151]
Is it possible to change the background colour of the plot?

**Comment by bthieurmel** [comment]
Not available using ``visNetwork`` only yet. Think about add this feature.

**Comment by niklasvm** [comment]
I found a workable solution using css. You can do something similar for shiny.

Example with *black* background:
```{r}
nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
edges <- data.frame(from = c(1,2), to = c(2,3))

v <- visNetwork(nodes, edges)

library(htmltools)
browsable(
  tagList(
    tags$head(
      tags$style('div.vis-network{background-color: black;}')  
    ),
    v
  )
)

```

**Comment by ThoDuyNguyen** [comment]
It would be nice if the library supports some pre-defined theme. 
Actually we could use CSS and code to explicitly set the theme but an easy way to construct custom theme always a great plus. Just my 2c

**Comment by bthieurmel** [comment]
Now possible in ``github`` with new argument  ``background`` in ``visNetwork`` function.
