### ISSUE TITLE
Duplicated nodes cause silent failure to render. Should show an error.

### ISSUE THREAD

**Issue by maxconway** [datastorm-open/visNetwork#152]
I think I've found a place where there is a missing error message in visNetwork.R

If the nodes data.frame contains duplicated ids, then the network fails to render without showing an error message. For instance:

```
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(data.frame(id = 1:3), edges) # works fine

visNetwork(data.frame(id = c(1:3,3)), edges) # fails, and doesn't say what's wrong
````

This could be fixed by adding something along these lines to visNetwork.R around line 219:

```
if(anyDuplicated(nodes$id)){
    stop("nodes must have unique ids")
}
```
Thanks, I hope I haven't misunderstood the expected behaviour

**Comment by bthieurmel** [comment]
Thanks. Add on github now.
