### ISSUE TITLE
Bug? multiselect = TRUE and highlightNearest

### ISSUE THREAD

**Issue by jeffkeller87** [datastorm-open/visNetwork#153]
It appears that these two options only partially work when used together. Take the example below.

Try selecting `Label 3`, then control-click `Label 8`. `Label 8` and its edges do appear to be getting bolded, but it is not being highlighted. The bolding happens to it while it is still greyed out.

Something else that is odd. Start over and try control-clicking `Label 8`, then control-click `Label 3`. Now keep control-clicking `Label 3` and see what happens. The two subgraphs seem to alternate their highlight!

I feel like this isn't desired behavior. I am expecting my selections and their neighbors (1 degree in this case) to be highlighted, and to continue being highlighted as I add more selections via control-click.

```require(visNetwork)
require(shiny)

server <- function(input, output) {
  datass <- reactive({
    set.seed(2)
    nodes <- data.frame(id = 1:15, label = paste("Label", 1:15))
    
    edges <- data.frame(id = 1:15, from = trunc(runif(15)*(15-1))+1,
                        to = trunc(runif(15)*(15-1))+1)
    list(nodes = nodes, edges = edges)
  })
  
  output$network_proxy_select <- renderVisNetwork({
    visNetwork(datass()$nodes, datass()$edges) %>% visLegend() %>%
      visInteraction(multiselect = TRUE) %>%
      visOptions(highlightNearest = list(enabled = TRUE, algorithm = "hierarchical"))
  })

}

ui <- fluidPage(
  mainPanel(visNetworkOutput("network_proxy_select"))
)

shinyApp(ui = ui, server = server)
```

**Session Info**

```R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.0      visNetwork_1.0.3

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.8 R6_2.2.0        magrittr_1.5    htmltools_0.3.5 tools_3.3.3     yaml_2.1.14     Rcpp_0.12.9     jsonlite_1.3   
 [9] digest_0.6.12   xtable_1.8-2    httpuv_1.3.3    mime_0.5   ```

**Comment by bthieurmel** [comment]
Not really a bug but a configuration not available yet. ``multiselect`` comes directly from ``vis.js``, ``visOptions`` is a ``visNetwork`` adding.

Have to update code and add support for this...!

**Comment by bthieurmel** [comment]
I think is't now fix....?

**Comment by jeffkeller87** [comment]
Is the `highlightNearest` `labelOnly` option something specific to `visNetwork`? I don't see anything about this in the vis.js documentation. I found it odd that it defaults to `TRUE` for showing node labels on `degree+1`.

Otherwise yes, this appears to be fixed.

**Comment by bthieurmel** [comment]
Hi, yes it's a custom functionnality developped in the R package.
