### ISSUE TITLE
visEvents() onlickEdge enables onclickNode

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#154]
I have created a visEvent and have specified its use onEdgeClick. A pop up is supposed to appear. The problem is that if I click the node, I will also get the same pop up. Is there a way to forcibly instruct the visEvent() to ignore the onNodeClick?

Thanks in advance.

**Comment by bthieurmel** [comment]
Not clear for me because don't see ``onEdgeClick`` and/or ``onNodeClick`` in vis.js event.

Can you send an example of code ?

**Comment by kagestrife** [comment]
ok, yeah, my bad, i meant

**Comment by kagestrife** [comment]
Sorry for the extra reply, I just want to point out another possible solution. Maybe change the "selectable" option in the visInteraction and make it able to make only the nodes or edges unselectable. In general, this is not a straightforward solution, but I am just pointing that out.

**Comment by bthieurmel** [comment]
Hi,

``selectEdge`` return an object with current ``nodes`` & ``edges`` selected (http://visjs.org/docs/network/#Events). So you can do something like that to control the event : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visEvents(selectEdge = "function(e) {
     // only for edge
    if(e.nodes.length === 0){
            alert('edge only')
    }
  }")
````
