### ISSUE TITLE
directional highlightnearest not directional

### ISSUE THREAD

**Issue by mfoos** [datastorm-open/visNetwork#155]
Hi there,

I have a directed network that I'd like to display in a Shiny app, and what I want is to click on a node, and highlight all of its children and none of its parents. (Incidentally, I'm using visGroups to preserve coloring as described in issue #74).

When I use `degree = list(to = 100, from = 0)` I get all downstream nodes as expected, but I also get LABELS ONLY on several degrees of parent node. The only way to turn the labels off is by removing the `from` parameter entirely (as below) but then I can only get 1 degree of `to`.  Do you have any suggestions? This is for production so I'd prefer not to use the dev version. Thanks!

`     visIgraph(inigraph) %>%
       visIgraphLayout(randomSeed = 123) %>%
       visInteraction(dragNodes = FALSE,
                      dragView = TRUE, 
                      zoomView = TRUE) %>%
       visOptions(highlightNearest = list(enabled = TRUE, algorithm = "hierarchical", 
                                          degree = list(to = 100),
                  hideColor = "#1F1F1F")) %>%
       visGroups(groupname = "1", size = 30,
                 color = list(background = "#0092CC",
                              border = "#244878",
                              highlight = list(background = "#99CA3C", border = "#99CA3C"),
                              hover = list(background = "#99CA3C", border = "#345F2B")),
                  font = list(size = 30, color = "gray", title = TRUE)) %>%
       visEdges(arrows = "to",
                color = list(color = "blue", highlight = "#99CA3C"),
                selectionWidth = 3)`

**Comment by bthieurmel** [comment]
Hi,

This is the default "algorithm"  : 

- hilighlight nodes in ``from`` & ``to`` parameters
- and just return labels of other in ``from+1`` & ``to+1``

I think about add a new argument to enabe/disable this. But without a new version, I thinl you can't fix that...

**Comment by mfoos** [comment]
Hi, thanks for your response! I respect your design decision, but I am also seeing labels on nodes further away than `from+1`, including nodes with no edges connecting them to the selected node.

**Comment by bthieurmel** [comment]
I'll have a look to this for next version, when I find time to also add new argument.

**Comment by bthieurmel** [comment]
Hi,

I 've find and fix some bug on hierarchical algorithm (bad interaction between ``from`` and ``to``), and add a new parameter ``labelOnly`` in ``visOptions`` to enable / disable label on ``degree + 1`` nodes.

You have to wait next CRAN version... (``1.0.5`` or ``1.1.0``) comming for summer. And if you have time, you can also test the dev version....!

Thanks for your feedback.

**Comment by mfoos** [comment]
That's great, thank you!
