### ISSUE TITLE
question: what the concept of  the "hubsize" and "directed" in visHierarchicalLayout(sortMethod)

### ISSUE THREAD

**Issue by lanshannin** [datastorm-open/visNetwork#156]
Hi 
 I  don't understand about `visHierarchicalLayout(sortMethod="hubsize")` and `visHierarchicalLayout(sortMethod="directed")`'s mean. There are four picture below. The first three figures use `sortMethod="hubsize"`, the other  figure use `sortMethod="directed"`.
In the first three figures I don't understand why id1 is at the top 2 layer,but id4 at the layer 4.

![e1](https://cloud.githubusercontent.com/assets/23090839/25048312/6722da64-216e-11e7-8316-c8a03cb6c8f5.png)
![e2](https://cloud.githubusercontent.com/assets/23090839/25048313/6aa69edc-216e-11e7-8ec0-d00e1d5d6669.PNG)
![e3](https://cloud.githubusercontent.com/assets/23090839/25048655/1535e3ca-2170-11e7-96ce-321f3b6b06bf.PNG)
The fourth figure  I don't understand why id9 at layer 2, not in the bottem.  
![e4](https://cloud.githubusercontent.com/assets/23090839/25048996/08e6cd80-2172-11e7-9967-0ce2b5f7f5a7.PNG)
 
I hope you can reply, thank you.

**Comment by bthieurmel** [comment]
Hi,

This is a question for ``vis.js``, not for ``visNetwork``...! In documentation, we can read : 

````
The algorithm used to ascertain the levels of the nodes based on the data. The possible options are: hubsize, directed. 

Hubsize takes the nodes with the most edges and puts them at the top. From that the rest of the hierarchy is evaluated. 

Directed adheres to the to and from data of the edges. A --> B so B is a level lower than A.
````

http://visjs.org/docs/network/layout.html

**Comment by lanshannin** [comment]
I will think about it after you advise. Thank you for your reply.
