### ISSUE TITLE
Bug? visHierarchicalLayout() only works if there are no double edges

### ISSUE THREAD

**Issue by adamsasiadek** [datastorm-open/visNetwork#157]
When trying to build this network I also have to specify the labels for the edges. Otherwise I get no output. 
 ```
nodes <- data.frame(id = 1:3, level = c(2,1,2), label = 1:3)
    edges <- 
      data.frame(from = c(1,2,1,1),
                 to = c(2,3,3,3),
                 label = 1:4,
                 arrows = rep("to",4),
                 level = 1:4,
                 smooth = rep(FALSE,4)
                 )

    visNetwork(nodes, edges, width = "100%") %>% visHierarchicalLayout()
```
Obviously it is pointless to build the graph because the arrows overlap, but it is still confusing.

**Comment by bthieurmel** [comment]
HI,

Yes, perhaps a bug, but linked to ``vis.js`` library. Can't do anything for that using ``visNetwork``....
