### ISSUE TITLE
widthConstraint for nodes

### ISSUE THREAD

**Issue by Rasica** [datastorm-open/visNetwork#158]
The labels on the nodes need to be split up if that's not the case the nodes get wider. Below is an example of it in visjs 
[http://visjs.org/examples/network/labels/multilineText.html](http://visjs.org/examples/network/labels/multilineText.html)

There is widthConstraint for edges in VisNetwork, is it also available for nodes? 

Thank you

**Comment by bthieurmel** [comment]
Hi,

yes, but I forget to add the argument in R... Coming in the next version !

**Comment by Rasica** [comment]
Thank you for your response !

**Comment by bthieurmel** [comment]
Done on github. So coming soon on CRAN
