### ISSUE TITLE
Highlighting neighbour nodes 

### ISSUE THREAD

**Issue by mmorine** [datastorm-open/visNetwork#160]
When using visOptions(highlightNearest =TRUE) I find that when selecting node X, all of node X's neighbours plus all of the neighbours' edges are highlighted - i.e., regardless of whether the neighbours' edges are connected to node X. Is it possible to only highlight node X, its first degree neighbours and the edges between them?
Thanks!

**Comment by bthieurmel** [comment]
Hi,
Yes, with the dev version on github (coming soon on CRAN), you can use : 

- ``degree`` to control depth
- ``labelOnly`` to add label of degree + 1

**Comment by mmorine** [comment]
That helps, thanks! Also defining separate color and highlight color in visEdges helps create more distinction.
