### ISSUE TITLE
Merge nodes into cluster dinamically

### ISSUE THREAD

**Issue by lordbitin** [datastorm-open/visNetwork#165]
HI!

I am looking forward to create a graph where each node belongs to a cluster. I would like to expand/merge the nodes of a cluster when clicking the cluster or something like that. I know that this library offers capability to cluster the nodes using different criterion (group, hubsize..) but I do not know if there is an option to merge all the nodes of a cluster nto a "supernode" that represents the whole cluster.

Thanks in advance!
Víctor

**Comment by Dmirijs-Ozernovs** [comment]
If I understood your question correct, than the thing you're asking for is described in [http://datastorm-open.github.io/visNetwork/more.html](url) "Clustering" section.

**Comment by bthieurmel** [comment]
Hi,

you can perhaps find some element in this discussion : 

https://github.com/datastorm-open/visNetwork/issues/83

And I'll add clustering ``vis.js`` method soon to use with proxy.

**Comment by lordbitin** [comment]
Thanks for all your responses! Finally I fixed my troubles here by changing my perspective about the problem in order to make the graph more clear :)
