### ISSUE TITLE
Question: Is it possible to connect nodes to the links?

### ISSUE THREAD

**Issue by consciousAI** [datastorm-open/visNetwork#167]
Hi Everyone, 

Is it possible to connect the nodes to links in visNetwork? This would be very much useful to represent moderator relationships in SEM models.

Something similar to the below:
![image](https://cloud.githubusercontent.com/assets/28952457/26450828/00503fd4-4162-11e7-97b2-42f6243d01ee.png)

This could be represented as:
a -> b
c -> a, b

if not already possible, it would be great if someone can add a feature to enable such relationships.

Many Thanks,
Shan.

**Comment by bthieurmel** [comment]
At moment not. For add this feature, it's better to ask to ``vis.js`` gtihub

https://github.com/almende/vis

**Comment by consciousAI** [comment]
Many thanks bthieurmel. I will post the query there.
