### ISSUE TITLE
How to increase the size of a node based on number of edges pointing to it?

### ISSUE THREAD

**Issue by JuASto** [datastorm-open/visNetwork#168]
![printgithubissue](https://cloud.githubusercontent.com/assets/28957119/26457996/72d80042-4148-11e7-8613-465033138026.JPG)

For example, I want the node circled appears bigger than the rest. Is it possible? 

Thank you

**Comment by Dmirijs-Ozernovs** [comment]
It is possible, but you have to do it in two steps:
1. Calculate the number of edges (called degree in graph theory) for every node.
2. Add the number of edges as "value" attribute for the nodes data frame.

Degree can be calculated using _igraph_ package. Transform nodes and edges into graph object, then calculate degree for every node, then add the result to nodes data frame. Example:

`library(visNetwork)
library(igraph)

nodes <- data.frame(id = 1:10)
edges <- data.frame(from = sample(1:10, 20, replace = T), to =sample(1:10, 20, replace = T))
graph <- graph.data.frame(edges)
degree_value <- degree(graph) 
nodes$value <- degree_value[match(nodes$id, names(degree_value))]
nodes$label <- paste("Degree is", nodes$value)

visNetwork(nodes, edges,)`
