### ISSUE TITLE
Q. visNetwork(nodes, edges) works in R shell, not R script

### ISSUE THREAD

**Issue by victoriastuart** [datastorm-open/visNetwork#170]
Hello: I can't seem to figure this out.

I have an RNeo4j R script ("demo.R"), the contents of which run fine in an R terminal / shell,

`R:> `

but not from a script,

`Rscript demo.R`

The script executes / completes without error.s

The last line of the code / script is

`visNetwork(nodes, edges)`

Suggestions?

**Comment by bthieurmel** [comment]
Hi, 

I think you can't retrieve / open a ``htmlwigets`` interative graphic like ``visNetwork`` running ``Rscript``.

If you want to save the network, you can do at the end  ``v <- visNetwork(nodes, edges); saveRDS(v, file = "path/to/v.RDS")`` for example and go back after and visualize with ``v <- readRDS(file = "path/to/v.RDS");v ``

**Comment by victoriastuart** [comment]
@bbthieurmel : Hi, thank you for your workaround:

```
# save network:
n <- visNetwork(nodes, edges); saveRDS(v, file = "v.RDS")
# visualize network:
v <- readRDS(file = "v.RDS"); v
```

Again, that code only works if it is run in an R shell ( R:> ), not from an R script ("demo.R," launched various ways: Rscript; r [littler]; ./demo.R; ...).

I already figured out that one needs to run a script that calls ```visNetwork(nodes, edges)``` in the R shell/terminal.  I think that my solution / workaround is slightly more 'facile:'

```R:> source("demo.R"); visNetwork(nodes, edges)```

It simply sources (runs) the script, then within the same R session (to access the network data), calls / visualizes the network.

So, either method works.  Thank you for your response/suggestion, however; much appreciated!  :-)
