### ISSUE TITLE
visNetwork causes RStudio to hang.

### ISSUE THREAD

**Issue by yash555** [datastorm-open/visNetwork#172]
Hi,

I am using visNetwork to generate an interactive graph, which has about 400 nodes and 7000 edges. When I try to run this as a Shiny app or on RStudio, the browser and IDE freezes and nothing happens. It would be of great help if someone could help me out with this as I find this package really useful for my project.

**Comment by bthieurmel** [comment]
Hi,
You can have a look to some tips for large network and performance : 

http://datastorm-open.github.io/visNetwork/performance.html

Particulary use ``visIgraphLayout`` to pre-compute position and disable physics

**Comment by wlandau-lilly** [comment]
@bthieurmel Thank you! Just dodged a bullet on that one.
