### ISSUE TITLE
bug? setting edge to hidden causes reset when dragging node?

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#173]
Hi - the below causes a reset when hidden=c(TRUE,FALSE) is set and node 3 is dragged, and the edge hovered over? If hidden is unset it will not reset. I was expecting no difference in behavior hidden or not.

```
library(magrittr)
library(visNetwork)

nodes <- data.frame(id = 1:3, label = paste("node", 1:3))
edges <- data.frame(from = c(1,2), to = c(1,3), label = "Edge label", hidden=c(TRUE,FALSE),
 font.size = 14)

visNetwork(nodes, edges) %>%
  visInteraction(hover = T) %>%
  visEvents(hoverEdge = "function(e){
 this.body.data.edges.update({id: e.edge, font: {size : 14}});}") %>%
  visEvents(blurEdge = "function(e){
 this.body.data.edges.update({id: e.edge, font: {size : 0}});}" )%>%
  visHierarchicalLayout(
    levelSeparation = 160,
    nodeSpacing = 10,
    sortMethod = "directed",
    blockShifting = TRUE,
    edgeMinimization = TRUE
  )

```
@bthieurmel is this an issue with visNetwork or visjs? Please close this if you think this is visjs and I'll try to come up a JavaScript example instead.

(by the way, this library is the best network library out there, by leaps and bounds!!!)

**Comment by bthieurmel** [comment]
Hi,

I think it's not due to ``visNetwork``. Can you make a jsFiddle example to see if we observe the same thing on javascript ? And so, post a issue to ``vis.js`` or go back to me ?

Thanks

**Comment by dockstreet** [comment]
Hi,

I was able to reproduce the issue in a jsFiddle example:
http://jsfiddle.net/dockstreet/mxzjf7j8/

Here is the visjs issue logged, feel free to chime in if I did not provide enough info or was unclear:
https://github.com/almende/vis/issues/3150
thanks again for your help!

**Comment by dockstreet** [comment]
Update on this, seems like API changes will need to be made to visjs to support this. refer to 
https://github.com/almende/vis/issues/3150

 Should we close this, based on it's not visNetwork? 

(I'm guessing if the API changes something may need to be added to visNetwork to support the changes. )

**Comment by dockstreet** [comment]
Update on this, seems like API changes will need to be made to visjs to support this. refer to
almende/vis#3150

I'm guessing if the API changes something may need to be added to visNetwork to support the changes. 

Perhaps we could get around this issue by capturing / saving the x/y values of the nodes and storing them in an data frame to be re-rendered? Not sure if that would be possible or not?

**Comment by bthieurmel** [comment]
Seems to be ok on current version
