### ISSUE TITLE
multiple selectedby - visOptions

### ISSUE THREAD

**Issue by naviInHyrule** [datastorm-open/visNetwork#174]
Hi,

I've built very nice network using the library, but I wonder if it is possible to have several selectedby boxes in the same graph. In my data, I have several characteristic like gender, location, work position and I'd like to have them together without using Rshiny. 

Thanks a lot!

**Comment by bthieurmel** [comment]
Hi,

Not possible at moment (perhaps one day....?). But you can try to play with ``multiple`` argument possibility : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE), 
                    sex = sample(c("H", "F"), 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)


# and with multiple groups ?
nodes$sel <- paste(nodes$group, nodes$sex, sep = ",")

visNetwork(nodes, edges) %>% 
  visOptions(selectedBy = list(variable = "sel", multiple = TRUE))
````
