### ISSUE TITLE
highlightNearest does not work correctly with more nodes

### ISSUE THREAD

**Issue by dagh** [datastorm-open/visNetwork#175]
Hi, I wasn't sure which place is the best to post questions or issues, so I first posted on stackoverflow, then I posted here. Let me know if one place is better than the other.

I am trying to generate a network map with some 200 - 500 nodes, and also use the highlightNearest option.
highlightNearest seems to stop working after some defined number of nodes and edges.
In the example below:
a. highlightNearest works great with 152 nodes
b. highlightNearest stop working with 153 nodes

I only use 4 edges in this simplified example. Normally, I would use more edges.
I need help so that I can have 200 - 500 nodes with highlightNearest working.
I just installed the latest visNetwork (v2.0.0) from github.
Let me know if you need additional details from me

Also, just so you know, this network library is great!
Thanks.

    #!/usr/bin/env Rscript 
    library(shiny)
    library(visNetwork)
    library(dplyr)

    ui <- shinyUI(fluidPage(visNetworkOutput("network_proxy_update", height = "500px")))

    server <- shinyServer(function(input, output) {
      output$network_proxy_update <- renderVisNetwork({
        # build nodes dataframe
        n.nodes <- 152 # highlightNearest works
        #n.nodes <- 153 # highlightNearest does not work
        nodes <- data.frame(id=1:n.nodes, labels=1:n.nodes, stringsAsFactors = F)

        # build edges dataframe
        n.edges <- 4
        edges <- data.frame(from=1:n.edges, to=2:(n.edges+1), id=1:n.edges, stringsAsFactors = F)
        visNetwork(nodes, edges) %>% visOptions(highlightNearest = T)
       })
    })

    # Run the application
    app <- shinyApp(ui = ui, server = server)
    runApp(app, port=8200, host='0.0.0.0')

**Comment by bthieurmel** [comment]
Thanks. Normally fix on 2.0.0 on github, coming in nexy days on CRAN.

(really a little bug, due to ``vis.js``....!)

**Comment by bthieurmel** [comment]
And ``github`` is the place to post issue & bug, and ``stackoverflow`` or other to post some question about.

So this is the right place !

**Comment by dagh** [comment]
Just installed and tested it out with 500 nodes and it seems to be working flawlessly.  Thanks for the fix and the incredibly quick turn around. They are all small bugs... :)

Also, thanks for the info about using Stackoverflow and github.
