### ISSUE TITLE
#question: is it possible to receive which nodes are click selected?

### ISSUE THREAD

**Issue by agk48** [datastorm-open/visNetwork#176]
Hi,

I'm new to both visNetwork and Shiny, so sorry if this is a simple question.  I'm trying to build an app that creates a network from files the user inputs and allows the user to select multiple nodes and then create a new network by clicking a button.  I've accomplished this using a selectInput widget and visUpdateNodes.  However, I would like to be able to create new networks with nodes the user has selected by click rather than by a selection bar.  Is there any way for me to get the ids of nodes that have been click selected, or a better way for me to do this?

Thanks!

**Comment by bthieurmel** [comment]
Hi,

if you are in shiny, you can use ``visGetSelectedNodes`` with ``visNetworkProxy``. This is a simple example : 

````
library(shiny)
library(visNetwork)

ui <- fluidPage(
  visNetworkOutput("network"),
  actionButton("gosel", "Get selected nodes!")
)
server <- function(input, output, session) {
  
  output$network <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    visNetwork(nodes, edges) %>% visInteraction(multiselect = T)
  })

  observe({
    input$gosel
    visNetworkProxy("network") %>% visGetSelectedNodes()
  })
  
  observe({
    print(input$network_selectedNodes)
  })
  
}

shinyApp(ui = ui, server = server)
````

**Comment by dmenne** [comment]
It would be really nice if this example could be put into the documentation, which is very obscure, pointing to examples that do not show how this works.
