### ISSUE TITLE
height=100% is percentage of canvas, not of window

### ISSUE THREAD

**Issue by nacnudus** [datastorm-open/visNetwork#178]
When setting `width = "100%"` the network is visible across the full width of the window, but with `height = "100%"` it is very short -- about an inch high on my screen.

This seems to be because it is a percentage of the canvas height, not the window height.  Is it possible to make the canvas the full height of the window?

**Comment by bthieurmel** [comment]
Hi,

Perhaps you can try this : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3)) 

visNetwork(nodes, edges, width = "100%", height = "100vh")
````
