### ISSUE TITLE
Diamond Layout?

### ISSUE THREAD

**Issue by gfleetwood** [datastorm-open/visNetwork#179]
Hi, 

I'm trying to implement a graph layout in a diamond-esque shape with two specific nodes at either end. Is this possible to do with visNetwork?

**Comment by wlandau-lilly** [comment]
Maybe the `level` column of the `nodes` data frame would help. Are you looking for something like this?

```r
library(magrittr)
library(visNetwork)

nodes = data.frame(
  id = 1:4, label = 1:4,
  level = c(1, 2, 2, 3))

edges = expand.grid(from = 1:4, to = 1:4)
edges = edges[-c(1, 6, 11, 16),]

visNetwork(nodes = nodes, edges = edges) %>%
  visHierarchicalLayout
```

![issue](https://user-images.githubusercontent.com/22958003/28329561-45bf9472-6bb8-11e7-936e-7a564c26e9c7.png)

**Comment by gfleetwood** [comment]
This is perfect. Thanks!
