### ISSUE TITLE
Margins around plot window

### ISSUE THREAD

**Issue by fabioc-ms** [datastorm-open/visNetwork#183]
Is there a way to disable the border around the plot window, so I can maximize the visibility of large networks?

Thanks,

Fabio

**Comment by bthieurmel** [comment]
Hi,

I'm sorry but I don't really understand this point...! Some print / example / detail ?

**Comment by bschilder** [comment]
think this is what you were talking about, if I'm not mistaken @fabioc-ms 
https://github.com/datastorm-open/visNetwork/issues/407
