### ISSUE TITLE
Large graphs do not fit to window by default

### ISSUE THREAD

**Issue by wlandau** [datastorm-open/visNetwork#185]
The final graph in [this blog post](http://will-landau.com/2017/07/25/Fun-with-network-graphs/) is zoomed in very far by default. Is there a way to automatically make the graph fit inside the plotting area?

**Comment by bthieurmel** [comment]
Hi,

Perhaps some element  #46 and #126 ?

**Comment by wlandau** [comment]
I tried `visEvents(type = "once", startStabilizing = "function() { this.fit({nodes:[1,5,10]})}")`, which mostly appears to work, but has unpredictable performance in `revealjs` presentations (see ). (By the way, what does `:[1,5,10]` mean?) I have better luck with `visEvents(type = "once", startStabilizing = "function() { this.moveTo({scale:0.1})}")`, but that requires me to manually pick a scaling factor.

**Comment by bthieurmel** [comment]
``this.fit`` can be use to fit the zoom to some nodes, for example 1, 5, and 10 (``:[1,5,10]``), or to all nodes with : 

``visEvents(type = "once", startStabilizing = "function() { this.fit()}")``
