### ISSUE TITLE
Color inherit = both stopped working for for edges

### ISSUE THREAD

**Issue by sebsfox** [datastorm-open/visNetwork#187]
My example edges and nodes are attached. 
[nodes.and.edges.xlsx](https://github.com/datastorm-open/visNetwork/files/1193479/nodes.and.edges.xlsx)

My network is created as follows:
```
nodes <- read.csv("nodes.csv")
edges <- read.csv("edges.csv")

library(gtools)
library(dplyr)
library(visNetwork)
profileCol <- "orange"
indicatorCol <- "dodgerblue"

indicatorSelection <- sort(nodes$id[nodes$type=="Indicator"])

net <- visNetwork(nodes, edges,
                  main = "Shared indicators within PHOLIO profiles",
                  width = "100%", height = "800px")  %>%
        visPhysics(enabled = FALSE) %>%
        visLegend(addNodes = list(
                list(label = "Profile", shape = "circle", color = profileCol),
                list(label = "Indicator", shape = "circle", color = indicatorCol)),
                addEdges = data.frame(color = c(profileCol,indicatorCol),
                                      label = c("Indicator received\nby profile",
                                                "Indicator provided\nby profile"),
                                      arrows =c("from", "to")),
                useGroups = FALSE
        )   %>%
        visNodes(group = "Profile.name") %>%
        visIgraphLayout(layout = "layout_in_circle") %>%
        visOptions(highlightNearest = list(enabled =TRUE,
                                           degree = 0),
                   selectedBy = list(variable = "Profile.name",
                                     values = mixedsort(levels(nodes$Profile.name)),
                                     style = 'width: 300px; height: 26px'),
                   nodesIdSelection = list(enabled = TRUE,
                                           values = indicatorSelection))

net
```

In version 1.0.3, the variable `color.inherit = "both"` in the edges data frame would tell the edges to be coloured based on the "from" and "to" node colours. Now it only seems to be picking up the "to" nodes colour.
Have I missed something?

Thanks for your help.

**Comment by bthieurmel** [comment]
Seems to work for me with latest version ``2.0.0`` or ``2.0.1`` : 

````
# minimal example
nodes <- data.frame(id = 1:3, color = c("red", "blue", "yellow"))
edges <- data.frame(from = c(1,2), to = c(1,3), color.inherit = "both")

visNetwork(nodes, edges)
````

And on your example : 

![image](https://user-images.githubusercontent.com/8750326/28875453-e8ede304-7795-11e7-8f8d-c902fd642f02.png)

**Comment by sebsfox** [comment]
Sorry - I forgot the main detail - thanks for not closing this. 
When _selecting_ an orange node, the attached edges have no colour, but when _selecting_ a blue node, the attached edges do have colour.

**Comment by bthieurmel** [comment]
This is the ``highlightNearest`` algorithm : 

- he keep color of nodes less or equal ``degree`` argument
- the edge keep color of the nodes colored

**Comment by sebsfox** [comment]
Thanks again for responding. Can I just double check my understanding? When the edge colour is `color.inherit = "both"` - the edge will only keep the colour of the "from" node when that is selected, but when the "to" node is selected, the edge won't keep the colour? Is this the intention because this is different from version 1.0.3. If so, I need to change my visualisation.

Thanks again for looking at this.
