### ISSUE TITLE
Show all alters on hover? 

### ISSUE THREAD

**Issue by vardavas** [datastorm-open/visNetwork#190]
Following on from "question : possible to hide edge text initially and display on hover? #128" - I can show display the node id on hover using title or by the following example code 

nodes <- data.frame(id = 1:3,label = "N label", font.size = 0)
edges <- data.frame(from = c(1,2), to = c(1,3), label = "Edge label", font.size = 0)
visNetwork(nodes, edges) %>%
  visInteraction(hover = T) %>%
  visEvents(hoverNode = "function(n){
            this.body.data.nodes.update({id: n.node, font: {size : 14}});
            }") %>%
  visEvents(blurNode = "function(n){
            this.body.data.nodes.update({id: n.node, font: {size : 0}});
  }")

However I'd like to display the node's id on hover as well as the ids of all the first degree contacts. 
What is the best way to do it? - My graph is quite busy with about 600 nodes and a mean degree of about 10. 

Thanks!

**Comment by bthieurmel** [comment]
Yes, using also ``getConnectedNodes`` (doc here http://visjs.org/docs/network/ or using ``visDocumentation``)


````
nodes <- data.frame(id = 1:3,label = "N label", font.size = 0)
edges <- data.frame(from = c(1,2), to = c(1,3), label = "Edge label", font.size = 0)
visNetwork(nodes, edges) %>%
  visInteraction(hover = T) %>%
  visEvents(hoverNode = "function(n){
            this.body.data.nodes.update({id: n.node, font: {size : 14}});
            connected_nodes = this.getConnectedNodes([n.node])
            if(connected_nodes.length > 0){
              for (var i = 0; i < connected_nodes.length; i++) {
                this.body.data.nodes.update({id: connected_nodes[i], font: {size : 14}});
              }
            }
            }") %>%
visEvents(blurNode = "function(n){
          this.body.data.nodes.update({id: n.node, font: {size : 0}});
          connected_nodes = this.getConnectedNodes([n.node])
          if(connected_nodes.length > 0){
            for (var i = 0; i < connected_nodes.length; i++) {
            this.body.data.nodes.update({id: connected_nodes[i], font: {size : 0}});
            }
          }
}")
````
