### ISSUE TITLE
add title to a visNetwork graph creating with DiagrammeR

### ISSUE THREAD

**Issue by RB000** [datastorm-open/visNetwork#191]
hello i create a visNetwork graph based on a graph created with DiagrammeR but i can't know add a title to my graph or even change it!
please is there any way to set the title of visNetwork graph not using shiny

**Comment by TitouanRobert** [comment]
Hello,
You can use main argument  : 

`
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(2,3))
visNetwork(nodes, edges, main = "Title")
`

**Comment by RB000** [comment]
the probleme is that i create my plot using diagrammer

```
ndf <-
  create_node_df(
    n = 4,
    label = TRUE,
    type = c("type_1", "type_1",
             "type_5", "type_2"),
    shape = c("circle", "circle",
              "rectangle", "rectangle"),
    values = c(3.5, 2.6, 9.4, 2.7))
edf <-
  create_edge_df(
    from = c(1, 2, 3),
    to = c(4, 3, 1),
    rel = "leading_to",
    values = c(7.3, 2.6, 8.3))
graph <-
  create_graph(
    nodes_df = ndf,
    edges_df = edf)
render_graph(graph,output="visNetwork",width='100%')
```

**Comment by TitouanRobert** [comment]
The probleme from diagrammer library, you can temporary do like it  :

```
DD <- render_graph(graph,output="visNetwork",width='100%')
DD$x$main$text <- "Title"
DD$x$main$style <- "font-family:Georgia, Times New Roman, Times, serif;font-weight:bold;font-size:20px;text-align:center;"
DD
```

But the best solution is to ask this question to maintener of DiagrammeR.

**Comment by RB000** [comment]
thank you ! this works well
