### ISSUE TITLE
Add a zoom function to vislegend

### ISSUE THREAD

**Issue by gloopy** [datastorm-open/visNetwork#194]
Hello is it possible to add a zoom function to the legend ? I currently can not see the text in the legend box .
![image](https://user-images.githubusercontent.com/8674130/29324924-17230940-81a3-11e7-8c0d-9cd2d3288f98.png)

Many Thanks

**Comment by bthieurmel** [comment]
I think it's possible. Looking as soon as possible.

**Comment by bthieurmel** [comment]
Add on ``dev github`` version.

New argument ``zoom`` on ``visLegend`` with defaut value to ``TRUE``
