### ISSUE TITLE
add Edge endpoint "|" 

### ISSUE THREAD

**Issue by iXanthos** [datastorm-open/visNetwork#197]
Hello, I would like to ask if it is possible to add "|" as an endpoint in the `arrows.to.type` . It is important as it is used in the Causality and Association networks a lot and it is something I have seen many biologists use in their networks as well.

Thanks in advance,
Jordan

**Comment by bthieurmel** [comment]
as in #73 , just can say :  you have to ask this enhancement on `vis.js` github (https://github.com/almende/vis).

**Comment by gadepallivs** [comment]
I have requested a different edge types feature on visnetwork main github [here](https://github.com/visjs/vis-network/issues/153). Will this feature be available with R visnetwork library right away or do I need to wait for library updates ?
