### ISSUE TITLE
Create network with both directed and undirected edges

### ISSUE THREAD

**Issue by iXanthos** [datastorm-open/visNetwork#198]
I want to create a network that has these kinds of edges o-o, <-o, <-, o-, <-> , -.
What I've tried so far, is to create 2 logical vectors for the to and from arguments and 2 vectors containing the types of edges. and put them in the Edges dataframe like this

`arrows = list(to = list(enabled = as.logical(toBool),type = toBoard), from = list(enabled =as.logical(fromBool),type = fromBoard))`

The problem is that if I have FALSE values in the fromBool and toBool vectors, I get an error for differing number of rows. Is there a way to do this otherwise, even to drop the Bool vectors and somehow define a type of edge thats undirected (not arrow nor circle)?
Thanks in advance

**Comment by bthieurmel** [comment]
You have to use a specific notation using dot rather than list for pass complex argument in a data.frame : 

````
# minimal example
nodes <- data.frame(id = 1:3, label = 1:3)

toBool <- c(T, F, T)
toBoard <- c("arrow", "circle", "circle")

fromBool <- c(F, T, T)
fromBoard <- c("arrow", "circle", "arrow")

edges <- data.frame(from = c(1,2, 3), to = c(1,3, 1), 
                    arrows.to.enabled = toBool, 
                    arrows.to.type = toBoard, 
                    arrows.from.enabled = fromBool, 
                    arrows.from.type = fromBoard)

visNetwork(nodes, edges)

````

**Comment by iXanthos** [comment]
ok, I'll try it out and give you feedback, please leave this thread open for a few days. Thanks
