### ISSUE TITLE
request: add event hook that indicates a network has been initialized

### ISSUE THREAD

**Issue by FrissAnalytics** [datastorm-open/visNetwork#200]
Hi!

Is it possible to add an event hook that indicates that a network has been initialized so that it's clear that additional commands can be send via proxy calls? For instance, in shiny I would like to say

```r
observeEvent(input$network_initialized,{
   # do stuff e.g. send update via proxy to add background circles...
  visNetworkProxy("network") %>% customVisMethod(...)
})
```
In some scenarios it makes sense to add your own custom methods that do custom stuff on the client. In that case it is helpful to know the initial network has been initialized. 

Unfortunately vis.js doesn't have a proper event for this it seems. There are some events that  can be used, but they have some caveats that make using them a bit tricky. For instance, you don't want to rely on a `stabilized` or `initRedraw` event or something like that, even though you could use them to hack something together. 

Perhaps adding a simple `Shiny.onInputChange` statement after [this](https://github.com/datastorm-open/visNetwork/blob/master/inst/htmlwidgets/visNetwork.js#L2638) line in your code is sufficient i.e. after:

```javascript
instance.network = new vis.Network(document.getElementById("graph"+el.id), data, options);
```

**Comment by bthieurmel** [comment]
Done. So you can test...!?

**Comment by FrissAnalytics** [comment]
Great! Works like a charm! :-)
