### ISSUE TITLE
Change Background color of Network in Shiny

### ISSUE THREAD

**Issue by FinScience** [datastorm-open/visNetwork#203]
Hi,

Is there a way to change the background color of the visNetwork generated in shiny? Would be great if you could help me out.

**Comment by bthieurmel** [comment]
Now possible in ``github`` with new argument  ``background`` in ``visNetwork`` function.

**Comment by FinScience** [comment]
@bthieurmel - Thanks for the response. How to I get this to my library.
The following is not working

      devtools::install_github("datastorm-open/visNetwork")

**Comment by bthieurmel** [comment]
Don't really understand why you have problem with devtools....
You can download source code from github and install the  (unzip) repertory
