### ISSUE TITLE
Node colors using R hex color codes

### ISSUE THREAD

**Issue by jzicker** [datastorm-open/visNetwork#205]
the color argument in nodes only appears to work with named colors or integer colors.   Does it work for R hex representation of colors?

**Comment by bthieurmel** [comment]
See #150 : 

- a hexa notation like ``#FF0000``, but **on 7 char and without transparency** (so not #FF0000FF)

**Comment by jzicker** [comment]
thank you and apologise I didn't find the solution when I searched
