### ISSUE TITLE
`shapeProperties.borderDashes` doesn't work for nodes in legend

### ISSUE THREAD

**Issue by olivier7121** [datastorm-open/visNetwork#211]
Hi,

I tried to draw dashed borders on nodes in a legend but so far it didn't work:
`LegendNodes <- data.frame(label = c("label1","label2","label3"), shape = "dot", color = list(background = "white", border = c("dodgerblue", "black", "red")), borderWidth = 3, shapeProperties = list(borderDashes = list(8, 5)))`
--> the nodes in the legend disappear
`LegendNodes <- data.frame(label = c("label1","label2","label3"), shape = "dot", color = list(background = "white", border = c("dodgerblue", "black", "red")), borderWidth = 3, shapeProperties = list(borderDashes = TRUE))`
`LegendNodes <- data.frame(label = c("label1","label2","label3"), shape = "dot", color = list(background = "white", border = c("dodgerblue", "black", "red")), borderWidth = 3, shapeProperties = list(borderDashes = c(8, 5)))`
--> the nodes are displayed but with a solid border.

Would you have any clue?

Regards,

Olivier

**Comment by bthieurmel** [comment]
Hi,

You can't use ``data.frame`` with complex argument, and it's the case of ``borderDashes `` if you want to set parameters.

With a ``data.frame``, you can only set "simple" parameters (one value, not a vector or a list for one node). but you can use ``.`` notation like this for argument with sub-argument like ``color`` : 

````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

# data.frame, only "simple argument"
dtLegendNodes <- data.frame(label = c("label1", "labels2"),
                            shape = "dot",
                            color.background = "white", 
                            color.border = c("dodgerblue", "red"),
                            shapeProperties.borderDashes = TRUE)

visNetwork(nodes, edges) %>% 
  visLegend(useGroups = FALSE, addNodes = dtLegendNodes)
````

Else, you have to define all the dataset as a ``list`` : 
````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

# list : all arguments
listLegendNodes <- list(
  list(label = "label1", shape = "dot", 
       color = list(background = "white", border = "dodgerblue"),
       shapeProperties = list(borderDashes = list(8, 5))),
  list(label = "label2", shape = "dot", 
       color = list(background = "white", border = "red"),
       shapeProperties = list(borderDashes = list(2, 5)))
  )

visNetwork(nodes, edges) %>% 
  visLegend(useGroups = FALSE, addNodes = listLegendNodes)
````

**Comment by olivier7121** [comment]
OK, thank you.
