### ISSUE TITLE
add stroke to fontawesome icons

### ISSUE THREAD

**Issue by FrissAnalytics** [datastorm-open/visNetwork#213]
hi!

is it possible to use a stroke on FontAwesome based node icons in visNetwork (or vis.js)? 

In HTML this can be done via CSS see for instance [here](https://codepen.io/mackdoyle/pen/yrgEH) or [here](http://owumaro.github.io/text-stroke-generator/). The latter link provides a tool to generate an appropriate stroke via a text-shadow 'hack'.

I'm not sure how or if this even can be done in a canvas context? Note here we talk about a stoke on the icon, not on the node label (which is easy).

The reason for the request is that we use visNetwork with FontAwesome based node icons that are displayed on top of background circles which color is determined dynamically. In some cases the background and icon are close in color, which prevents the user from seeing the icon as it blends with the background. Adding a stroke would fix this.

kind regards, Herman

**Comment by bthieurmel** [comment]
Hi,

I'don't know if it's possible using ``vis.js``. ``icon`` are defined with ``face``, ``icon``, ``size`` and ``color``. I think it's not possible to pass more information, like a ``css class``....

**Comment by bthieurmel** [comment]
Perhaps you can use somethong like this : 

````
nodes <- data.frame(id = 1:3, label = "\uf0c0")
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visNodes(shape = "circle", borderWidth = 0, 
           color = "white", font = list(multi = TRUE, face = 'FontAwesome', ital = list(mod = ''), 
                       bold = list(mod = ''))) %>%
  visEdges(color = list(inherit = FALSE)) %>%
  addFontAwesome()
````
