### ISSUE TITLE
cannot add images to nodes from local directory

### ISSUE THREAD

**Issue by abhik1368** [datastorm-open/visNetwork#214]
I am trying to add an icon to the network from the local machine using the code below . But nothing shows up . Any recommendations and help in this case ?
![dna](https://user-images.githubusercontent.com/1129505/31563629-7f364e60-b025-11e7-9a3f-a3cfee3e5371.png)

path_to_images <- "C:\\Users\\abhik\\Pictures\\images_Vis\\"

nodes <- data.frame(id = 1:4, group = c("A", "B"),
                    shape = "star",
                    image = paste0(path_to_images,"doc", ".png"),
                    label = "I'm an image")

edges <- data.frame(from = c(2,4,3,3), to = c(1,2,4,2))

visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shapeProperties = list(useBorderWithImage = TRUE)) %>%
  visLayout(randomSeed = 2) %>% visOptions(highlightNearest = T, selectedBy = "group")

Thanks 
Abhik

**Comment by FrissAnalytics** [comment]
in case you want to put images in a shiny app, in this case in your network graph, you either have to put them in a `www` folder, inside the shiny app, or use [addResourcePath](https://shiny.rstudio.com/reference/shiny/latest/addResourcePath.html).

**Comment by abhik1368** [comment]
Yes thanks i was looking at the old answers www folder one worked and keeping the images on github and then accessing it works for me.
