### ISSUE TITLE
 font.strokeWidth renders strange results

### ISSUE THREAD

**Issue by skanskan** [datastorm-open/visNetwork#215]
![s3svu9r](https://user-images.githubusercontent.com/4120283/31586384-713313e6-b1d0-11e7-8644-519d9e3c72ab.png)

As you can see near the 6% or the 26% it's not "clean".

**Comment by bthieurmel** [comment]
Hi,

``strokeWidth`` is a ``vis.js`` parameter, so I can't do anything directly in ``visNetwork``. If you want, you can write issue on : 

https://github.com/almende/vis

And, perhaps you can use ``background`` rather than ``strokeWidth`` ? 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3),  label = "6%")

visNetwork(nodes, edges) %>% 
  visEdges(arrows = 'from', font = list(background = "white"))

visNetwork(nodes, edges) %>% 
  visEdges(arrows = 'from', font = list(strokeWidth = 8))
````

**Comment by skanskan** [comment]
Last time I wrote there they told me I should develop it myself.

Regards
