### ISSUE TITLE
`vadjust` undocumented

### ISSUE THREAD

**Issue by davidaknowles** [datastorm-open/visNetwork#219]
`vadjust` is mentioned as an option under `font` in `visEdges` and `visNodes` with a reference to `visDocumentation` for further info, which doesn't seem to be there. I don't see `vadjust` in the source either - is this not implemented yet? (I'd like to have the node label at the same height as the node rather than below it)

**Comment by bthieurmel** [comment]
Hi,

It's implemented, and you have some information in ``visDocumentation`` (In **Modules** -> Nodes -> font).

````
nodes <- data.frame(id = 1:3, label = "Label")
edges <- data.frame(from = c(1,2), to = c(1,3))

# default
visNetwork(nodes, edges) %>% 
  visNodes(font = list(vadjust = 0))

# positive : down
visNetwork(nodes, edges) %>% 
  visNodes(font = list(vadjust = 20))

# negative : up
visNetwork(nodes, edges) %>% 
  visNodes(font = list(vadjust = -20))
````
