### ISSUE TITLE
Bug - visNetworkProxy & shiny - Changing edges' (only, not nodes') colors doesn't work

### ISSUE THREAD

**Issue by olivier7121** [datastorm-open/visNetwork#220]
Dear All,

Many thanks to the author of the R wrapper as well, of course, to the author of the underlying js library, vis.

I modified the code from this datastorm page: https://datastorm-open.github.io/visNetwork/shiny.html
in order to modify only the color of the edges (the original code modifies the nodes' colors only, but actually, it modifies both the nodes' and edges' colors):

`require(shiny)
require(visNetwork)

server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges)
  })
  
  
  observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
  
  observe({
    visNetworkProxy("network_proxy_nodes") %>%
		visEdges(color = input$color)

  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("color", "Color :",
                    c("blue", "red", "green")),
      selectInput("Focus", "Focus on node :",
                    c(1:3))
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
`
First, do you know where the issue comes from? The R wrapper or the underlying js library?

I thank you in advance for you help.

Best regards,

Olivier

**Comment by bthieurmel** [comment]
Hi,

First, the original demo code modifies both edges and nodes color because, by default, edges inherits of nodes colors.

It seems there is some bug updating edges using ``visEdges`` (work for label for example, but not for colors....). You can fix that setting id to your edges and so use ``visUpdateEdges`` : 

````
require(shiny)
require(visNetwork)

server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(id = 1:2, from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>% visNodes(color = "blue")
  })
  
  
  observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
  
  observe({
    newEdges <- data.frame(id = 1:2, color = input$color)
    visNetworkProxy("network_proxy_nodes") %>%
      visUpdateEdges(newEdges)
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("color", "Color :",
                  c("blue", "red", "green")),
      selectInput("Focus", "Focus on node :",
                  c(1:3))
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
````

**Comment by olivier7121** [comment]
Hi Benoît,

Many thanks for your very quick reply.

I didn't know this inheritance.

Actually I don't use solid (with a uniform color) nodes but rather nodes filled-in with a picture.

Many thanks for the work-around solution. I will try it.

Best regards,

Olivier

**Comment by olivier7121** [comment]
Hi Benoît,

I just tried this code (with image in each node)

`observe({
		newLinks <- data.frame(id = 1:dim(Links)[1], color = rep("blue", dim(Links)[1]))
		visNetworkProxy("NetworkProxy") %>%
		visUpdateEdges(newLinks)
	})`

Nothing changed (I first tried without rep, same outcome).

**Comment by bthieurmel** [comment]
Do you first set id on edges ? If not, ``vis.js`` set defaut random id. (and so not equal to 1:n)

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(id = 1:2, from = c(1,2), to = c(1,3))
visNetwork(nodes, edges)
````

**Comment by bthieurmel** [comment]
And in your shiny code, the ``observe``  seemes to observe nothing (no input, no reactive values), and I think it will be not be execute !

**Comment by olivier7121** [comment]
No, I didn't set id on edges. Will do, I'll keep you posted.

Yes, I modified my code for the example to be runnable by the others. In my original code there is a reactive value.

**Comment by olivier7121** [comment]
OK, I added an extra id column to the Links dataframe (I suppose this column should be the #1? In any case, I moved it as the first column) but it still doesn't work.

Below is my server code:

`server <- function(input, output)
{
	ColorsTemp <- reactive({
		Links$color[which(Links$Transaction.Type %!in% input$Transaction.Type)] <- "white"
		Links$color
	})

	output$NetworkProxy <- renderVisNetwork(NetworkProxy)
	output$txt <- renderText(ColorsTemp())

	observe({
		newLinks <- data.frame(id = 1:dim(Links)[1], color = ColorsTemp())
		visNetworkProxy("NetworkProxy") %>%
		visUpdateEdges(newLinks, legend = TRUE)
	})
}`

output$txt is for debugging purposes.

**Comment by olivier7121** [comment]
Actually, I don't think that the id has to be in the first column.

**Comment by bthieurmel** [comment]
1 : Is my example in my first message work fine for you ?
2 : can you send me a full example ?

**Comment by bthieurmel** [comment]
``id`` column can be when you want, but with the name ``id``...!

**Comment by olivier7121** [comment]
Answers:
1: yes, your code in your first reply worked fine, thank you. But in my actual code, I don't use solid-colored nodes but rather nodes with an image.
2: I'm really sorry about that: it is confidential, it's for my work...

**Comment by olivier7121** [comment]
I could send you modified data if you want?

**Comment by olivier7121** [comment]
`id` column can be where you want, but with the name id...!

Thanks for confirming.

**Comment by bthieurmel** [comment]
Ok, so can you adapt this to your case ?

````
require(shiny)
require(visNetwork)

server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    # minimal example
    path_to_images <- "https://raw.githubusercontent.com/datastorm-open/datastorm-open.github.io/master/visNetwork/data/img/indonesia/"
    
    nodes <- data.frame(id = 1:3, 
                        shape = c("image", "circularImage", "image"),
                        image = paste0(path_to_images, 1:3, ".png"),
                        label = "I'm an image")
    
    edges <- data.frame(id = 1:2, from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>% visNodes(color = "blue")
  })
  
  
  observe({
    newEdges <- data.frame(id = 1:2, color = input$color)
    visNetworkProxy("network_proxy_nodes") %>%
      visUpdateEdges(newEdges)
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("color", "Color :",
                  c("blue", "red", "green"))
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
````

**Comment by olivier7121** [comment]
Thank you, your code works fine.

I just noticed that the rounded image has a blue outline and this color doesn't change.

I simply mention that because I also make draw a coloured outline to each circular image of my network.

**Comment by olivier7121** [comment]
It's very fine if the outline's color doesn't change (stays at its initial color).

**Comment by olivier7121** [comment]
Well, to be fair, I don't see how I could adapt my own code I sent you...

**Comment by bthieurmel** [comment]
You can try to make this simple example bug, or try to find a solution to your case...! Can't do more for you actually... Do you have R error ? Some message in web console ?

**Comment by olivier7121** [comment]
Of course, thanks a lot already!

I don't have any R error. Regarding the web console, I don't know where to find it (I opened something with a debugger tab - I use Firefox). I didn't see any "obvious" error. Anyway I'm not an IT expert...
I modified a bit the server code, but still unsuccessful.

`server <- function(input, output)
{
	ColorsTemp <- reactive({
		Links$color[which(Links$Transaction.Type %!in% input$Transaction.Type)] <- "white"
		Links$color
	})

	output$NetworkProxy <- renderVisNetwork(NetworkProxy)
	output$txt <- renderText(ColorsTemp())

	observe({
		ColorsTemp()
		newLinks <- data.frame(id = 1:dim(Links)[1], color = "red")
		visNetworkProxy("NetworkProxy") %>%
		visUpdateEdges(newLinks, legend = TRUE)
	})
}`

Anyway, thank you very much for your time.

**Comment by olivier7121** [comment]
Hi there,

Now I tried another simpler and more natural solution by removing unselected edges.

Below is my code:

`ui <- fluidPage(
		sidebarLayout(
			checkboxGroupInput(inputId = "Transaction.Type", label = "Transactions to display:", choices = levels(factor(Links$Transaction.Type)), selected = levels(factor(Links$Transaction.Type))),
			visNetworkOutput(outputId = "NetworkProxy", width = "100%", height = "800px")
		),
		textOutput("txt")
)

server <- function(input, output)
{
	#ColorsTemp <- reactive({
	#	Links$color[which(Links$Transaction.Type %!in% input$Transaction.Type)] <- "white"
	#	Links$color
	#})

	output$NetworkProxy <- renderVisNetwork(NetworkProxy)
	output$txt <- renderText(input$Transaction.Type)

	observe({
		#ColorsTemp()
	  LinksToBeRemoved_id <- Links[which(Links$Transaction.Type != input$Transaction.Type), ]$id
		visNetworkProxy("NetworkProxy") %>%
		visRemoveEdges(id = LinksToBeRemoved_id, legend = TRUE) %>%
		visUpdateEdges(Links, legend = TRUE)
	})
}

shinyApp(ui = ui, server = server)`

But it still doesn't work, edges are not removed...

Any idea?

**Comment by olivier7121** [comment]
OK, I eventually managed...

`Transaction.Type.InitialList <- levels(factor(Links$Transaction.Type))

'%!in%' <- function(x,y)!('%in%'(x,y))

ui <- fluidPage(
		sidebarLayout(
		  checkboxGroupInput(inputId = "Transaction.Type", label = "Transactions to display:", choices = Transaction.Type.InitialList, selected = Transaction.Type.InitialList),
			visNetworkOutput(outputId = "NetworkProxy", width = "100%", height = "800px")
		),
		textOutput("txt")
)

server <- function(input, output)
{
	output$NetworkProxy <- renderVisNetwork(NetworkProxy)
	output$txt <- renderText(input$Transaction.Type)
	
	observe({
	  OldLinks_id <- Links[which(Links$Transaction.Type %!in% input$Transaction.Type),]$id
	  NewLinks <- Links[which(Links$Transaction.Type %in% input$Transaction.Type),]
		visNetworkProxy("NetworkProxy") %>%
		visRemoveEdges(OldLinks_id) %>%
		visUpdateEdges(NewLinks)
	})
}

shinyApp(ui = ui, server = server)`
