### ISSUE TITLE
visHclust : new features

### ISSUE THREAD

**Issue by bthieurmel** [datastorm-open/visNetwork#221]
TO DO : 

- Can set nodes size based on population, like in ``visTree`` (``nodesPopSize``, ``minNodeSize``, ``maxNodeSize``)
- Can call with 
   + ``data.frame``, computing distance and hclust (current version)
   + giving a ``dist matrix``, and optionnaly a ``data.frame`` (same dims) for graphics on tooltip
   + giving a ``hclust`` result (or ``cutree`` ?) and optionnaly a data.frame (same dims) for graphics on tooltip

Using S3 class with first object argument (object = data.frame, objetc = dist, object = hclust)

**Comment by TitouanRobert** [comment]
Done
