### ISSUE TITLE
Own text instead of "select by id"

### ISSUE THREAD

**Issue by TobiSonne** [datastorm-open/visNetwork#223]
Could you please add an option to output an individual text for nodesIdSelection in visOptions instead of "select by id"? Thank you very much!

**Comment by bthieurmel** [comment]
Yes, why not... coming soon for next version.

**Comment by bthieurmel** [comment]
Done on current dev version

**Comment by TobiSonne** [comment]
Thank you very much!

**Comment by Mtmmmmm** [comment]
> Done on current dev version

Hi bthieurmel,

I have the same question. I am wondering which statement in visOpions is for selecting nodes by text input (eg. manually inputted nodes labels) instead of select by id.

Thanks!

**Comment by yiqinfu** [comment]
> > Done on current dev version
> 
> Hi bthieurmel,
> 
> I have the same question. I am wondering which statement in visOpions is for selecting nodes by text input (eg. manually inputted nodes labels) instead of select by id.
> 
> Thanks!

`nodesIdSelection = list(enabled = TRUE, main = "Your Text Here")`
