### ISSUE TITLE
Ordering the first node and furthur nodes in the visNetwork in ascending order

### ISSUE THREAD

**Issue by ashminkaul** [datastorm-open/visNetwork#225]
Hi, the below script is created using the "visNetwork" package. My requirement here is that here I want to create a sequence "visNetwork" where the nodes are ordered as per numbers. However, carefully checking here, the first node is at a level below the second node and then the order of all numbers is fine. Please help me in assigning the postion of first node with value 1 at the top instead of 2 and then get a straight visNetwork. Thanks and please help.

      nodes <- data.frame(id = 1:7, label = 1:7)
      # Extract the id
      num <- nodes$id
      # Repeat the numbers
      num2 <- rep(num, each = 2)
      # Remove the first and last numbers
      num3 <- num2[c(-1, -length(num2))]
      #Create a data frame
      edges <- as.data.frame(matrix(num3, ncol = 2, byrow = TRUE))
      names(edges) <- c("from", "to")
      visNetwork(nodes, edges, width = "100%") %>% 
      visEdges(arrows = "to") %>% 
      visHierarchicalLayout()

**Comment by ashminkaul** [comment]
You need "visNetwork" package in R to do this.

**Comment by bthieurmel** [comment]
Hi,

You have to use ``level`` argument like this : 

````
nodes <- data.frame(id = 1:7, label = 1:7, level = 1:7)
````
