### ISSUE TITLE
Question - visNetwork vs NEO4J

### ISSUE THREAD

**Issue by olivier7121** [datastorm-open/visNetwork#226]
Hello everyone,

I wish you all an Happy New Year!

What do you think of NEO4J as a "competitor" of vis(Network) in terms of capabilities, shortcomings, ease of use, etc.?

Just for the context: out of curiosity I wanted to try it out (as they define themselves as "The #1 Platform for Connected Data"), so I clicked on the download link but I was then asked to fill in a mandatory form with my name, email address, etc. Therefore I stopped the experience here as it seems it is not fully free (the cost is at least your personal data).

**Comment by Dmirijs-Ozernovs** [comment]
Neo4j is a graph database. Visnetwork is a tool to visualize graphs. They have different purposes and you shouldn't compare them.
Neo4j has very basic visualization capabilities (as I found myself), so in this field you can benefit a lot by combining Neo4j database capabilities with Visnetwork visualization capabilities. But you can't replace Neo4j as a database with Visnetwork.

**Comment by olivier7121** [comment]
Very clear answer, thank you very much.

**Comment by FrissAnalytics** [comment]
FYI: if you really like to work with NEO4j data and have a 'better' visualization tool (than the standard neo4j viewer), perhaps check out:

https://github.com/eisman/neo4jd3
http://www.popotojs.com/

vis.js indeed is very nice and has a ton of features and has good bindings with R.

However, there are some things to be desired like animating a node into position, which [d3.js](https://d3js.org/) allows you to do quite [nicely](https://github.com/d3/d3-transition). That being said, most people will find d3.js not so easy and you definitely need javascript knowledge to leverage the potential of d3. 

Also, keep in mind that when the number of nodes in the network gets big, standard d3 rendering schemes using [SVG](https://www.dashingd3js.com/svg-basic-shapes-and-d3js) graphics will become too [slow](https://bocoup.com/blog/d3js-and-canvas). vis.js in fact uses [canvas](https://www.w3schools.com/html/html5_canvas.asp) as well, which can handle larger graphs better.
