### ISSUE TITLE
Edge lines crossing over nodes when using font awesome

### ISSUE THREAD

**Issue by royfrancis** [datastorm-open/visNetwork#228]
This question is in a way related to #213.  

The default plot.

```
nodes <- data.frame(id=c(1,2,3,4),group=c("A","A","A","A"),value=c(2,2,2,2))
edges <- data.frame(from=c(1,1,2),to=c(2,3,4),arrows=c("to","to","to"))
visNetwork(nodes,edges)
```

![3](https://user-images.githubusercontent.com/5083500/34919731-5ea2389e-f968-11e7-872b-91d8b5ead793.png)

The circles have strokes. The edges start and stop at the strokes of circles.

When using awesome fonts.

```
visNetwork(nodes,edges) %>%
  visGroups(groupname="A",shape="icon",icon=list(code="f016",size=30)) %>%
  addFontAwesome()
```

![2](https://user-images.githubusercontent.com/5083500/34919745-81b86b82-f968-11e7-9649-de7d6c13f847.png)

The icons are transparent and the edges connect to each other behind the icons. The arrows seem like they are not necessarily at the end of the edge lines.

Is there some way to specify that the edge lines must stop at arbitrary distance away from the node, rather than crossing over the node. I am imagining an argument like `offset=10` or something that determines how close the edge line can be to the node.  Below is the result that I have in mind. 

![4](https://user-images.githubusercontent.com/5083500/34919780-d63f0166-f968-11e7-870b-ed3caceb6b64.png)

**Comment by bthieurmel** [comment]
Hi,

We are restricted by ``vis.js`` and ``fontAwesome`` options, so you can't do what you want with transparent icon. You can just add this : 

````
 visEdges(arrowStrikethrough = FALSE)
````

**Comment by royfrancis** [comment]
Adding `visEdges(arrowStrikethrough = FALSE)` helps on the end of the edge. Doesn't do much at the start of the edge.

![screenshot 2018-02-19 10 40 44](https://user-images.githubusercontent.com/5083500/36371103-7003046e-1561-11e8-8383-6ab829074465.png)

**Comment by bthieurmel** [comment]
Yes, I know, but as I said, I can't do nothing....

**Comment by bthieurmel** [comment]
Perhaps you can use somethong like this : 

````
nodes <- data.frame(id = 1:3, label = "\uf0c0")
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visNodes(shape = "circle", borderWidth = 0, 
           color = "white", font = list(multi = TRUE, face = 'FontAwesome', ital = list(mod = ''), 
                       bold = list(mod = ''))) %>%
  visEdges(color = list(inherit = FALSE)) %>%
  addFontAwesome()
````
