### ISSUE TITLE
Dragging Multiple Nodes Simultanously 

### ISSUE THREAD

**Issue by EhsonGhandehari** [datastorm-open/visNetwork#232]
Hi. Thanks for the package, I love it.
I was wondering if it is possible to select multiple nodes (maybe mouse_brushing the screen for selection) and move all the selected nodes simultaneously. 

If Yes, can this help for nodes selected from different groups, or shall it be nodes from one specific group?

Thanks.

**Comment by bthieurmel** [comment]
Yes, you can select multiple nodes and move them using ``multiselect`` argument in ``visInteraction``, and  ``ctrl`` : 

````
visNetwork(nodes, edges) %>%
     visInteraction(multiselect = TRUE)
````

**Comment by EhsonGhandehari** [comment]
Awesome. Thanks for the help. It worked!

**Comment by alptaciroglu** [comment]
I wanted to know whether the functionality of selecting multiple nodes (with a rectangle select using mouse) is implemented or can be implemented. 

Thought this is the right issue, sorry if mistakenly reopened. Thanks
