### ISSUE TITLE
Uncollapse by node id not working?

### ISSUE THREAD

**Issue by flat-linex** [datastorm-open/visNetwork#234]
I am trying to collapse/uncollapse in Shiny by providing specific node ids: while I am able to collapse the nodes, I am unable to uncollapse them unless I uncollapse 'all' nodes by passing NULL as nodes specification. Am I missing something or is it a bug?

  ```R
require(shiny)
require(visNetwork)

server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges)
  })
  
  observeEvent(input$gohid, {
        visNetworkProxy("network_proxy_nodes") %>%
          visCollapse(nodes = c(1,2))
  })
  
  observeEvent(input$gounhid, {
        visNetworkProxy("network_proxy_nodes") %>%
          visUncollapse(nodes = c(1,2))
  })
  
  observeEvent(input$gounhidall, {
        visNetworkProxy("network_proxy_nodes") %>%
          visUncollapse(nodes = NULL)
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 2,
      actionButton("gohid",      "Collapse",       style = "width:100%;") ,
      actionButton("gounhid",    "Uncollapse",     style = "width:100%;") ,
      actionButton("gounhidall", "Uncollapse all", style = "width:100%;") 
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)

```

**Comment by bthieurmel** [comment]
Hi, yes it's a bug.... two solution : 

- with current ``visNetwork`` version, just use ``character`` for nodes id : 

````
  observeEvent(input$gounhid, {
    visNetworkProxy("network_proxy_nodes") %>%
      visUncollapse(nodes = c("1", "2"))
  })
````

- ore use the ``github`` version waiting for CRAN update (I've just adding a fix).

**Comment by flat-linex** [comment]
Thanks for the easy fix.
Would it be more correct on my side to always use node ids in character format when setting up the networks?

**Comment by bthieurmel** [comment]
Not really but It can prevent some bug (as you can see...!)

**Comment by flat-linex** [comment]
Ok :)
BTW, what's the id of the 'collapsed' node (to map it back to the nodes it represents so that I can uncollapse them ...)?

**Comment by bthieurmel** [comment]
It's a random id like 'cluster1989898'. I choose the simplest way passing real nodes id, and so collapsed clusters linked to...
