### ISSUE TITLE
Anomalies in collapsing/uncollapsing nodes?

### ISSUE THREAD

**Issue by flat-linex** [datastorm-open/visNetwork#235]
with a more complex setup than previously notified (the zip  file contains a complete shiny app, requiring some supporting libs ...).
The topology of the network is built from ods files in the folders data/cases/C_00... (files nodes.ods and relations.ods are used).

An example of the anomaly: 
- select node 20;
- click 'Collapsed view': only nodes 18,19,20 should be collapsed (as the debug print shows, they are the ids with which visCollapse is called) but more are actually collapsed;
- double clicking for uncollapsing 'partially' uncollapse the nodes (a subcluster remains) while clicking 'Uncollapsed view' correctly uncollapse everything.

[cluster.zip](https://github.com/datastorm-open/visNetwork/files/1727600/cluster.zip)

Sorry if this is not the appropriate way of documenting a possible bug ...

**Comment by bthieurmel** [comment]
Hi,

I think this is not a anomaly but due to the algorithm : just take all ``to`` nodes, and then all ``to`` nodes of child,... continue until the end. Better look on hierarchical network.

**Comment by flat-linex** [comment]
Do you mean using HierarchicalLayout?

**Comment by bthieurmel** [comment]
No, just say you can weel understand the algorithm looking a hierarchical example.
