### ISSUE TITLE
shiny.onInputChange and modules

### ISSUE THREAD

**Issue by johndrummond** [datastorm-open/visNetwork#241]
Hi,
I may be doing something stupid and I presume it's something to do with namespaces but I can't find anywhere how to get events to work in shiny when the visNetwork is in a module, like the shiny.onInputChange hover event
e.g.
the sample code below works fine, the text field being updated on the hover event
`library(visNetwork)
library(shiny)

server <- function(input, output) {
  output$network <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3, label = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>%
      visOptions(highlightNearest = TRUE,
                 nodesIdSelection = TRUE) %>% 
      visInteraction(hover = TRUE) %>%
      visEvents(hoverNode = "function(nodes) {
        Shiny.onInputChange('current_node_id', nodes);
      ;}")
  })
  
  output$shiny_return <- renderPrint({
    input$current_node_id
  })
}

ui <- fluidPage(
  visNetworkOutput("network"),
  verbatimTextOutput("shiny_return")
)

shinyApp(ui = ui, server = server)` 

But if I put it in a module the hover event shows on the graph but there's no update of the text output field.
`library(visNetwork)
library(shiny)

testModUI <- function(id) {
  ns <- NS(id)

  tagList(
  visNetworkOutput(ns("network")),
  verbatimTextOutput(ns("shiny_return"))
    )
   
}
testMod <- function(input, output,session){
  output$network <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3, label = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>%
      visOptions(highlightNearest = TRUE,
                 nodesIdSelection = TRUE) %>% 
      visInteraction(hover = TRUE) %>%
      visEvents(hoverNode = "function(nodes) {
        Shiny.onInputChange('current_node_id', nodes);
      ;}")
  })
  
  output$shiny_return <- renderPrint({
    input$current_node_id
  })  
}

server <- function(input, output) {
  callModule(testMod,"tMod")
}

ui <- fluidPage(
  testModUI("tMod"),

)

shinyApp(ui = ui, server = server)`

**Comment by bthieurmel** [comment]
You have to use ``ns`` function like this : 

````
testMod <- function(input, output,session){
  
  ns <- session$ns
  
  output$network <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 1:3, label = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    
    visNetwork(nodes, edges) %>%
      visOptions(highlightNearest = TRUE,
                 nodesIdSelection = TRUE) %>% 
      visInteraction(hover = TRUE) %>%
      visEvents(hoverNode = paste0("function(nodes) {
                Shiny.onInputChange('", ns("current_node_id"), "', nodes);
                ;}"))
    })
  
  output$shiny_return <- renderPrint({
    input$current_node_id
  })
}
````

**Comment by johndrummond** [comment]
fabulous, thank you.
