### ISSUE TITLE
hoverNode: clear selection after hover

### ISSUE THREAD

**Issue by Tixierae** [datastorm-open/visNetwork#242]
Thank you so much again for the great package! 
Do you know how to clear the selection when not hovering over any node? Currently, the ID of the node that was previously hovered over stays on until another node is hovered over. 

I think the `Shiny.onInputChange` should be replaced by some kind of `update` statement but I'm not skilled enough in javascript to get this done. Any help would be much appreciated.

**Minimal reproducible example:**
````
library(visNetwork)
library(shiny)

server <- function(input, output) {
	output$network <- renderVisNetwork({
		nodes <- data.frame(id = 1:3, label=1:3)
		edges <- data.frame(from=c(1,2),to=c(2,3))

		visNetwork(nodes, edges) %>%
		visInteraction(hover = TRUE, selectable=FALSE) %>%
		visEvents(hoverNode = "function(nodes) {
		Shiny.onInputChange('current_node_id', nodes);
		;}")
	})

	output$shiny_return <- renderPrint({
	input$current_node_id
	})
}

ui <- fluidPage(
	visNetworkOutput("network"),
	verbatimTextOutput("shiny_return")
)

shinyApp(ui = ui, server = server)
````

**Comment by bthieurmel** [comment]
Hi, you can use ``blurNode`` event : 

````
      visEvents(hoverNode = "function(nodes) {
                Shiny.onInputChange('current_node_id', nodes);
                ;}", blurNode = "function(nodes) {
                Shiny.onInputChange('current_node_id', null);
                ;}")
````

**Comment by Tixierae** [comment]
Thanks much, it works like a charm! 
**Fixed example**:
```r
library(visNetwork)
library(shiny)

server <- function(input, output) {
	output$network <- renderVisNetwork({
		nodes <- data.frame(id = 1:3, label=1:3)
		edges <- data.frame(from=c(1,2),to=c(2,3))

		visNetwork(nodes, edges) %>%
		visInteraction(hover = TRUE, selectable=FALSE) %>%
      visEvents(hoverNode = "function(nodes) {
                Shiny.onInputChange('current_node_id', nodes);
                ;}", blurNode = "function(nodes) {
                Shiny.onInputChange('current_node_id', null);
                ;}")
	})

	output$shiny_return <- renderPrint({
	input$current_node_id
	})
}

ui <- fluidPage(
	visNetworkOutput("network"),
	verbatimTextOutput("shiny_return")
)

shinyApp(ui = ui, server = server)
```

**Comment by stevepowell99** [comment]
that's really useful, but the user still needs to move pointer away from the node for this to work (of course) - so if user clicks on node, something happens, doesn't move the pointer and then clicks again on the same node, nothing happens. Is it possible to set current_node_id to null directly from R, once the app has used the current_node_id information? In other words, something like visNetworkProxy("network",set_to_null("current_node_id))?
