### ISSUE TITLE
visNearestNodes and modules

### ISSUE THREAD

**Issue by johndrummond** [datastorm-open/visNetwork#243]
in https://github.com/datastorm-open/visNetwork/issues/241
@bthieurmel  kindly pointed out how to use namespaces with a module with an event, which is great.
But I find myself equally lost with modules, namespaces and visNearestNodes, regardless of where I try and add ns.
e.g.  changing the line visNetworkProxy("network")
for  visNetworkProxy(ns("network")) doesn't work either

I'm hoping this is obvious to someone, or there's a better way to do it.
-----
Thank you.
-----

E.g. no module and working
`require(visNetwork)
require(shiny)

nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

server <- function(input, output, session) {
  output$network <- renderVisNetwork({
    visNetwork(nodes, edges, 
               height = "100%", width = "100%",
               main = "") %>%
      visEvents(click = "function(nodes){
                Shiny.onInputChange('click', nodes.nodes[0]);
                ;}"
      )
})
  
  output$node_found <- renderText(input$click)
  
  output$shiny_return <- renderPrint({
    visNetworkProxy("network") %>%
      visNearestNodes(target = input$click)
  })
  }

ui <- fluidPage(
  visNetworkOutput("network"), 
  verbatimTextOutput("node_found"), 
  verbatimTextOutput("shiny_return")  
)

shiny::shinyApp(ui = ui, server = server)`

With modules and not working for the nearest nodes (the found node does work as helped previously)

`# install dev version
#devtools::install_github("datastorm-open/visNetwork")

require(visNetwork)
require(shiny)

nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

testModUI <- function(id) {
  ns <- NS(id)
  tagList(
    visNetworkOutput(ns("network")), 
    verbatimTextOutput(ns("node_found")),  
    verbatimTextOutput(ns("shiny_return"))  
    
  )
}

testMod <- function(input, output,session, nodes,edges) {
  ns <- session$ns
  
  output$network <- renderVisNetwork({
    visNetwork(nodes, edges, 
               height = "100%", width = "100%",
               main = "") %>%
      visEvents(click = paste0("function(nodes){
                Shiny.onInputChange('",ns('click'),"', nodes.nodes[0]);
                ;}")
      )
  })
  output$node_found <- renderText(input$click)

    
  output$shiny_return <- renderPrint({
    visNetworkProxy("network") %>%
      visNearestNodes(target = input$click)
  })
}

server <- function(input, output, session) {
  callModule(testMod,"lookAtNearest", nodes,edges)

  }

ui <- fluidPage(
  testModUI("lookAtNearest")
)

shiny::shinyApp(ui = ui, server = server)`

**Comment by johndrummond** [comment]
I think this essentially a question on: how does one use visNetworkProxy in a shiny module; merely wrapping the shinyID parameter in ns doesn't work.

**Comment by bthieurmel** [comment]
This is the use of ``visNetworkProxy`` in module : 

````

 ns <- session$ns

  output$network <- renderVisNetwork({ })

  visNetworkProxy(ns("network"))....

````

But there is also a bug with ``visNearestNodes in module. Look when find time....!

**Comment by johndrummond** [comment]
Ah. That explains it. Thank you.
Fwiw confirming what you said, the following works for visGetConnectedNodes using a module



swapping in 
`  observe({
    if(length(input$click) == 1){
      visNetworkProxy(ns("network")) %>%
        visGetConnectedNodes(id = input$click, input = ns("connected_nodes"))
    }
  })
  
  output$shiny_return <- renderPrint({
    input$connected_nodes
  }) `

**Comment by bthieurmel** [comment]
Fix on github. And so the correct syntax is (after uptade package) : 

````
testMod <- function(input, output,session, nodes,edges) {
  ns <- session$ns
  
  output$network <- renderVisNetwork({
    visNetwork(nodes, edges,
               height = "100%", width = "100%",
               main = "") %>%
      visEvents(click = paste0("function(nodes){
                               Shiny.onInputChange('",ns('click'),"', nodes.nodes[0]);
                               ;}")
      )
  })
  
  output$node_found <- renderText(input$click)
  
  output$shiny_return <- renderPrint({
    visNetworkProxy(ns("network")) %>%
      visNearestNodes(target = input$click)
  })
}
````
