### ISSUE TITLE
Mark subsets of nodes in R

### ISSUE THREAD

**Issue by ggvvaa** [datastorm-open/visNetwork#245]
Hi,
I have a question.
Is there a way of marking subsets of nodes, or nodes belonging to different groups with visNetwork? I found an implementation of the idea, in the package "igraph". The image below shows what i mean exactly ([Full example](http://www.kateto.net/polnet2016)).

![igraph](https://user-images.githubusercontent.com/23385224/38416796-9640b0fc-399e-11e8-942a-bf9f41820281.png)

I searched for different implementations of the example above, bud I don't seem to find anything relevant.

Cheers :)

**Comment by bthieurmel** [comment]
Yes, with javascript and svg. See #233.

We can think about a simple function in next version....!

**Comment by ggvvaa** [comment]
Thanks for replying so fast,
I'm playing around, with the function you provided in #233, and looking forward for a possible implementation.
