### ISSUE TITLE
Error: This function should not be called directly

### ISSUE THREAD

**Issue by joyce-ji** [datastorm-open/visNetwork#246]
Recently, my plots generated by visnetwork stopped working with this error:

> Error: This function should not be called directly

After looking into the error, it seems that a function from dplyr was called directly and causing the error. And I'm sure my part of code didn't cause the errors. Can anyone help me with that?

**Comment by bthieurmel** [comment]
Can't help you without more information.... And ``visNetwork`` doesn't use ``dplyr``
