### ISSUE TITLE
Prevent `color.border` from coercing to `color.highlight` upon node selection

### ISSUE THREAD

**Issue by JoGall** [datastorm-open/visNetwork#247]
Related to [issue 51](https://github.com/datastorm-open/visNetwork/issues/51):

Is there a way to define `color.border` of nodes upon selection? `color.border` appears to be coerced into matching `color.highlight` when provided.

This plot results initialises with unselected nodes having a black border as expected, but border colour appears to revert to `color.highlight` colour on selection.

```
nodes <- data.frame(id = 1:3,
                    color.background = c("green","blue","blue"),
                    color.highlight = c("lightgreen","lightblue","lightblue"),
                    color.border = "black")
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges)
```

Exaggerating border size shows the borders are still drawn:

```
visNetwork(nodes, edges) %>% 
  visNodes(borderWidth = 20, borderWidthSelected = 20)
```

This is also the case if color arguments are provided using `visGroups`:

```
nodes <- data.frame(id = 1:3,
                    group = c("A", "B", "B"))
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges) %>% 
  visGroups(groupname = "A", color = list(background = "green", border = "black", highlight = "lightgreen")) %>% 
  visGroups(groupname = "B", color = list(background = "blue", border = "black", highlight = "lightblue"))
```

**Comment by bthieurmel** [comment]
Usins ``background`` and ``border`` for ``highlight`` ? See ``?visNodes``, color section. 

````
nodes <- data.frame(id = 1:3,
                    color.background = c("green","blue","blue"),
                    color.highlight.background = c("lightgreen","lightblue","lightblue"),
                    color.highlight.border = "red",
                    color.border = "black")
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges)
````

**Comment by JoGall** [comment]
OMG I swear I'm not one of these people that doesn't read the man pages first when something goes wrong but I somehow totally missed that highlight and hover took subarguments.

Sorry -- thanks for the quick response!
