### ISSUE TITLE
Available Layouts

### ISSUE THREAD

**Issue by AmazingSean** [datastorm-open/visNetwork#250]
<img width="951" alt="screenshot 2018-04-27 09 44 14" src="https://user-images.githubusercontent.com/15025485/39374397-93071cca-49ff-11e8-913f-3b07ce69be31.png">

Hi,
Is it possible to create a layout like this using the now available functions in the library?

Thanks in advance!

**Comment by bthieurmel** [comment]
Of course. Using ``visHierarchicalLayout`` option
