### ISSUE TITLE
Line breaks in Edge Title

### ISSUE THREAD

**Issue by yoshimoncho** [datastorm-open/visNetwork#252]
Hi!
I'm using visNetwork and I'm having problem with edges titles, they are too long. I'm using about 300 characters for the title, but its a very big line and it is really ugly. If there is no solution for that, I would like to display that text in an alert box when selecting the edge, however alert boxes in JS are not pretty. Is there any alternative solution for alert boxes in R ?
Thanks!

**Comment by bthieurmel** [comment]
Hi,

You just have to play a little with ``css``, using for example ``max-width`` and ``word-break: break-all`` : 

````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), 
                    title = c("shot", "this is a very very very very very..............................long title"))

visNetwork(nodes, edges)%>%
  visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;
                font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;
                -moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;
                 border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2)
                 max-width:100px;word-break: break-all')
````

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by bthieurmel** [comment]
So, I've just change the default ``css`` using now ``max-width:400px;word-break: break-all'``

**Comment by Gryphire** [comment]
Hi!

I'm having the exact same issue as OP (using VisNetwork in R), but unfortunately the code you provided doesn't do anything for me @bthieurmel. My code is below, and I've included a screenshot to display my issue. 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/17269537/180785615-83335ab3-08d3-4836-86cb-4cbed1619064.png">


<img width="1148" alt="image" src="https://user-images.githubusercontent.com/17269537/180785047-c4e0bbd2-d6bf-46ae-b13f-8ea19cd6912d.png">
