### ISSUE TITLE
Highlighting nearest nodes in visNetwork

### ISSUE THREAD

**Issue by amirh357** [datastorm-open/visNetwork#255]
Is it possible to highlight ONLY nodes that are in "downstream" of a selected node in a visNetwork with a certain level of depth (or degree)? For example, if I'm modeling a food supply chain using visNetwork and I select a retail store, I'm only interested to identify entities (e.g., processing facilities, farms, etc) that are downstream of selected retail store. I dont want to select what is after that retail store (e.g., consumer nodes).  It doesnt seem like visOptions allow you to specify a direction for your nearest neighbor. Does it make sense?

**Comment by TitouanRobert** [comment]
Hello,
you can use visOptions with degree like this : 

```
library(visNetwork)

nodes <- data.frame(id = 1:24, group = c(rep("Data center", 3),
                                         rep("antenna", 6),
                                         rep("Users", 15)),
                    label = "")
edges <- data.frame(from = c(1,1,2,2,2,3,3,3,4,4,5,5,6,6,6,7,7,7,8,8,8,9,9), to = c(9,8,4,5,6,6,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24),
                    color = c(rep("blue", 9), rep(c("blue", "green"), 7)),
                    width = 3)
ledges <- data.frame(color = c("blue", "green"),
                     label = c("In", "Out"), font = "20px" )

visNetwork(nodes, edges, width = "100%", main = list(text = "Phone",
                                                     style = "font-size:30px;text-align:center;"), height = "800px",
           submain =list(text = "City",
                         style = "font-weight:bold;font-size:20px;text-align:center;"), footer =list(text = as.character(Sys.Date()),  style = "font-size:30px;text-align:center;") ) %>%
  visGroups(groupname = "Data center", shape = "icon", 
            icon = list(code = "f233", size = 100), font = "20px") %>%
  visGroups(groupname = "antenna", shape = "icon", 
            icon = list(code = "f143", color = "blue", size = 60), font = "20px") %>%
  visGroups(groupname = "Users", shape = "icon", 
            icon = list(code = "f10b", color = "red"), font = "20px") %>%
  visOptions(highlightNearest =  list(enabled = TRUE, algorithm = "hierarchical", 
                                      degree = list(from = 0, to = 50)), collapse = TRUE)  %>%
  visLegend(addEdges = ledges, useGroups = TRUE, width = .2) %>%
  addFontAwesome()

```
You can also specify deep of your highlight (0 - 50 for my exemple)
Best

**Comment by amirh357** [comment]
Thank you so much for the response. Just one question, what if I want to click on a user (in your example) and trace back the connecting antennas as well as data centers? Right now, it doesnt do that.  Is this done through how we define the edges? it doesnt seem we can enforce a "direction" in our edges although visEdges can show an arrow using "from" or "to" but by direction i mean tractability (i.e., grabbing a node and go back in the network to reach the source).

Also, if i click on a node and get all connecting nodes based on your example, can i get the ids for those nodes as well? For a single node id, i can add this code to my server code (using shiny):
visEvents(select = "function(nodes) {
                    Shiny.onInputChange('current_node_id', nodes.nodes);
                    ;}")
and get the id for the node that is clicked by the user, but im wondering if I can get the ids for all connecting nodes?

Thanks!

**Comment by amirh357** [comment]
I think I found the answer. It depends on how you define "from" and "to" in your edge file. So, if there is a hierarchy in your network and you want to perform trace-back, you need to define the edges from the end nodes to the begining nodes. I hope there was a feature in visNetwork that could do nearestneighbor in both directions. Maybe thats something to add though.

**Comment by amirh357** [comment]
Okay I think I now understand how this works. It's all about degree=list(from=xx, to=yy). Thank you for your help!
