### ISSUE TITLE
Download node positions clicking on one button.

### ISSUE THREAD

**Issue by nanls** [datastorm-open/visNetwork#258]
Hi!

Inspired by [this answear](https://github.com/datastorm-open/visNetwork/issues/138#issuecomment-278902307) to issue #138, I start to try to download the current node positions, without having to click on `store_position` button right before. Thus, I ended with this code:

```r
library(shiny)
library(visNetwork)

# network data
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

# Define UI
ui <- shinyUI(fluidPage(
    visNetworkOutput("network"),
    downloadLink('downloadNetwork', 'Download network'),
    verbatimTextOutput("nodePositions")
))

# Define server
server <- shinyServer(function(input, output) {

    output$nodePositions <- renderPrint({
        input$network_positions
    })

    output$network <- renderVisNetwork({
        visNetwork(nodes, edges) %>% visOptions(highlightNearest = TRUE) %>%
            visPhysics(enabled = FALSE) %>% visEdges(smooth = FALSE)
    })

    output$downloadNetwork <- downloadHandler(
        filename = function() {
            paste('network-', Sys.Date(), '.html', sep = '')
        },
        content = function(con) {
            
            # Use to be run if `store_position` button clicked 
            visNetworkProxy("network") %>% visGetPositions()

            # format positions
            if (!is.null(input$network_positions)) {
                nodes_positions <- do.call("rbind", lapply(input$network_positions, function(x){ data.frame(x = x$x, y = x$y)}))
                nodes_positions$id <- names(input$network_positions)
                nodes_positions
            } else {
                NULL
            }

            if(!is.null(nodes_positions)){
                nodes_save <- merge(nodes, nodes_positions, by = "id", all = T)
            } else  {
                nodes_save <- nodes
            }

            visNetwork(nodes = nodes_save, edges = edges, height = "800px") %>%
                visOptions(highlightNearest = TRUE) %>% visExport() %>%
                visPhysics(enabled = FALSE) %>% visEdges(smooth = FALSE) %>% visSave(con)
        }
    )

})

# Run the application
shinyApp(ui = ui, server = server)

```

At the beginning I have:
![visnetwork-saveposition-atthebegining](https://user-images.githubusercontent.com/3973705/42933154-5d4ce746-8b44-11e8-9566-6b7277faa0c8.png)

Then, I click on the Download button, there is an internal error:
![visnetwork-saveposition-trydownloading](https://user-images.githubusercontent.com/3973705/42933170-65b11e7a-8b44-11e8-92b7-ee6e14275474.png)
And that is what is outputed in the console : 
```
Warning: Error in download$func: object 'nodes_positions' not found
  [No stack trace available]
```
The file is not downloaded, but you can see that the verbatim output has been updated. 

Then, if I move a node, then click on the download button, the html file is created with old positions and the verbatim output is updated with new positions.

_____________

I do not understand this behavior. Can't we use `input$network_positions` just after the call to `visNetworkProxy("network") %>% visGetPositions()` ?

Thanks!

**Comment by bthieurmel** [comment]
``visNetworkProxy("network") %>% visGetPositions()`` is an ``observe`` javascript event. So you have a kind of delay before get back the results in ``shiny``. So you have to separate process like in #138
