### ISSUE TITLE
visEdges does not honor fine-grained specification of chosen

### ISSUE THREAD

**Issue by KallyopeBio** [datastorm-open/visNetwork#261]
visEdges appears to respect boolean values for the chosen option, but it does not appear to use the functions supplied as arguments to chosen.edge or chosen.label. 

See the following simplified code snippet
``visNetwork(nodes = nd, edges = ed) %>% 
            visEdges(width = edge.width, font = list(size = edge.font.size), 
                chosen = list(edge = TRUE, label = function(values, 
                  id, selected, hovering) {
                  values.size = 100
                }))``

Given the above, when I click on an edge, the size of the edge label does not change. That's the problem. Moreover, the chosen.label function does not appear to be called at all (because putting code inside the function that should terminate the program has no effect after clicking on an edge).

**Comment by bthieurmel** [comment]
Hi,

you have to use ``htmlwidgets::JS`` to set this as a javascript function : 

````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), label = "edge")

visNetwork(nodes = nodes, edges = edges) %>% 
  visEdges(width = 5, 
           font = list(size = 10), 
           chosen = list(edge = TRUE, 
                         label = htmlwidgets::JS("function(values, id, selected, hovering) {values.size = 100;}"))) %>%
  visInteraction(hover = TRUE)
````

**Comment by KallyopeBio** [comment]
This works, and the use of htmlwidgets::JS makes perfect sense. Thank you very much!

I have one additional question. I'm trying to use this feature to make edge labels appear only when an edge is selected. This feature is useful in my scenario, where I'm working with a multigraph in which many nearby edges appear near each other in the plot, and when each edge has a different meaning. 
So I'm setting the initial edge label font size to be small, then increasing it dramatically when the edge is selected. This is now working. But one issue remains. Because the initial font size is set small, even the large font doesn't actually appear until I zoom in on the plot, enough that I'd be able to see fonts of the original size. 

Is there a workaround for this additional problem? Or should I use another technique to accomplish what I'm aiming for?

**Comment by KallyopeBio** [comment]
I see that one option is to use the scaling.label.drawThreshold option, which will force the initially small edge labels to be drawn. This then allows the large labels to appear immediately when edges are selected. The only disadvantage of this approach is performance: rendering all the small edge labels makes interaction with the network slower.

**Comment by KallyopeBio** [comment]
If I export the graph to html, I noticed that my browser doesn't experience the same performance hit as the Viewer in RStudio. Further, I noticed that my browser renders the small labels in a different (simpler) font, while the RStudio Viewer renders the small and large labels in the same font. So one solution may be to use a font that's easy to render

**Comment by KallyopeBio** [comment]
Changing the font doesn't help with the performance issue. This issue is about ready to close. Please just let me know if you have any suggestions for maximizing rendering speed in this scenario.
