### ISSUE TITLE
Bug visClusteringByGroup with highlightNearest

### ISSUE THREAD

**Issue by Tixierae** [datastorm-open/visNetwork#263]
Reproducible example:
- download `edgelist.txt` file [here](https://www.dropbox.com/s/mj02anbj21fyo1i/edgelist.txt?dl=0) and `nodes_info.csv` file [here](https://www.dropbox.com/s/xt172lnxibosgcu/nodes_info.csv?dl=0)
- run:
```R
library(igraph)
library(visNetwork)
library(shiny)

ui <- shinyUI(fluidPage(
  visNetworkOutput("graph", height='600px')
))

server <- function(input, output) {
  edgelist = read.table('edgelist.txt',header=FALSE)
  g = graph.data.frame(edgelist[,1:2],directed=FALSE)
  nodes = read.csv('nodes_info.csv',header=T)
  g_df = get.data.frame(g, what='both')
  edges = g_df$edges
  my_groups = as.character(unique(nodes[,'group']))
  vis = visNetwork(nodes, edges) %>% visLayout(randomSeed = 1234) %>% 
    visPhysics(solver = "forceAtlas2Based", minVelocity = 25) %>%
    visClusteringByGroup(groups=my_groups) %>% 
    visOptions(highlightNearest = list(enabled = TRUE, hover = TRUE))
  output$"graph" = renderVisNetwork({vis})
}

shinyApp(ui = ui, server = server)
```

**Problem**: try double clicking on a cluster to expand it. You'll see that the app freezes. I deployed the app [here](https://safetyapp.shinyapps.io/visnetwork_2-0-3/) (based on visNetwork 2.0.4 despite the URL saying 2.0.3) so that you can see exactly what I'm getting.

If you comment out the `visOptions(highlightNearest())` statement above, cluster expansion works again.

Interestingly, the snippet above was working fine up to visNetwork 1.0.3 (the bug starts appearing with version 2.0.0). [Here](https://safetyapp.shinyapps.io/visnetwork_1-0-3/) is the same app, deployed with visNetwork 1.0.3. You'll see that it works fine.

Thank you in advance for the help!

**Comment by bthieurmel** [comment]
Fix on ``github``

**Comment by Tixierae** [comment]
thank you very much for the quick fix, and for the great package!

**Comment by Tixierae** [comment]
Not directly related to this thread, but with the dev version that I just installed from GitHub (`2.0.5`) to resolve the issue in this thread, it seems there is a problem with `visHierarchicalLayout`. The following doesn't produce any output:

```R
nodes = data.frame(id=1:3, label = as.character(1:3), size = rep(20,3))
edges = data.frame(from = c(1,2), to = c(2,3))
edges = cbind(edges, rep("to",nrow(edges)))
names(edges) = c("from","to","arrows")
visNetwork(nodes,edges) %>% visHierarchicalLayout(direction = "LR")
```
but it does if you comment out `visHierarchicalLayout(direction = "LR")`

**Comment by bthieurmel** [comment]
Thanks. Fix. For the direction, it's due to ``vis.js`` choices / algorithm

**Comment by bthieurmel** [comment]
You have to use ``sortMethod = 'directed'`` : 

````
nodes = data.frame(id=1:3, label = as.character(1:3), size = rep(20,3))
edges = data.frame(from = c(1,2), to = c(2,3))
edges = cbind(edges, rep("to",nrow(edges)))
names(edges) = c("from","to","arrows")
visNetwork(nodes,edges) %>% visHierarchicalLayout(direction = "LR", 
                                                  sortMethod = "directed")
````

**Comment by Tixierae** [comment]
Thank you very much!
