### ISSUE TITLE
manipulation mode: just allow edit, not add/delete

### ISSUE THREAD

**Issue by Fideldue** [datastorm-open/visNetwork#266]
Hi,

is it possible to allow manipulation mode, but just with the functionality to edit nodes (and/or edges) and not to add or delete any nodes/edges? Like this (http://visjs.org/docs/network/manipulation.html).
Many thanks!

**Comment by bthieurmel** [comment]
Hi,

It's now possible. Have a look to github version, and ``?visOptions`` : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

visNetwork(nodes, edges) %>% 
  visOptions(manipulation = list(enabled = TRUE, addNode = FALSE, addEdge = FALSE))
````
