### ISSUE TITLE
Drag to select multiple nodes/edges

### ISSUE THREAD

**Issue by mmorine** [datastorm-open/visNetwork#267]
Great work on this package.
I'm wondering if there's any way to drag the mouse to select multiple nodes/edges, either with right click or left click. I've seen this implemented in js [here](https://jsfiddle.net/ostrebler/qzk6kmyk/) but am not sure how to implement as a visEvent, if it's even possible.
Thanks in advance!

**Comment by bthieurmel** [comment]
Using  ``visInteraction(multiselect = TRUE)`` ? And so click on first node and use ``Ctrl + click`` or a ``long click``  to select other ?

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges) %>% visInteraction(multiselect = TRUE)
````

**Comment by mmorine** [comment]
Awesome, thanks! Such an easy solution.
