### ISSUE TITLE
[bug] visFocus freezes network

### ISSUE THREAD

**Issue by Tixierae** [datastorm-open/visNetwork#272]
**Problem:** if focusing on another node before the current focusing animation is over, the visualization freezes.
**Reproducible example**: in the app below (deployed [here](https://safetyapp.shinyapps.io/visnetwork_repro_issue/)), click on `Focus on random node`. Before the animation finishes, click again. Now, click and drag the network. It freezes. Zooming in or out is impossible. But as long as you wait for the animation to finish before clicking `Focus on random node` again, everything is fine
````r
library(visNetwork)
library(shiny)
ui = shinyUI(fluidPage(
  fluidRow(
    actionLink('focus', 'Focus on random node')
  ),
  fluidRow(
    visNetworkOutput('graph', height='600px')
  )
))
server = function(input, output) {
  nodes = data.frame(id=1:8)
  edges = data.frame(from=c(1,2,1,3,3,3,6,7,8), to=c(2,3,3,4,5,6,7,1,2))
  vis = visNetwork(nodes,edges) 
  output$'graph' = renderVisNetwork({vis})
  observe({
    input$focus
    visNetworkProxy('graph') %>% visFocus(id=sample(1:8,1),scale=4)
  })
}
shinyApp(ui=ui, server=server)
````
I'm using `visNetwork_2.0.5` and `shiny_1.1.0.9001` (latest dev versions).

**Comment by bthieurmel** [comment]
I think I can't fix that in ``R`` package....

**Comment by Tixierae** [comment]
Do you have an idea what creates the issue?

**Comment by Tixierae** [comment]
In light of my comment above, could you please explain why you think this cannot be fixed in R? 
Do you have any suggestion on how to circumvent the problem? I can ignore user clicks if within 1 or 2 secs of one another, but this is very hacky. It'd be better if we could understand the root of the problem and fix it.

**Comment by bthieurmel** [comment]
In ``R``, we just call the  ``JS`` method....

Perhaps you can try ``visFocus(id=sample(1:8,1),scale=4, locked = FALSE)``

**Comment by Tixierae** [comment]
That seems to work! Thanks a bunch!
