### ISSUE TITLE
Render visNetwork in R graphics device.

### ISSUE THREAD

**Issue by jamieAmacpherson** [datastorm-open/visNetwork#273]
Is visNetwork compatible with windows or X11 R graphics devices? I would like the output of visNetwork to be rendered within the windows. Instead, the output is forced to the Rstudio viewer.

A minimal example of what I mean:

```
# generate some test nodes and edges to plot
test.nodes = as.data.frame(c('n1', 'n2', 'n3'))
names(test.nodes) = 'id'
test.edges = as.data.frame(cbind(c('n1', 'n1', 'n2', 'n3'), c('n2', 'n3', 'n2', 'n3')))
names(test.edges) = c('from', 'to')

# launch an empty R graphics device 
windows()

# plot network within the R graphics device
# instead of going to the graphics device, the output of below is forced
# to the Rstudio viewer
visNetwork::visNetwork(test.nodes, test.edges)

```

Can I force `visNetwork()`  to `windows()`?

Thanks!

**Comment by dataquestions** [comment]
If you ran this in a shiny app - you can click run external within the top tap where it says "R viewer (default)"

**Comment by bthieurmel** [comment]
I think X11 R windows is only for "static" graphics. ``visNetwork`` and all ``htmlwidgets`` packages results in ``.html`` graphics, needed a ``Viewer`` or a ``browser`` for render

**Comment by jamieAmacpherson** [comment]
Ok. Thanks for clarifying that for me.
