### ISSUE TITLE
visNetwork() does not display in Jupyter

### ISSUE THREAD

**Issue by buddha314** [datastorm-open/visNetwork#28]
When attempting to use visNetwork with Jupyter, the display does not render, nor does it error.  I've attached a screenshot of a notebook and can include the notebook by email if needed
<img width="1280" alt="screen shot 2015-11-19 at 11 41 39 am" src="https://cloud.githubusercontent.com/assets/630441/11282130/926fddb6-8eb2-11e5-9655-834a2b59f531.png">
.

**Comment by bthieurmel** [comment]
HI, 

It's seems that javascript graphic in R package using htmlwidget don't display (yet ?) in jupyter.

 You can have a look to Rendering htmlwidgets in Jupyter #144 (https://github.com/ramnathv/htmlwidgets/issues/144)
