### ISSUE TITLE
Limit the number of time steps of network simulation

### ISSUE THREAD

**Issue by jamieAmacpherson** [datastorm-open/visNetwork#281]
While I know it is possible to define the timestep within `visPhysics`, the simulation continues for eternity (or until the positional coordinates are stabilized). Is it possible to explicitly limit the number of timesteps evaluated in the simulation?

Thanks! 

P.S Great work. Love the package!

**Comment by bthieurmel** [comment]
Hi,

Physics is very complex... You can try to play with ``minVelocity``, ``maxVelocity`` and perhaps ``iterations `` ?

````
nnodes <- 100
nnedges <- 200

nodes <- data.frame(id = 1:nnodes)
edges <- data.frame(from = sample(1:nnodes, nnedges, replace = T), 
                    to = sample(1:nnodes, nnedges, replace = T))

visNetwork(nodes, edges)

visNetwork(nodes, edges) %>%
  visPhysics(minVelocity = 10)

visNetwork(nodes, edges) %>%
  visPhysics(minVelocity = 10, stabilization = list(enabled = TRUE, iterations = 10))
````
