### ISSUE TITLE
Font awesome display issues

### ISSUE THREAD

**Issue by GilesPercy** [datastorm-open/visNetwork#287]
If I look in the font awesome section at 

http://datastorm-open.github.io/visNetwork/image_icon.html

with IE11 or Firefox 63.0.3 then I don't see font awesome icons. Only if I move the tree do they appear. 

I am having other issues with font awesome - it appears like the dependency is not properly attached with addFontAwesome. If you disable physics then I see no icons in Rstudio viewer e.g.

nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
edges <- data.frame(from = c(1,2), to = c(2,3))

visNetwork(nodes, edges) %>%
  visGroups(groupname = "A", shape = "icon", icon = list(code = "f0c0", size = 75)) %>%
  visGroups(groupname = "B", shape = "icon", icon = list(code = "f007", color = "red")) %>%
  visPhysics(enabled = FALSE) %>% 
  addFontAwesome()

**Comment by bthieurmel** [comment]
Dependency is properly attached but some times not full loaded rendering network on less performance browser( RStudion, IE, ...), so you have to click / move the network...

I just add a little patch when ``visPhysics(enabled = FALSE)``.
