### ISSUE TITLE
Change colors of individual nodes

### ISSUE THREAD

**Issue by elbamos** [datastorm-open/visNetwork#288]
I'm trying to build a shiny app in which the user can select an attribute to use to color the graph.

I'm trying to update the colors using the `observe`/`visNetworkProxy` pattern in the documentation, but its not working. 

When I try to use `visNodes`, the function appears only able to set every node to be the same color. It ignores the `id` parameter and isn't vectorized.  

I.e., `visNetworkProxy("Simple") %>% visNodes(id="first_node", color="green")` will change every node to green.  `visNetworkProxy("Simple") %>% visNodes(color=[some vector)` will change every node to (I think the first) color in the vector.  

`visSetData` redraws the entire graph, which is what I'm trying to avoid. 

`visUpdateNodes`, passing a data.frame with the `color` field changed, does nothing at all.  

What's the right way to do this?  Do I need to set groups each time? If so, this doesn't really work, since some of the attribute are real-valued rather than categorical.

**Comment by bthieurmel** [comment]
If you want to change the colors / or some properties of some nodes, you have to use ``visUpdateNodes`` passing a ``data.frame`` with ``id`` column like this : 

````
library(shiny)
library(visNetwork)


nodes <- data.frame(id = paste0("L", 1:3))
edges <- data.frame(from = c(1,2), to = c(1,3))

# Define UI for application that draws a histogram
ui <- fluidPage(
  visNetworkOutput("net"), 
  actionButton("action_1", "visUpdateNodes")
  
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$net <- renderVisNetwork({
     visNetwork(nodes, edges)
   })
   
   observeEvent(input$action_1,{
     visNetworkProxy("net") %>%
       visUpdateNodes(nodes= data.frame(id = "L1", color = "green"))
   })
   
}

# Run the application 
shinyApp(ui = ui, server = server)
````

``visNodes`` can be use to change global options shared between nodes.

**Comment by elbamos** [comment]
Worked - thanks!
