### ISSUE TITLE
nearestHighlighted - labelOnly possibly not working?

### ISSUE THREAD

**Issue by thisisnic** [datastorm-open/visNetwork#289]
I am trying to create a network where, in the options, `nearestHighlighted` is set to `TRUE`, but the labels are still visible for nodes which aren't highlighted.  However, when I run the example below, the labels are no longer visible for the nodes not highlighted once a node is selected.

```
library(visNetwork)

nodes <- data.frame(id = 1:7,
                    label  = c("Top level node",
                      "Subnode 1", "Subnode 2",  "Subnode 3",
                      "Sub-subnode 1", "Sub-subnode 2", "Sub-subnode 3"
                    )
)

edges <- data.frame(from = c(1,1, 1, 2:4), to = 2:7)

visNetwork(nodes, edges) %>%
  visOptions(highlightNearest = list(
    enabled = TRUE,
    degree = 1,
    labelOnly = FALSE
  ))
```
I wasn't sure if this is a bug or if I'm just misinterpreting what `labelOnly` is supposed by applying to?

I'm using R 3.4.3 and visNetwork 2.0.5.

**Comment by bthieurmel** [comment]
Hi, 

with ``labelOnly = FALSE``, the labels are no longer visible for the nodes not highlighted once a node is selected

with ``labelOnly = TRUE``, the labels for nodes on ``degree + 1`` (not highlighted but on neighborhood of highlighted  nodes) are visibled.

And in both case, all labels are visible if no node selected
