### ISSUE TITLE
Legend displays incorrectly when there is only one group level with multi-character group names

### ISSUE THREAD

**Issue by jayqi** [datastorm-open/visNetwork#290]
When I run the following example:
```
library(magrittr)
library(visNetwork)
nodes <- data.frame(id = 1:3, group = c("FOO", "FOO", "FOO"))
edges <- data.frame(from = c(1,2), to = c(2,3))
# default, on group
visNetwork(nodes, edges, width = "100%") %>%
    visGroups(groupname = "FOO", color = "red") %>%
    visLegend()
```
I get:
![](https://user-images.githubusercontent.com/2721979/49481038-b114af00-f7ee-11e8-8a27-7a71c5a67fb5.png)

This appears to be a problem specifically when there is both only one group level and the group level names are character strings with more than one character.

The following examples behave as expected:
```
library(magrittr)
library(visNetwork)
nodes <- data.frame(id = 1:3, group = c("F", "F", "F"))
edges <- data.frame(from = c(1,2), to = c(2,3))
# default, on group
visNetwork(nodes, edges, width = "100%") %>%
    visGroups(groupname = "F", color = "red") %>%
    visLegend()
```
![](https://user-images.githubusercontent.com/2721979/49481073-d7d2e580-f7ee-11e8-972f-eeb16dcb0b29.png)

```
library(magrittr)
library(visNetwork)
nodes <- data.frame(id = 1:3, group = c("FOO", "FOO", "FOO"))
edges <- data.frame(from = c(1,2), to = c(2,3))
# default, on group
visNetwork(nodes, edges, width = "100%") %>%
    visGroups(groupname = "FOO", color = "red") %>%
    visLegend()
```
![](https://user-images.githubusercontent.com/2721979/49481098-e4efd480-f7ee-11e8-96b8-77934de9597a.png)

**Comment by bthieurmel** [comment]
Thanks. Fix on github.
