### ISSUE TITLE
Fontawesome icons for nodes do not render in a shinydashboard application

### ISSUE THREAD

**Issue by redstplr** [datastorm-open/visNetwork#292]
library(shinydashboard)
library(visNetwork)
library(magrittr)
library(shiny)

# Build a shinydashboard UI
header <- dashboardHeader(title = "visNetwork Graph")

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("visNetwork", tabName = "graph", icon = NULL)
  )
)

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "graph",
      fluidPage(
        visNetworkOutput("le_graph", width = "100%", height = "600px")
      )
    )
  )
)

dashboardUI <- dashboardPage(header, sidebar, body, skin = "red")

# Build a standard shiny UI
shinyUI <- fluidPage(
    visNetworkOutput("le_graph", width = "100%", height = "600px")
  )
)

# Application server
SERVER <- function(input, output) {
  output$le_graph <- renderVisNetwork({
    nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
    edges <- data.frame(from = c(1,2), to = c(2,3))

    visNetwork(nodes = nodes, edges = edges, main = "Attack Paths",
              width = "100%", height = "600px") %>%
      visEdges(arrows = "to") %>%
      visGroups(groupname = "A", shape = "icon", 
                icon = list(code = "f007", size = 75)) %>%
      visGroups(groupname = "B", shape = "icon", 
                icon = list(code = "f0c0", color = "#f46d43")) %>%
      addFontAwesome() %>% 
      visIgraphLayout() %>%
      visOptions(manipulation = TRUE, nodesIdSelection = TRUE,
                 highlightNearest = list(enabled = T, degree = 2, hover = T))
  })
}

# Application
dashboardapp <- shinyApp(ui = dashboardUI, server = SERVER)
shinyapp <- shinyApp(ui = shinyUI, server = SERVER)

# Fontawesome icons do not render in the shinydashboard application
runApp(dashboardapp) # does not work
runApp(shinyapp) # does work

**Comment by bthieurmel** [comment]
Hi,

It's because ``shinydashboard`` uses ``fontAwesome 5`` but ``vis.js`` uses and is restricted to ``fontAwesome 4``....

I've just add a fix on github, so you can now change library/dependency name like this : 

````
addFontAwesome(name = "font-awesome-visNetwork")
````

**Comment by redstplr** [comment]
Thank you for the quick fix!

**Comment by YallaToure** [comment]
Hi,

I am quite new to R and shiny so this might be a rookie mistake. Although I have tried everything the icons (nodes) in my network are not displayed; instead I only see empty squares. 

I want to use the Google Play icon (f3ab) of Font Awesome 5 and have runned the following code:

    visNetwork(nodes.p.top.20, edges.p.top.20, main = list(text = "Sentiment polarity network top 20 apps", style = "font-family:Helvetica Neue, Helvetica, Arial,sans-serif;font-weight:bold;font-size:20px;text-align:center;")) %>%
      visNodes(shape = "icon",
                icon = list(face = "'Font Awesome 5 Free'", code = "f3ab", size = 75)) %>%
      addFontAwesome(version = "5.13.0") %>%
      visNetwork::visIgraphLayout(physics = FALSE) %>%
      visPhysics(stabilization = FALSE) %>%
      visInteraction(hover = TRUE, navigationButtons = TRUE, 
                     zoomView = TRUE, keyboard = TRUE)

I have tried various inputs for 'face' and 'version', and even changed 'code' to another icon but nothing seems to work. 

Does anyone know what could be the issue here?

**Comment by bernardsilenou** [comment]
@YallaToure 
you used `addFontAwesome(version = "5.13.0")` in your code but the only arguments of the function are graph and name.
You can follow the example in the help file of addFontAwesome
