### ISSUE TITLE
Control when labels disappear?

### ISSUE THREAD

**Issue by ashenkin** [datastorm-open/visNetwork#296]
Hi all,

Is it possible to control when labels fade and disappear?  The networks I'm working with are complex enough that vis.js (I guess?) is disappearing the labels as (I guess) it's judging them to be too crowded.  However, it's important for my application to show the labels, even if it's a bit unseemly and crowded.  Is there any way to control this?

Thanks,
Alex

**Comment by bthieurmel** [comment]
Hi,

You can try to play with ``font`` and ``scaling`` properties :


````

nodes <- data.frame(id = 1:3, label = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% 
  visNodes(font = list(size = 25) , 
           scaling = list(label = list(
             enabled = TRUE, 
             min = 25, max = 100, 
             maxVisible = 100, 
             drawThreshold = 1
           )))
````
