### ISSUE TITLE
Question: How to call id of nodes defined in Server in UI when using visNetworkProxy

### ISSUE THREAD

**Issue by Mtmmmmm** [datastorm-open/visNetwork#301]
I am building a network analysis using visNetwork package in Shiny and would like to use visNetworkProxy to **interact** with **nodes** **defined in Server** by their **ids** in the app

As the code below, for **selectInput** in **UI**, I'd like to call a list **"nodes$id"**, which is a column of dataframe **"nodes"** defined in **Shiny Server**.

It did not work as lists called in **UI** have to be **pre-defined in R** or **directly defined inside of UI**, but **not in Shiny Server**.

```
server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    # minimal example
    nodes <- data.frame(id = 2:4)
    edges <- data.frame(from = c(2,3), to = c(2,4))

    visNetwork(nodes, edges) %>% visNodes(color = "blue")
  })


  observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("Focus", "Focus on node :",
                  nodes$id)
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
```

Thanks in advance.

**Comment by bthieurmel** [comment]
Hi,

It's not a ``visNetwork`` issue but a ``shiny`` good comprehension...!

If you data are global, you can defined it on top on ``server.R, or on global.R

````
require(visNetwork)
require(shiny)

# minimal example
nodes <- data.frame(id = 2:4)
edges <- data.frame(from = c(2,3), to = c(2,4))

server <- function(input, output) {
  output$network_proxy_nodes <- renderVisNetwork({
    visNetwork(nodes, edges) %>% visNodes(color = "blue")
  })
  
  
  observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("Focus", "Focus on node :",
                  nodes$id)
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
````

Else, you can use  ``reactive`` functions and ``update`` like this : 

````
require(visNetwork)
require(shiny)

server <- function(input, output, session) {
  
  network_data <- reactive({
    list(
      nodes = data.frame(id = 2:4),
      edges = data.frame(from = c(2,3), to = c(2,4))
    )
  })
  
  output$network_proxy_nodes <- renderVisNetwork({
    visNetwork(network_data()$nodes, network_data()$edges) %>% visNodes(color = "blue")
  })
  
  observe({
    updateSelectInput(session, "Focus", choices = network_data()$nodes$id)
  })
  
  observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 4,
      selectInput("Focus", "Focus on node :", NULL)
    ),
    column(
      width = 8,
      visNetworkOutput("network_proxy_nodes", height = "400px")
    )
  )
)

shinyApp(ui = ui, server = server)
````

**Comment by Mtmmmmm** [comment]
> Hi,
> 
> It's not a `visNetwork` issue but a `shiny` good comprehension...!
> 
> If you data are global, you can defined it on top on ``server.R, or on global.R
> 
> ```
> require(visNetwork)
> require(shiny)
> 
> # minimal example
> nodes <- data.frame(id = 2:4)
> edges <- data.frame(from = c(2,3), to = c(2,4))
> 
> server <- function(input, output) {
>   output$network_proxy_nodes <- renderVisNetwork({
>     visNetwork(nodes, edges) %>% visNodes(color = "blue")
>   })
>   
>   
>   observe({
>     visNetworkProxy("network_proxy_nodes") %>%
>       visFocus(id = input$Focus, scale = 4)
>   })
> }
> 
> ui <- fluidPage(
>   fluidRow(
>     column(
>       width = 4,
>       selectInput("Focus", "Focus on node :",
>                   nodes$id)
>     ),
>     column(
>       width = 8,
>       visNetworkOutput("network_proxy_nodes", height = "400px")
>     )
>   )
> )
> 
> shinyApp(ui = ui, server = server)
> ```
> Else, you can use `reactive` functions and `update` like this :
> 
> ```
> require(visNetwork)
> require(shiny)
> 
> server <- function(input, output, session) {
>   
>   network_data <- reactive({
>     list(
>       nodes = data.frame(id = 2:4),
>       edges = data.frame(from = c(2,3), to = c(2,4))
>     )
>   })
>   
>   output$network_proxy_nodes <- renderVisNetwork({
>     visNetwork(network_data()$nodes, network_data()$edges) %>% visNodes(color = "blue")
>   })
>   
>   observe({
>     updateSelectInput(session, "Focus", choices = network_data()$nodes$id)
>   })
>   
>   observe({
>     visNetworkProxy("network_proxy_nodes") %>%
>       visFocus(id = input$Focus, scale = 4)
>   })
> }
> 
> ui <- fluidPage(
>   fluidRow(
>     column(
>       width = 4,
>       selectInput("Focus", "Focus on node :", NULL)
>     ),
>     column(
>       width = 8,
>       visNetworkOutput("network_proxy_nodes", height = "400px")
>     )
>   )
> )
> 
> shinyApp(ui = ui, server = server)
> ```

Thank you so much! It solved my problem!
