### ISSUE TITLE
how to chenge colors of edges in visnetwork based on weight

### ISSUE THREAD

**Issue by sirox84** [datastorm-open/visNetwork#305]
Hi everybody,

I'm using visNetwork to create my graph and now I would like to change colors of the edge when the values of the weight is more than 20! There is a way to do that?
I searched a lot in a web but I couldn't find anything regarding this problem!
Can you help me please?
Thanks a lot

> netout <- visNetwork(net$nodes, net$edges, main="Relationship between Municipality", submain="From Resident To Infection") %>%
                       visIgraphLayout(layout = "layout_with_fr") %>%
                       visNodes(borderWidth = 2,color = list(hover = "red"))%>%
                       visEdges(arrows = "middle",smooth = list(enabled = TRUE))%>%
                       visOptions(highlightNearest = TRUE, nodesIdSelection = list(enabled = TRUE, 
                                                                                   style = 'width: 200px; height: 26px;
                                                                                   background: #f8f8f8;
                                                                                   color: darkblue;
                                                                                   border:none;
                                                                                   outline:none;')) %>%
                       visInteraction(hover = TRUE)
                       #visLegend()%>% visExport(type = "jpeg", name = "export-network", 
                                               #float = "left", label = "Save network", background = "purple", style= "")
  netout

**Comment by bthieurmel** [comment]
You can use ``color`` column in ``edges`` data.frame : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), 
                    weight = c(1, 25))

edges$color <- "red"
edges$color[edges$weight > 20] <- "#23b4f8"

visNetwork(nodes, edges)
````

Is-it what you need ?

**Comment by sirox84** [comment]
Perfect!

Thanks a lot
