### ISSUE TITLE
How to re-collapse groups clustered via visClusteringByGroup()

### ISSUE THREAD

**Issue by olyerickson** [datastorm-open/visNetwork#307]
We are currently using `visClusteringByGroup()` to initialize our graphs collapsed by group, and to expand individual groups by double-clicking. So far, so good...

We also need to re-collapse individual groups by double clicking on any node in the group; this is the reverse of the expansion behavior. We are successfully maintaining the desired state by updating based on our clicks, but this has no effect on the visNetwork object. 

We've examined the following code in the `visnetwork()` source (starting at line 3895) for expanding, but we don't see logic for collapsing. Also, the `Reinitialize` button seems to refresh the app, which resets our state. 

```
    if(x.clusteringGroup || x.clusteringColor || x.clusteringOutliers || x.clusteringHubsize || x.clusteringConnection){
      // if we click on a node, we want to open it up!
      instance.network.on("doubleClick", function (params){
        
        if (params.nodes.length === 1) {
          if (instance.network.isCluster(params.nodes[0]) === true) {
            is_clicked = false;
            instance.network.openCluster(params.nodes[0], {releaseFunction : function(clusterPosition, containedNodesPositions) {
              return containedNodesPositions;
            }});
          }
        }
      });
```

**Comment by olyerickson** [comment]
It seems like, if there was an appropriate `else` on the inner `if`, the correct behavior could be implemented...

**Comment by bthieurmel** [comment]
Hi,

Can you send me a example ? Its seems its possible to pass adding custom JS function using ``visEvents`` : 

````
nodes <- data.frame(id = 1:10, label = paste("Label", 1:10), 
                    group = sample(c("A", "B"), 10, replace = TRUE))
edges <- data.frame(from = c(2,5,10), to = c(1,2,10))

visNetwork(nodes, edges) %>%
  visEvents(type = "on", doubleClick = "function() {
            alert('first selection');}") %>%
  visGroups(groupname = "A", color = "red", shape = "database") %>%
  visGroups(groupname = "B", color = "yellow", shape = "triangle") %>%
  visClusteringByGroup(groups = c("B"), label = "Group : ", 
                       shape = "ellipse", color = "blue", force = TRUE) %>%
  visLegend()
````

**Comment by olyerickson** [comment]
Thanks for your reply. Yes, we're trying that; the issue is not detecting the doubleclick, but rather how to explode the cluster --- ie what should the function be? 

Here is our test example:
```
library(visNetwork)
library(shiny)

# Initial condition
nodes <- data.frame(id = 1:7, label = 1:7, group = c(2,3,2,1,2,1,3))
edges <- data.frame(from = c(1,1,1,2,3,4,2), to = c(5,3,4,3,5,6,7))
network = visNetwork(nodes,edges,height=1000)

groups.closed <- c(1,2,3)

server <- function(input, output) {
  
  observeEvent(input$clicked_node_id, {
    if (typeof(unlist(input$clicked_node_id[[1]])) != "character"){
      input$clicked_node_id
      myNode <- unlist(input$clicked_node_id[[1]])
      myGroup <- nodes$group[nodes$id==myNode]
      print(toString(myGroup))
      if (myGroup %in% groups.closed) {
        message <- c("Uncollapse these: ")
        groups.closed <<- groups.closed[groups.closed!= myGroup]
        visUncollapse(visNetworkProxy("network"), nodes$id[which((nodes$group %in% myGroup))])
      } 
      else {
        message <- c("Collapse these: ")
        groups.closed <<- c(groups.closed, myGroup)
        visCollapse(visNetworkProxy("network"), nodes$id[which((nodes$group %in% myGroup))])
      }
      message <- paste(message, toString(nodes$id[which((nodes$group %in% myGroup))]), sep=" ")
      print(message)
    }
  })
  
  
  output$network <- renderVisNetwork({
    palette()               # obtain the current palette
    myPalette <- palette(rainbow(11))
    
    visNetwork(nodes,edges,height=1000) %>%
      visClusteringByGroup(groups = groups.closed, label = "Group: ", 
                           shape = "circle", color=myPalette, force = TRUE) %>%
      visEvents(doubleClick = "function(nodes) {
        Shiny.onInputChange('clicked_node_id', nodes)}") %>%
      visLegend(main="Groups", position="right", ncol=1) 
    
  })
  
}

ui <- fillPage(
  visNetworkOutput("network", height = "100%")
)

shinyApp(ui = ui, server = server)
```

**Comment by olyerickson** [comment]
In our example you can see that while the expand works perfectly (as expected) our re-collapse doesn't, because it is a _collapse_ and not a _group cluster_ 

What we need to do is think different --- we need to re-cluster the un-clustered group

**Comment by olyerickson** [comment]
To see the difference, imagine maintaining group state "outside" of the object (e.g. saving state to the file system), and re-setting (refreshing the page, NOT reinitializing using the button).

**Comment by bthieurmel** [comment]
``visClusteringByGroup`` is quite old function. 

``visCollapse`` & ``visUncollapse`` are quite new function, with different logic : clustering all connected nodes from another.

I've just pushed a fix for collapse / uncollapse nodes using ``visClusteringByGroup``. You can try using dev version : 

````
devtools::install_github("datastorm-open/visNetwork")

set.seed(123)
nodes <- data.frame(id = 1:10, label = paste("Label", 1:10), 
                    group = sample(c("A", "B"), 10, replace = TRUE))
edges <- data.frame(from = c(2,5,10), to = c(1,2,10))

visNetwork(nodes, edges) %>%
  visGroups(groupname = "A", color = "red", shape = "database") %>%
  visGroups(groupname = "B", color = "yellow", shape = "triangle") %>%
  visClusteringByGroup(groups = c("B"), label = "Group : ", 
                       shape = "ellipse", color = "blue", force = TRUE) %>%
  visLegend()
````

So now, if you double-click on a node present initally in a group cluster, the cluster is recreate.

**Comment by olyerickson** [comment]
Thanks! We'll give it a shot...

**Comment by olyerickson** [comment]
That solution seems to have worked perfectly. The only issue we've encountered is that group IDs need to be single characters, ie "0"-"9", "A"-"Z", "a"-"z". Which is okay for our application, but might be limiting for some. 

THANKS!

**Comment by olyerickson** [comment]
Here is a quick demo using the famous Le Miserables network:
![Peek 2019-03-29 06-38](https://user-images.githubusercontent.com/358649/55227418-d38f6580-51ed-11e9-8044-82b03285051c.gif)

**Comment by bthieurmel** [comment]
Thanks. Fix also passing multiple character group.

**Comment by olyerickson** [comment]
Thanks!!! That change is important because it will enable users to more easily use group IDs created by e.g. community detection algorithms.

**Comment by g-pires** [comment]
Hi, did the behavior of visClusteringByGroup has changed ? On your gif of les miserables we can see that all connected edges between two nodes appear on the clustered network but now it doesn't, there is only one left, is there a way to have this behavior ?  

Thanks
