### ISSUE TITLE
[Enhancement] selectedBy() with overlapping groups

### ISSUE THREAD

**Issue by Tixierae** [datastorm-open/visNetwork#31]
Thanks for this excellent package! The title is pretty much self-explanatory. I am trying to find a way to use selectedBy() when nodes can belong to more than one group. This occurs oftentimes in practice with hierarchical decomposition of graphs (e.g., k-core decomposition). However, currently, it seems that nodes can only belong to one group.

**Comment by cjmartinIndra** [comment]
any news on this?

**Comment by bthieurmel** [comment]
It's on my roadmap in a near future...

**Comment by bthieurmel** [comment]
Hi,

Now possible with a new argument ``multiple = TRUE``, and using comma separated values in one column : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE), stringsAsFactors = F)

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

# and with multiple groups ?
nodes$group <- sample(c("group 1", "group 2", "group 1, group 2, group 3"), nrow(nodes), replace = TRUE)
visNetwork(nodes, edges) %>% 
  visOptions(selectedBy = list(variable = "group", multiple = TRUE))
````

**Comment by Tixierae** [comment]
Awesome, thank you very much! I look forward to testing this new feature!

**Comment by cjmartinIndra** [comment]
Thanks for this update. I have tested it and it is very useful!!!
