### ISSUE TITLE
Positioning the labels of Nodes

### ISSUE THREAD

**Issue by shubhrampandey** [datastorm-open/visNetwork#312]
Hi,

I just want to change the position of the labels of the nodes i.e. the labels should be above the nodes or sideways.

How can I change this as there is no option of doing this in visNetwork.Any help much appreciated/

![image](https://user-images.githubusercontent.com/45200005/56206283-9fc79300-6069-11e9-85b2-133243040528.png)

**Comment by bthieurmel** [comment]
Hi, 

You can only play with ``vadjust`` to control the vertical positioning of the base font in the label text (Positive is down.)

````
# minimal example
nodes <- data.frame(id = 1:3, 
                    label = LETTERS[1:3])
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visNodes(font = list(vadjust = -44))
````

**Comment by shubhrampandey** [comment]
Hi,
Thank you so much. 

This is what exactly I am looking for. Just a minor change that I want label position w.r.t the nodes because if I use vadjust then this is for all the labels not for a particular.

I want something like : 
-- | --
vertex.label.degree = The position of the label in relation to the vertex, where 0 is right, “pi” is left, “pi/2” is below, and “-pi/2” is above
-- | --

Any help regarding this is much appreciated, if not I am ok with this.

Once again thanks!!!!

**Comment by bthieurmel** [comment]
You can pass ``visNodes`` argument in two ways : 

- globally, for all nodes, using ``visNodes``
- per node on the ``data.frame``, using ``.`` for complex / hierarchical argument : 

````
# minimal example
nodes <- data.frame(id = 1:3, 
                    label = LETTERS[1:3], 
                    font.vadjust = c(44, 0, -44))
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges)
````

**Comment by shubhrampandey** [comment]
Aahh...Thank you so much for this!!!!!
