### ISSUE TITLE
Switch visNetwork javascript dependency to visjs-network?

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#322]
This project, visNetwork, depends on javascript code for displaying networks, the files vis.min.js and vis.css found in inst/htmlwidgets/lib/vis. This javascript code was originally developed on the github project [vis.js](https://github.com/almende/vis). Unfortunately, this project is no longer being maintained by the original group.

However, a fork of the relevant network code was made, and is available at [visjs-network](https://github.com/visjs-community/visjs-network). I would like to make a request that visNetwork switch its dependency from vis.js to visjs-network. Unlike vis.js, visjs-network is actively being maintained and is taking new pull requests.

I recently submitted a pull request http://github.com/visjs-community/visjs-network/pull/68 fixing a bug in vis.js

This fixes the issue https://github.com/almende/vis/issues/3150

**Comment by bthieurmel** [comment]
Hi, 

I'll try to initialize soon a new branch on github linked to  visjs-network for test, hoping there is not breaking change...!

**Comment by bthieurmel** [comment]
Hi, 

You can test the new branch : 

``devtools::install_github("datastorm-open/visNetwork", ref = "visjs-network")``

**Comment by DarylMcCullough** [comment]
Thank you so much! This is great!
Daryl McCullough 


Sent from Yahoo Mail for iPhone


On Monday, June 17, 2019, 6:19 AM, B. Thieurmel <notifications@github.com> wrote:


Hi,

You can test the new branch :

devtools::install_github("datastorm-open/visNetwork", ref = "visjs-network")

**Comment by mojoaxel** [comment]
`almende/vis` is now maintained by the community: www.visjs.org
I would recommend switching to the official successor [vis-network](https://github.com/visjs/vis-network)

**Comment by bthieurmel** [comment]
I'll have a look for the next version.

**Comment by DarylMcCullough** [comment]
Hi, I'm not sure if this should be a new issue, or not. There has been a new release of vis-network javascript code on NPM, here:

https://www.npmjs.com/package/vis-network

(The naming is confusing: vis-network is javascript, and visNetwork is R?)

It would be helpful to me to make a new release of this project using the latest javascript. There's a new feature that I would appreciate, which is the following issue:
https://github.com/visjs/vis-network/issues/149

The new feature has a mechanism to prevent overlapping of large nodes.

Thanks!

**Comment by mojoaxel** [comment]
@DarylMcCullough I think this issue should be reopened until the vis-network dependencies have been updated here!

**Comment by bthieurmel** [comment]
In progress. Seems to be ok in RStudio now, but I've to make more tests before include totally this version. But you can try : 

````
devtools::install_github("datastorm-open/visNetwork", "visjs-network")
````

**Comment by bthieurmel** [comment]
github master version is now on top on vis-js-network 7.5.2

**Comment by DarylMcCullough** [comment]
This is wonderful! Thank you.
    On Tuesday, April 7, 2020, 11:16:07 AM EDT, B. Thieurmel <notifications@github.com> wrote:  
 
 


github master version is now on top on vis-js-network 7.5.2

**Comment by stevepowell99** [comment]
sounds good, right now I am getting `Downloading GitHub repo datastorm-open/visNetwork@visjs-network
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/datastorm-open/visNetwork/tarball/visjs-network'`

**Comment by bthieurmel** [comment]
It-s now on master branch. Visjs-network was deleted

**Comment by stevepowell99** [comment]
thanks, I installed the dev version and it's working well but I get some different behaviour from the previous version:
```
visEvents(
      hoverEdge = "function(edges) {
    Shiny.onInputChange('net_hoverEdges', edges);
    ;}"
    )
```
previously, input$net_hoverEdges was the id of the edge, now it is a list with coordinates? Should I make a separate issue for this? Where should I look for any documentation about such changes?

**Comment by bthieurmel** [comment]
It seems there is some additionals information return by some event like ``hoverEdge``, but the edge is still return at the same place.

old version : 

````
$edge
[1] "e3b344bf-4c90-455b-a354-dc1ea5ff47e2"
````

new version : 

 ````
$pointer
$pointer$DOM
$pointer$DOM$x
[1] 673

$pointer$DOM$y
[1] 250


$pointer$canvas
$pointer$canvas$x
[1] -126.1446

$pointer$canvas$y
[1] 46.39698



$event
$event$isTrusted
[1] TRUE


$edge
[1] "91b08281-b106-4625-b00a-961df4c8969c"
````

So the id is in both case in ``input$net_hoverEdges$edge`` ?

For JS documentation, you can have a look to R ``visDocumentation()`` or see https://github.com/visjs/vis-network
