### ISSUE TITLE
Suggestion: Put Legend Text Outside of Dots

### ISSUE THREAD

**Issue by yiqinfu** [datastorm-open/visNetwork#328]
In the documentation, the legend looks quite nice because the label text for all groups is the same length. But when I plot groups whose names differ in length, the legend doesn't look as neat.

![Screen Shot 2019-07-01 at 2 01 09 AM](https://user-images.githubusercontent.com/23423360/60467465-b6bb6180-9c24-11e9-82fd-69fd9ead9537.png)

Could we have the option of putting the text outside of the shapes? Thanks.

**Comment by Dmirijs-Ozernovs** [comment]
You can use other shapes that have labels outside of the shape: square, triangle, dot, star, diamond.

Check this: https://datastorm-open.github.io/visNetwork/nodes.html
