### ISSUE TITLE
Prevent node overlap when using "Hierarchical Layout"?

### ISSUE THREAD

**Issue by timwilliate** [datastorm-open/visNetwork#33]
First I would like to state that I am enjoying experimenting with this package. I am working through every R package for network visualization that I can find in an attempt to find the best one for plotting directed acyclic graphs (DAG's). This is the best one I have encountered thus far.

Is there a way (i.e. a parameter to set) which will prevent nodes from contacting and/or overlapping each other when using `visHierarchicalLayout()`? I see that there is a `nodeOverlap` parameter in `visPhysics()` but it does not appear to be available for `hierarchicalRepulsion`.

**Comment by bthieurmel** [comment]
Hi, 

perhaps you can try to play with ``springConstant`` and ``nodeDistance`` options in ``visPhysics``, like this : 

````
nodes <- data.frame(id = 1:7)
edges <- data.frame(from = c(1,2,2,2,3,3),
                    to = c(2,3,4,5,6,7))


visNetwork(nodes, edges) %>%
  visLayout(randomSeed = 124, hierarchical = TRUE)

visNetwork(nodes, edges) %>%
  visLayout(randomSeed = 124, hierarchical = TRUE) %>%
  visPhysics(solver = "hierarchicalRepulsion", 
             hierarchicalRepulsion = list(springConstant = 1, 
                                          nodeDistance = 300))
````

**Comment by bthieurmel** [comment]
With the last udpate on github, and new ``vis.js 4.15.0``, there is a lot of new options for ``visHierarchicalLayout``. Perhaps what you want...
