### ISSUE TITLE
Custom function for edge hoverWidth

### ISSUE THREAD

**Issue by stevepowell99** [datastorm-open/visNetwork#331]
hoverWidth behaves unpredictably, e.g. just setting it to 5 has different effects depending on the size of the network. This is documented: https://visjs.github.io/vis-network/docs/network/edges.html but it is not clear to me how to implement this in R. Following 
https://github.com/datastorm-open/visNetwork/issues/130 I put 
`visEdges(network, hoverWidth = 'function (width) {return width*2;}',)`
but this has no effect, i.e. the hover size stays the same.
Would be very grateful for a suggestion!

**Comment by bthieurmel** [comment]
Hi,

For passing JS function, you have to use ``htmlwidgets::JS`` :

````
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% visInteraction(hover = T) %>%
  visEdges(hoverWidth = htmlwidgets::JS('function (width) {return width*10;}'))
````
