### ISSUE TITLE
In branch visjs-network, do a "pull" to get latest from visjs-network

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#332]
There was a recent (well, a few weeks ago) bug fix to the javascript code in https://github.com/visjs-community/visjs-network.git, which is (I think) being used by the branch visjs-network of visNetwork. But from my testing, it seems that the bug fix has not been incorporated. Maybe that's because visNetwork needs to pull the latest version from visjs-network?

The original bug in vis.js showed up as an issue in visNetwork, described in issue 173:

https://github.com/datastorm-open/visNetwork/issues/173

This was due to the bug described in an issue of visjs-network described here:

https://github.com/visjs-community/visjs-network/issues/67

which was fixed in this pull:
https://github.com/visjs-community/visjs-network/pull/68

**Comment by bthieurmel** [comment]
Update on github.
