### ISSUE TITLE
Ensure compatibility with the next ggraph release

### ISSUE THREAD

**Issue by thomasp85** [datastorm-open/visNetwork#334]
The reverse dependency check has identified some issues between visNetwork and the next ggraph release:

*   checking dependencies in R code ... NOTE
    ```
    Missing or unexported object: ‘ggraph::den_to_igraph’
    ```

ggraph has delegated all network handling to tidygraph and removed the inferior code it contained itself. I suggest visNetwork moves to this approach as well. I plan to submit ggraph to CRAN on September 1st and hope you'll be able to have a fix on CRAN before that.

best
Thomas

**Comment by bthieurmel** [comment]
On its way to CRAN

**Comment by thomasp85** [comment]
Thank you
