### ISSUE TITLE
Show/hide Edges bei clicking on connecting Nodes

### ISSUE THREAD

**Issue by wernerdrt** [datastorm-open/visNetwork#336]
Hi,
I want to hide all edges until i click on a node (then show the connected edges). I have the code for it, but it's not working.

`network<-visNetwork(nodes = Aggregation_Lagertyp, edges = Aggregation_transport,width = "100%", height = "1000px") %>%
  visEdges(arrows = 'to',hidden = TRUE) %>%
  visNodes(physics = FALSE)  %>% 
  visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = TRUE) %>% 
  visOptions(highlightNearest = TRUE) %>%
  visEvents(selectNode = "function(e) {
    var test = this.body.data.edges;
    e.edges.forEach(function(item) { 
      test.update({id: item,hidden : 'FALSE'});
    }); 
  }") %>%
  addFontAwesome()`

It's woking if i do the opposite, so firstly setting the edges on hidden = FALSE and when i click on a node set them on hidden = TRUE. So the code is correct. What's the problem here?
Thanks!

**Comment by bthieurmel** [comment]
In javascript, you have to use ``true`` or ``false`` in lowercase, and so : 

```test.update({id: item,hidden : false})``
