### ISSUE TITLE
Is there a way to define a layout and overlay data on top of it?

### ISSUE THREAD

**Issue by shashj** [datastorm-open/visNetwork#339]
I wanted to define a layout with Kegg pathways and then overlay data on it so that the interpretation becomes much easier. I don't know if it is possible with visnetwork right now.

Thanks

**Comment by bthieurmel** [comment]
Sorry but not clear for me...! More information ?

**Comment by shashj** [comment]
I want to define a network like below and then color the nodes according to given data

[Pathway Map](https://www.genome.jp/kegg-bin/show_pathway?map=map00020&show_description=show)

**Comment by bthieurmel** [comment]
I don't think ``visNetwork`` is the best tool for this kind of network. Perhaps you can find some solution with https://rich-iannone.github.io/DiagrammeR/ ?

**Comment by shashj** [comment]
Ok thanks will try it out
