### ISSUE TITLE
Add edge endpoint 'bar' to vis-network

### ISSUE THREAD

**Issue by Jinchao-Yu** [datastorm-open/visNetwork#343]
Initionally mentioned in https://github.com/datastorm-open/visNetwork/issues/73. However, at that time, 'bar' edge endpoint was not available in vis.js. Following 'bar' endpoint's implemntation in vis.js (https://github.com/almende/vis/pull/3444), I would like that 'bar' endpoint, maybe with more other options if they are already implmented in vis.js, can be also implmented in visnetwork.

**Comment by gadepallivs** [comment]
I see the vis-network implemented more custom edges/nodes https://github.com/visjs/vis-network/issues/153#issuecomment-546711575. Is the visnetwork package using the latest version of visjs library ?

**Comment by gadepallivs** [comment]
Hi, there is an alternate implementation by visjs library https://github.com/visjs/vis-network/issues/153#issuecomment-546711575. It seems the new update has this implementation https://github.com/visjs/vis-network/issues/153#issuecomment-546711575. Is the r package updated with latest visjs library ?

**Comment by bthieurmel** [comment]
Yes, the master on github is now up-to-date witrh ``vis-network`` and so you can use ``bar`` : 

````
visNetwork(nodes, edges) %>%
   visEdges(arrows = list(to = list(enabled = TRUE, type = "bar")))
````

**Comment by gadepallivs** [comment]
@bthieurmel Using the latest github version of the package creates a bar, but does not show the legend as bar.
