### ISSUE TITLE
Set manipulation option initiallyActive = TRUE

### ISSUE THREAD

**Issue by AlexSurtees** [datastorm-open/visNetwork#345]
Hi. I am using shiny to make an app that allows the user to make a network. However, I want it so that the Add Node and Add Edge menu is initially active rather than having to click the 'edit' button first.

I have looked at resources online and tried using visConfigure() etc., but not sure how to actually integrate the var options into the code.

Thanks,
Alex

**Comment by bthieurmel** [comment]
Hi,

You can pass all ``manipulation`` options in ``visOptions`` : 

````
visNetwork(nodes, edges) %>% 
  visOptions(manipulation = list(enabled = TRUE, initiallyActive = TRUE))
````
