### ISSUE TITLE
legend size on visSave

### ISSUE THREAD

**Issue by fmoratalla** [datastorm-open/visNetwork#347]
Hello,

Is there any way of increasing the size of the legend when donwloading a graph in shiny. I have not seen any argument to do that.

Thanks

**Comment by bthieurmel** [comment]
Hi,

You can use ``visLegend()`` before ``visSave`` or change ``width`` directly : 

````

# minimal example
nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
edges <- data.frame(from = c(1,2), to = c(2,3))

# default, on group
vis <- visNetwork(nodes, edges) %>%
  visGroups(groupname = "A", color = "red") %>%
  visGroups(groupname = "B", color = "lightblue") %>%
  visLegend()

vis

vis$x$legend$width <- 0.4
visSave(vis, file = "vis.html")
````

**Comment by fmoratalla** [comment]
Hello, 

Thanks for the answer. However this seem to partially solve my issue. I still have a very short legend althought its width is acceptable. Is there any option to set the height of the legend just as the height of the network? I am talking about the downloaded objects, not the network plots rendered by renderVisNetwork, which works perfect

Thanks in advance
