### ISSUE TITLE
Make branch that uses version 6.3.1 of vis-js-network

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#350]
Hi, I decided this should be its own issue.

There has been a new release of vis-network javascript code on NPM, here (version 6.4.0):

https://www.npmjs.com/package/vis-network

(The naming is confusing: vis-network is javascript, and visNetwork is R?)

It would be helpful to me to make a new release of this project using the latest javascript. There's a new feature that I would appreciate, which is the following issue:
visjs/vis-network#149

The new feature has a mechanism to prevent overlapping of large nodes.

This update could go into the same branch, visjs-network.

Thanks!

[note: updated version requested to 6.4.0 from 6.3.1]

**Comment by bthieurmel** [comment]
Have at moment some trouble with full R package compatibility with this version, for example ``network`` are not rendering in RStudio Viewer...

**Comment by DarylMcCullough** [comment]
Would it be possible to make a branch that is broken, so that I could see if I could help figure out what's going wrong?

**Comment by bthieurmel** [comment]
Seems to be ok in RStudio now, but I've to make more tests before include totally this version. But you can try : 

````
devtools::install_github("datastorm-open/visNetwork", "visjs-network")
````

**Comment by DarylMcCullough** [comment]
I have tested this version, and it seems to work pretty well. I haven't seen any problems.

I recommend making this branch available on CRAN as the "official" vis-network download. Is that possible?

**Comment by DarylMcCullough** [comment]
After using the new branch a while longer, I have found a couple of minor bugs. They are both illustrated by this example code:


`library(shiny)
library(visNetwork)

u <- shinyUI(fluidPage(
  visNetworkOutput("visnetwork",height="500px"),
  style = "background-color: #eeeeee;")
)

s <- shinyServer(function(input, output,session){
  output$visnetwork <- renderVisNetwork({
    nodes_sub <- data.frame(
      id = c("<https://A.com>",
             "<https://B.com>",
             "<https://C.com>"),
      label = c("A", "B", "C"),
      level = c(1,2,2)
    )
    edges_sub <- data.frame(
      from = c("<https://B.com>",
               "<https://C.com>", "<https://D.com>"),
      to = c("<https://A.com>", "<https://A.com>", "<https://A.com>"),
      arrows = "to"
    )
    #########
    visNetwork(nodes_sub,edges_sub) %>% visNetwork::visHierarchicalLayout() %>% visOptions(highlightNearest = TRUE)
  })
})

shinyApp(u,s)`

**Comment by DarylMcCullough** [comment]
There are two issues:

1. If the "edges" input to VisNetwork contains an edge where the "from" node is a non-existent node (that is, it is an id that does not appear in the "nodes" input), AND you have hierarchical layout, AND you select "highlightNearest = TRUE", then the network shows weird behavior. If you click on a node, the whole network quivers. In the above example, there is an edge connecting node A to a nonexisting node D. The nodes come together and then spring apart again. It's easy enough to avoid this bug by just making sure that the two ends of each edge are nodes that exist. But it's strange behavior, and it wasn't present in the stable version of VisNetwork.

2. A second bug, or maybe it's an idiosyncrasy, is that the display of labels inside a "box" representing a node is inconsistent between the way the first line is treated and the way the last line is treated. In the example of above, box A has a label "\nA\n". That is, there are carriage returns before and after the "A". The carriage return before the "A" successfully causes the label to have a blank line. But the carriage return after the "A" seems to have no effect. So if you want to make space at the bottom and top, you have to put in a last line that contains spaces. It's not enough to have a carriage return.

These issues are probably issues in the underlying javascript code, not with visNetwork's shiny code. I will try to make a pure javascript example that I can post to the visjs-network site.

**Comment by bthieurmel** [comment]
Ok. Thanks. Waiting for news on this point.

**Comment by DarylMcCullough** [comment]
I need some help in creating a pure-js version showing this bug. The bug shows up when in VisNetwork you choose hierarchical layout, and the hightlight nearest nodes option. I don't know how to do those things in pure vis-js. Can someone help me?

**Comment by DarylMcCullough** [comment]
In my opinion, it's worth it to make VisNetwork use the latest code from vis-js-network, even with the bugs that I found (which I haven't figured out how to reproduce in pure javascript). There are workarounds for the bugs. The most important workaround is to just check when calling visNetwork to make sure that every edge has a "to" and "from" that corresponds to the id of a node. This check could actually be done through a modification to the visNetwork function. I can't see that there would ever be a reason you would want an edge that doesn't connect two nodes.

So I would like to request a release of VisNetwork that incorporates the latest from vis-js-network.

**Comment by bthieurmel** [comment]
github master version is now on top on vis-js-network 7.5.2
