### ISSUE TITLE
Enable Shiny feedback via HTML tooltip

### ISSUE THREAD

**Issue by geotheory** [datastorm-open/visNetwork#351]
Am I right that the tooltip is a purely passive element that only responds with CSS?  What I really need is a way to click on nodes, raise a sticky tooltip/menu, click on an option, and send an instruction back to the Shiny server.  That would presumably mean enabling an actual HTML tooltip rather than just CSS.

This would enable interactive expansion of graphs.  E.g. to iteratively grow a graph from a single node or subset when the full dataset is too big or not of interest.

N.B. Shouldn't _"HTML style of tooltip"_ in visInteraction documentation not read "CSS" instead?

**Comment by bthieurmel** [comment]
Hi,

Yes you're right : only CSS for tooltip.  But you can defined shiny action when user click on a node with exsiting ``visNetwork`` input or creating a new input ?

http://datastorm-open.github.io/visNetwork/shiny.html

**Comment by geotheory** [comment]
Thanks @bthieurmel. I went with modal in the end but will bear this in mind for future.
