### ISSUE TITLE
Shiny Event marking the completion of drawing of network

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#352]
When there is a very large graph, it sometimes takes some time for the graph to draw. During this time, nothing is apparently happening on the web page.

What I would like is to be able to have a message saying something like "Please wait for the network to be drawn..." However, in order to dismiss that message when the drawing is complete, I need a Shiny Event corresponding to the completion of the drawing. Is there any way to get at such an event using VisNetwork? Or would that require a change at the javascript level?

**Comment by bthieurmel** [comment]
Perhaps you can try this #200 

And created input ``input$network_initialized`` ?

**Comment by DarylMcCullough** [comment]
Thank you. I will try it out!

**Comment by DarylMcCullough** [comment]
I have tested this out, and what I actually find more useful are the events "stabilizationProgress" and "stabilizationIterationsDone".

To use these events, you can first create a visnetwork

network <- visNetwork(...)

Then send it to visEvents:

network %>% visEvents(
   stabilizationProgress = <javascript code>,
   stabilizationIterationsDone = <javascript code>
)

where the javascript code has the form:

"function() {
   progrs = { 'value': params.iterations, 'total': params.total };
   shiny.setInputValue('progressBarId', progrs, {priority: 'event'});
}"

(if you want to update a progress bar to reflect the progress in stabilization)
