### ISSUE TITLE
Programmatically edit nodes / edge just like in visOptions(manipulation = TRUE)

### ISSUE THREAD

**Issue by terenceltl** [datastorm-open/visNetwork#359]
It is cool to use visOptions(manipulation = TRUE) to let the user e.g. add a new edge between two nodes and see the whole network wiggles a bit when the new connection is formed.

Is it possible to do it programmatically? What I want to achieve is to simulate updating the network as time goes by, and add new connections to the network when new info becomes available. For example, A is not known to be related to B at time = 0, but at time = 0, we learn that A and B is related and would like to add an edge between them. The output would be like an animation.

Is this possible?

**Comment by bthieurmel** [comment]
Hi,

It's possible in a shiny application using ``?visNetworkProxy`` & all associated methods.
