### ISSUE TITLE
how to add a hover events in visnetwork

### ISSUE THREAD

**Issue by stephenlee4413** [datastorm-open/visNetwork#360]
I want to add some customer information for a node when house hover it .
`R
visNetwork(vis_data$nodes, vis_data$edges) %>%
  visInteraction(hover = TRUE) %>%
  visEvents( hoverNode = "function(properties) {
      var node_name = this.body.data.nodes.get(properties.nodes[0]).id
      var node_degree = 12
      print('您选择的节点是:' + node_degree);
            }")
`
this code can't work!
thanks

**Comment by bthieurmel** [comment]
Hi,

all events are JS function. If you want to update ``title`` value printed on tooltip for example, you can do something like this : 

````
nodes <- data.frame(id = 1:3, title = "init title")
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% 
  visInteraction(hover = TRUE) %>% 
  visEvents( hoverNode = "function(properties) { 
            console.info(this);
            console.info(properties)
            this.body.data.nodes.update({id: properties.node, title : 'update title'});
            }") 
````
