### ISSUE TITLE
visHclust throwing "undefined columns selected" error

### ISSUE THREAD

**Issue by aschweickart** [datastorm-open/visNetwork#361]
I'm simply running the example function call from the visHclust documentation:

visHclust(iris, cutree = 3, colorEdges = "red")

And can't get past the following error:
Error in `[.data.frame`(dta$nodes, , c("id", "x", "y", "hidden", "label",  : 
  undefined columns selected

This happens no matter what the input object is (same error is thrown when I input an hclust).
Thoughts?

**Comment by bthieurmel** [comment]
Hi,

No error on last CRAN version for me. Can you send me your ``sessionInfo()`` ouput ?

**Comment by bthieurmel** [comment]
This is fix an github master. (Due to some update / change in ``ggraph``)
