### ISSUE TITLE
Recommended change to documentation for edge smoothness

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#367]
The documentation for edges, at [VisEdges](rdrr.io/cran/VisNetwork/man/visEdges.html) suggests that you use

edges$smooth <- boolean or named list

to make the edges curved. But this makes all edges curve in the same way. That might be what the user wants in some cases, but if there are two or more edges connecting the same two nodes, then those edges will overlap each other, making it hard or impossible to see both edges. What I think is more useful in many cases is to give different roundness values to different edges. Two edges that connect the same two nodes will not overlap if they have different roundness values.

It's easy enough to give different edges different roundness values, but it's not mentioned in the VisNetwork documentation. The way to do it is not to use a single attribute "smooth", but to use three different attributes:

- edges$smooth.enabled <- vector of booleans, one for each edge
- edges$smooth.type <- vector of strings, one for each edge, with values "curvedCW", "curvedCCW", etc.
- edges$smooth.roundness <- vector of numeric values between 0 and 1, one for each edge,

**Comment by bthieurmel** [comment]
Add new example updating all documentation vs js
