### ISSUE TITLE
Suggested change: Ignore edges where one or both nodes is not displayed

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#368]
As I mentioned in issue https://github.com/datastorm-open/visNetwork/issues/350, there was (I'm not sure if it's fixed, or not) a bug in the underlying vis-js-network javascript code that comes up in a specific case: when you create a network where one of the edges connects to a nonexistent node. When this happens, there is weird behavior when you click on a node that is connected to a nonexistent node.

What I mean by "nonexistent node" is this:

To create a network, you need two data frames, nodes and edges. The nodes data frame has

nodes$id

equal to the vector of ids for all nodes. The edges data frame has

edges$from
edges$to

which are vectors of node ids. The strange bug occurs when one of the ids in edges$from or edges$to is equal to a value that is not found in nodes$id.

A simple fix is that before calling visNetwork(nodes=..., edges=...), first remove any edges that don't connect to any node:

edges <- edges[ which(edges$from %in% nodes$id & edges$to %in% nodes$id), ]

Since presumably there is no reason to have edges that connect to nonexistent nodes, could this filtering be done inside the visNetwork function?

**Comment by bthieurmel** [comment]
Done
