### ISSUE TITLE
Use FontAwesome 5

### ISSUE THREAD

**Issue by bhogan-mitre** [datastorm-open/visNetwork#373]
vis.js now supports FontAwesome 5, provided that [icon weight is set to bold](https://github.com/visjs/vis-network/blob/master/examples/network/nodeStyles/icons.html#L117-L140).

<img width="750" alt="Screen Shot 2020-05-09 at 12 38 49 AM" src="https://user-images.githubusercontent.com/32336739/81464216-8a9a3680-918d-11ea-84d2-28af3efe0825.png">

Screenshot via [vis.js icons example](https://visjs.github.io/vis-network/examples/network/nodeStyles/icons.html)

Could we make FA5 the built-in option here as well?  I believe this would resolve issues with use in Shiny Dashboard, related to #292.

**Comment by bhogan-mitre** [comment]
I have a work-in-progress attempt at this here: https://github.com/bhogan-mitre/visNetwork

I would still like to clean up a couple things such as automatically setting the required `icon.weight` and `icon.face`, and making sure all the examples work.  It's not quite ready for a PR, but I'm sharing now in case anyone is interested in trying it out.

**Comment by bthieurmel** [comment]
Hi,

Good news for FA5 support. I think about let the fontAwesome 4 & 5 supports / possibility in ``visNetwork`` (not to include only new FA5).

**Comment by bthieurmel** [comment]
Done on github. So you can use both version (4..7.0 as default or 5.13.0).

And weight is set to "bold" automatically. See ``?addFontAwesome``

**Comment by bhogan-mitre** [comment]
Thanks for taking a look!  

I'm curious what is the use case for maintaining both FA 4.7 and 5.13?

Their upgrade guide seems to advise against that.  https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
![Screen Shot 2020-05-14 at 9 27 49 AM](https://user-images.githubusercontent.com/32336739/81940094-33e59000-95c5-11ea-8b60-d4eb53ace9e6.png)

I like how you've set `icon.weight` to bold automatically.  It seems like we could automatically update `icon.face` from `FontAwesome` to `"Font Awesome 5 Free"` as well, and have this change be transparent and backwards compatible for users here.

Some icons have changed names in FA5... but since the interface here is based on unicode value rather than name, I think we'd be protected against that.

**Comment by bthieurmel** [comment]
I've just want to have a full compatibility with current visNetwork code. 

The goal is not to use both FA4 and FA5 in the same project, but keep current code working on FA4, and let the possibility of new users to use FA5.

**Comment by bhogan-mitre** [comment]
Yes, that is what I'm picturing as well, that this is all transparent and backwards compatible so that current code continues to work.

I would argue that existing examples such as the following all continue to work, but that these icons get provided from FA5 instead of FA4.
```
nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
edges <- data.frame(from = c(1,2), to = c(2,3))

visNetwork(nodes, edges, width = "100%") %>%
  visGroups(groupname = "A", shape = "icon", 
            icon = list(code = "f0c0", size = 75)) %>%
  visGroups(groupname = "B", shape = "icon", 
            icon = list(code = "f007", color = "red")) %>%
  addFontAwesome()
```
The same code uses the same icon codes to produce the same output, but behind the scenes it is using a newer version of the dependency.

Would that work from your perspective?  It would be nice to be using the same clean UI (without needing to provide icon face and version) and still get access to the new FA5 icons.

**Comment by pbaret** [comment]
Hi,
I am interested in this too as I want to use icon f722 (the tractor) in a project.

I tried a lot of stuff and got strange behavior before I found out the problem was font-awesome version embedded with visNetwork package.

Is there a way of using Font Awesome 5.4.0 (or superior) with visNetwork at the moment? 

The closest I got (digging in various forums) before I found this issue:

use `tags$style("@import url(https://use.fontawesome.com/releases/v5.7.2/css/all.css);"),` in the ui to import the icons I need
add `face = "'Font Awesome 5 Free'"` when creating the icon

Behavior: no icon displayed, unless i select the node.  LoL !! 
I share it in case it is of any help 😄 

```
library(shiny)
library(shinyjs)
library(visNetwork)

ui <- fluidPage(
    tags$style("@import url(https://use.fontawesome.com/releases/v5.7.2/css/all.css);"),

    visNetworkOutput("graph1", width = "100%", height = "750px")

)

server <- function(input, output, session) {

    output$graph1 <- renderVisNetwork({
        nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
        edges <- data.frame(from = c(1,2), to = c(2,3))
        
        visNetwork(nodes, edges, width = "100%") %>%
            visGroups(groupname = "A", shape = "icon", 
                      icon = list(code = "f0c0", size = 75)) %>%
            visGroups(groupname = "B", shape = "icon", 
                      icon = list(face = "'Font Awesome 5 Free'", code = "f722", color = "red")) %>%
            addFontAwesome()
    })
}

shinyApp(ui, server)
```

**Comment by YallaToure** [comment]
> Hi,
> I am interested in this too as I want to use icon f722 (the tractor) in a project.
> 
> I tried a lot of stuff and got strange behavior before I found out the problem was font-awesome version embedded with visNetwork package.
> 
> Is there a way of using Font Awesome 5.4.0 (or superior) with visNetwork at the moment?
> 
> The closest I got (digging in various forums) before I found this issue:
> 
> use `tags$style("@import url(https://use.fontawesome.com/releases/v5.7.2/css/all.css);"),` in the ui to import the icons I need
> add `face = "'Font Awesome 5 Free'"` when creating the icon
> 
> Behavior: no icon displayed, unless i select the node. LoL !!
> I share it in case it is of any help 😄
> 
> ```
> library(shiny)
> library(shinyjs)
> library(visNetwork)
> 
> ui <- fluidPage(
>     tags$style("@import url(https://use.fontawesome.com/releases/v5.7.2/css/all.css);"),
> 
>     visNetworkOutput("graph1", width = "100%", height = "750px")
> 
> )
> 
> server <- function(input, output, session) {
> 
>     output$graph1 <- renderVisNetwork({
>         nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
>         edges <- data.frame(from = c(1,2), to = c(2,3))
>         
>         visNetwork(nodes, edges, width = "100%") %>%
>             visGroups(groupname = "A", shape = "icon", 
>                       icon = list(code = "f0c0", size = 75)) %>%
>             visGroups(groupname = "B", shape = "icon", 
>                       icon = list(face = "'Font Awesome 5 Free'", code = "f722", color = "red")) %>%
>             addFontAwesome()
>     })
> }
> 
> shinyApp(ui, server)
> ```

I have exactly the same issue, is there a way to fix this right now?

**Comment by bthieurmel** [comment]
It's not a good idea to mix fontAwesome 4 and fontAwesome 5, so you just have to use only fontAwesome 5 in your case : 

````
library(shiny)
library(shinyjs)
library(visNetwork)

ui <- fluidPage(
  # tags$style("@import url(https://use.fontawesome.com/releases/v5.7.2/css/all.css);"),
  
  visNetworkOutput("graph1", width = "100%", height = "750px")
  
)

server <- function(input, output, session) {
  
  output$graph1 <- renderVisNetwork({
    nodes <- data.frame(id = 1:3, group = c("B", "A", "B"))
    edges <- data.frame(from = c(1,2), to = c(2,3))
    
    visNetwork(nodes, edges, width = "100%") %>%
      visGroups(groupname = "A", shape = "icon", 
                icon = list(face = "'Font Awesome 5 Free'", code = "f0c0", size = 75)) %>%
      visGroups(groupname = "B", shape = "icon", 
                icon = list(face = "'Font Awesome 5 Free'", code = "f722", color = "red")) %>%
      addFontAwesome(version = "5.13.0")
  })
}

shinyApp(ui, server)
````
