### ISSUE TITLE
'bar' won't plot when using 'arrow' 'type' options

### ISSUE THREAD

**Issue by bio-bean** [datastorm-open/visNetwork#375]
Perhaps I'm misunderstanding the docs but I'm trying to plot a network like this, with some different style arrow heads, like in this example:

```
nodes <- data.frame(id = c(1:10))
edges <- data.frame(from = sample(1:10, 8), 
to = sample(1:10, 8),
arrows = c("to", "middle;to", "", ""), 
type = c("bar", "arrow", "", ""))

visNetwork(nodes, edges)
```
And arrows are plotted instead of bars, am I completely misunderstanding how I'm meant to go about plotting the different arrow heads? Sorry if this is a silly question!

**Comment by bthieurmel** [comment]
Hi,

``arrows`` ican be a string like "to" or a more complex object : 

![image](https://user-images.githubusercontent.com/8750326/82642028-89e1b580-9c0d-11ea-8109-17e591f7c61c.png)

If you want to define custom arrows on edges passing javascript object in R data.frame, you have to use a "dot" notation like this : 

````
nodes <- data.frame(id = c(1:10))
edges <- data.frame(from = sample(1:10, 8), 
                    to = sample(1:10, 8),
                    arrows.to.enabled = c(T, T, F, F),
                    arrows.middle.enabled = c(F, T, F, F),
                    arrows.from.enabled = c(F),
                    arrows.to.type = c("bar", "arrow", "", ""),
                    arrows.middle.type = c("bar", "arrow", "", "")
                    )



visNetwork(nodes, edges)
````

But, if you only want to set the global edge configuration, you can simply use ``visEdges`` : 

````
nodes <- data.frame(id = c(1:10))
edges <- data.frame(from = sample(1:10, 8), 
                    to = sample(1:10, 8),
                    arrows = c("to", "middle;to", "", ""))



visNetwork(nodes, edges) %>%
  visEdges(arrows = list(
    to = list(type = "arrow"), 
    middle = list(type = "bar")
  ))
````

**Comment by bio-bean** [comment]
Hi,

Thanks for your response - I tried running the code that you put but I'm afraid it plotted arrows again instead of the bars. Is this perhaps an issue with java and R communicating?

Here's an image of the network that was plotted:
![Rplot_for_github](https://user-images.githubusercontent.com/56388933/82652218-25c2ef80-9c15-11ea-8ace-d0185b21060b.png)

**Comment by bthieurmel** [comment]
You need dev version for this I think : ``devtools::install_github("datastorm-open/visNetwork")`` (for bar option)

**Comment by bio-bean** [comment]
Hi,

Thanks so much for getting back to me, I ran into some installation errors but everything is now working perfectly, thank you so much for your help!
