### ISSUE TITLE
[Bug] Nested selfReference parameters

### ISSUE THREAD

**Issue by julianstanley** [datastorm-open/visNetwork#379]
Recently, [I've needed nodes to have two self-referencing edges](https://github.com/julianstanley/gfpop-gui/issues/31).

Ideally, they would look like this:

![image](https://user-images.githubusercontent.com/22749289/84074501-ae28ea80-a9a0-11ea-830a-6d444594f116.png)

In vis.js, I do this by setting the edge.selfReference.angle parameter, e.g.:

```javascript
{ from":1,"to":1,"arrows":"to","label":"Edge 1", selfReference: {angle: 2*Math.PI} }
```

[See full jsbin example here](https://jsbin.com/bepufonuna/1/edit?html,js,output).

As stated [here](https://datastorm-open.github.io/visNetwork/edges.html) the dot notation should work for this, right? But it doesn't seem to work in my hands, on visNetwork 2.1.0.

Example:

```r
visNetwork(nodes = data.frame(label = "Node 1", id = 1), 
           edges = data.frame(id = c("Edge1", "Edge2"),
                              label = c("Edge 1", "Edge 2"),
                              to = c(1, 1), 
                              from = c(1,1), 
                              selfReference.angle = c(2*pi, pi)))
```

Should output the same as above, but instead outputs:

![image](https://user-images.githubusercontent.com/22749289/84077851-ec74d880-a9a5-11ea-9a72-624ecdf2fbc5.png)

I noticed while experimenting that the selfReference.angle parameter doesn't work with some vis-network versions, but it does work with 7.5.2.

**Comment by bthieurmel** [comment]
Hi,

Fix on github (removing some controls on aloowed split columns...) : 

````
# using DF and dot notation
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1, 1, 2), 
                    to = c(1,1, 3), 
                    selfReference.angle = c(2*pi, pi, NA))
visNetwork(nodes, edges)
````

And using a list, it's ok to with this structure :

````
# using a list
nodes <- list(list(id = 1), list(id = 2), list(id = 3))
edges <- list(list(from = 1, to = 1, selfReference = list(angle = pi)), 
              list(from = 1, to = 1, selfReference = list(angle = 2 *pi)), 
              list(from = 2, to = 3))

visNetwork(nodes, edges)
````

**Comment by julianstanley** [comment]
This now works brilliantly:

```r
visNetwork(nodes = data.frame(label = "Node 1", id = 1), 
           edges = data.frame(id = c("Edge1", "Edge2"),
                              label = c("Edge 1", "Edge 2"),
                              to = c(1, 1), 
                              from = c(1,1), 
                              selfReference.angle = c(2*pi, pi),
                              selfReference.size = c(30, 30)))
```
![image](https://user-images.githubusercontent.com/22749289/84144728-c17e9900-aa26-11ea-8900-888d87995c06.png)

Thank you!!!
