### ISSUE TITLE
Can graph internals be exposed to the DOM?

### ISSUE THREAD

**Issue by julianstanley** [datastorm-open/visNetwork#382]
Right now, the visNetwork graph is all within a `<canvas>` tag. Is it feasible to expose elements within the graph to the DOM?

I'm asking about this feature to make it possible to test visNetwork plots with tools like Selenium (or even `shinytest`, which I don't think is able to interact with visNetwork at all at this time).

![image](https://user-images.githubusercontent.com/22749289/87089669-c476d000-c204-11ea-9779-e1d6c304ce5d.png)

**Comment by bthieurmel** [comment]
``vis.js`` use HTML canvas for rendering, and I think it's not possible to use/set other configuration

**Comment by julianstanley** [comment]
Yep, that makes sense. I suppose I can expose my graph's data for testing by setting it to the window on render:

```r
  output$my_graph <- renderVisNetwork({
    visNetwork(
      nodes = data.frame(id = "A", label = "A")
    ) %>%
      onRender("(el, x) => {window.myData = x}")
  })
```

and, besides that, I'll just work [on the tricks associated with automating canvas testing](https://qxf2.com/blog/selenium-html5-canvas-verify-what-was-drawn/).

Thanks!
