### ISSUE TITLE
Push Latest VisNetwork to CRAN?

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#398]
The version of VisNetwork that is available from CRAN is fairly old--I think it was last updated 17 months ago. Important changes have happened since then. In particular, from last April, 2020, a new version of VisNetwork was created that incorporated the latest javascript from vis-js-network, but this version is not yet available on CRAN.

I would like to request that the latest version of VisNetwork be pushed to CRAN.

Thank you.

**Comment by bthieurmel** [comment]
On it's way #408
