### ISSUE TITLE
New Versions of VisNetwork pushed to CRAN?

### ISSUE THREAD

**Issue by DarylMcCullough** [datastorm-open/visNetwork#408]
This is a sort of broad issue having to do with VisNetwork updates. Is VisNetwork continuing to be updated, and are new updates being made available to the CRAN repository? I know that maintaining free open source software is a lot of thankless work (thanks for all the work, by the way, to Benoit and everyone who has contributed). But I am wondering about the future of this project because I have been using it extensively in recent years.

What is involved in pushing a new version to CRAN? I don't think that I would be of much help in programming issues, but I would volunteer to help out with the necessary testing of new versions.

**Comment by dmenne** [comment]
It would really help if the main author could comment on the future of VisNetwork. Has this project been abandoned? If yes, we should probably fork it and post it under some other name to CRAN.

**Comment by bthieurmel** [comment]
No, this project is not "abandoned", I'm working on severals others projects, so just missing time to check and push a new version on CRAN

**Comment by bthieurmel** [comment]
I've just init a ``v9.1.0`` branch with the latest version. Have some bug on ``configure`` options, so have to wait for fix on vis-network js for a CRAN update

https://github.com/visjs/vis-network/issues/1489

But you can try this latest version if you want / have time.

**Comment by dmenne** [comment]
Thanks, this help a lot, my people prefer a "CRAN-only" version!

**Comment by bthieurmel** [comment]
Ok. Fix the configure pb directly in R, and merge into master. Coming soon on CRAN...

**Comment by bthieurmel** [comment]
On CRAN

**Comment by dmenne** [comment]
Congratulations. I know what a effort it is to follow the paths of CRAN
