### ISSUE TITLE
Can't make visNetwork from empty Igraph

### ISSUE THREAD

**Issue by James-G-Hill** [datastorm-open/visNetwork#409]
The following:

```
visNetwork::visIgraph(
  igraph = igraph::make_empty_graph()
)
```

gives this error:

```
Error in `$<-.data.frame`(`*tmp*`, "id", value = 1:0) : 
  replacement has 2 rows, data has 0
```

So unfortunately, I can't create an empty visNetwork when my Shiny application starts with Igraph layouts; this is how I do it with basic visNetwork:

```
visNetwork::visNetwork(
  nodes = data.frame(id = c()),
  edges = data.frame(from = c(), to = c())
)
```
I have tried other methods of converting that empty basic visNetwork into Igraph format with `visNetwork::visIgraphLayout` but that doesn't work either.

**Comment by bthieurmel** [comment]
Thanks. Fix on dev branch v9.1.0.
