### ISSUE TITLE
Setting initial selection

### ISSUE THREAD

**Issue by dmenne** [datastorm-open/visNetwork#412]
Is there a method to set the initial selection without displaying a dropdown box?

My workaround:
```
  visOptions(
        nodesIdSelection = list(
          enabled = TRUE,
          selected = 3, # or use variable here
          style = 'visibility:hidden' # This hides the dropdown
        )

```

To explain why I asked: visSetSelection only works with visNetworkProxy, but when you have another observer that sets the initial selection, it does not work immediately, but only when used with some delay via invalidateLater. Looks like the network is not yet ready, so an event "networkReady" would have helped.

**Comment by bthieurmel** [comment]
Hi, 

You can use an input$_initialized like this in shiny  (#200) :

````
observeEvent(input$network_initialized,{
   # do stuff e.g. send update via proxy to add background circles...
  visNetworkProxy("network") %>% customVisMethod(...)
})
````
Or some JS stabilization Events #352

**Comment by dmenne** [comment]
Fine!

**Comment by dmenne** [comment]
Thanks for your response, and sorry to reopen this, I had worked on other stuff. I was looking for a method to set the initial selection by program, as if the node had been clicked. The only workaround I found used `nodesIdSelection` , but isn't there an easier way to do something like `visNetworkProxy("network") %>% selectNode(3)`?

**Comment by dmenne** [comment]
Looks like this is a racing condition. When after some delay or on explicit button press I do 
```
 visNetworkProxy(network) %>%  
      visSelectNodes(6)
```
everything works as expected. I will try to create a simplified example.
