### ISSUE TITLE
problem to create an interactive org chart with visNetwork: boxes with long text are overlapping 

### ISSUE THREAD

**Issue by fm555** [datastorm-open/visNetwork#414]
I need to create an interactive org chart with visNetwork, including long text in boxes. But the problem is that the boxes with long text overlap.
Try the following example:

library(visNetwork)
library(tidyverse)
nodes <- data.frame(id = 1:9)
edges <- data.frame(from = c(1,2,2,2,3,3,3,3,3),
to = c(2,3,4,5,6,7,7,8,9))

nodes_df<-data.frame(id=nodes,
label=c("Department Aaaaaaaaaaaaaaaaaaa \naaaaaaaaaaaaaaaaa aaaaaaaaaaaaa very long name \n\nPerson Name Aaaaaaaaaaa Aaaaaaaaaaaaaaaaaaaaaa", "Department 2aaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaaa Aaaaaaaaaaaaaaa","Department 2b Aaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa ", "Department 2c Aaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaa", "Department 3a Aaaaaaaaaaaaa aaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa", "Department 3b Aaaaaaaaaaaaa aaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa","Department 3c Aaaaaaaaaaaaa aaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa","Department 3d Aaaaaaaaaaaaa aaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa","Department 3e Aaaaaaaaaaaaa aaaaaaaaaaaaaaaa \n\nPerson Name Aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa"),
value=20,
level=c(1,2,2,2,3,3,3,3,3),
shape="box")

visNetwork(nodes_df, edges, width="100%") %>% visEdges(smooth = FALSE) %>% visOptions(highlightNearest = TRUE) %>% visHierarchicalLayout(nodeSpacing = 200) %>% visPhysics(stabilization = TRUE)

Do you have any suggestion to solve this problem? I would like to create the interactive org chart with long text using visNetwork. 

Thank you in advance.

**Comment by TitouanRobert** [comment]
Hi, 

You can try : 

`visNetwork(nodes_df, edges, width="100%") %>% visEdges(smooth = FALSE) %>% visOptions(highlightNearest = TRUE) %>% visHierarchicalLayout() %>% visPhysics(stabilization = TRUE, hierarchicalRepulsion = list(nodeDistance = 500))`

Hope it will help you,
Best

**Comment by fm555** [comment]
Excellent! Thank you so much!
