### ISSUE TITLE
ncol in visLegend crashing session

### ISSUE THREAD

**Issue by NaturalSelecta1** [datastorm-open/visNetwork#415]
Hello,

Thankyou so much for the hard work putting this package together and maintaining it.

I just want to highlight an issue that arose through my own stupidity:

I accidentally passed a non-numeric argument to the `ncol=` argument in visLegend(). I passed a data frame with a single entry instead of a raw number. Rather than throwing an error, this seems to have completely crashed my R session and failed to timeout after overnight. I had to do a full terminate of R to remedy.

I appreciate this is only an issue if the user does something wrong, but wanted to flag it.

**Comment by bthieurmel** [comment]
Thanks. Add a control on dev branch.
