### ISSUE TITLE
[Enhancement] Multiline textfield for addNode / editNode popUp

### ISSUE THREAD

**Issue by hnbeck** [datastorm-open/visNetwork#42]
The pop-up window for editing or adding nodes in a graph should provide a multiline input window for entering the "label" text. The reason is to provide the possibility to  input bigger  (markdown) text if required. 
In addition, configuring this popup window by visOption would be nice (text in the window, size ...)

**Comment by bthieurmel** [comment]
Hi,
I keep in memory this point for future improvements, with more configuration for the manipulation process

**Comment by ThoDuyNguyen** [comment]
I think it would be best if the manipulation process included all possible setting like shape, color, label, size ... of both edges and nodes. 
But it takes time to implement I suppose.

**Comment by hnbeck** [comment]
My dream is an application to let grow a graph interactively. But this means to provide useful ways to input (big) markdown text, html text, pictures or diagrams as well as formulas od even office docs. Independent from this I see simple way to manipulate presentation: filtering, shapes, colors etc. 
Having said this, I assume that (general purpose) multi line text field and the manipulators you mentioned are the most achievable goal at the moment :).

**Comment by ThoDuyNguyen** [comment]
@hnbeck : I try many free/open source graph visualization and it seems to me your wish like a presentation editor more than just a graph visualization tool. 
Until now, R presentation or slidify have not well supported html widget (last checked was last week). Once it done, your need could be achievable, by editing RMarkdown syntax I suppose.

**Comment by hnbeck** [comment]
Hi, 

no, not presentation. you#re right, presentation is an aspect. But the main thing for me is the data editor. I’m seeking a long time for a tool to setup a graph interactively. Fetching data from Facebook or Twitter or perform an CSV import are common ways to build a graph, but I need interactive growing and modification. My graphs are in the range from 10-1000 nodes.

Regards

Hans

**Comment by hnbeck** [comment]
@bthieurmel Do you have some basic idea what you want for this point ? Then I could consider to fork and implement an suggestion. But to limit the gap between my idea and yours some basic ideas or design goals would be cool :)

**Comment by bthieurmel** [comment]
No time yet to work on this (and no many time to work to ``visNetwork`` actually...!), so every code is welcome on this.

**Comment by hnbeck** [comment]
Ok, Then I do a new fork and try out ;)

**Comment by hnbeck** [comment]
II think I'll wait with the fork until 2.2 is released.
