### ISSUE TITLE
set up initial zooming level

### ISSUE THREAD

**Issue by Tixierae** [datastorm-open/visNetwork#46]
Would it be possible to initially render the network from a high zoom level (where edge and node labels are not visible)? For large networks for which stabilization takes time and is not very smooth, this would allow to converge faster (it is much smoother when labels are not visible) while still enabling the user to see the overall structure of the network. Also large networks tend to spread out a lot, so the user has to zoom out at some point to continue seeing the entire network. Starting at a higher zoom level would also take care of this. I looked at the documentation but I can't find such a parameter...

**Comment by bthieurmel** [comment]
Hi,
Perhaps you can use and play with the ``moveTo`` function, associated with ``startStabilizing`` event : 

````
visNetwork(nodes, edges) %>%
  visEvents(startStabilizing = "function() {
    this.moveTo({scale:0.1})}") %>%
  visPhysics(stabilization = FALSE)
````

**Comment by Tixierae** [comment]
thank you for this suggestion, I will try it!

**Comment by Tixierae** [comment]
it works very nicely! Thank you very much!

**Comment by Tixierae** [comment]
it works very nicely, many thanks!

**Comment by bthieurmel** [comment]
Yes, of course... It's just because the event is run each time a stabilization is done... For this special case, I've just add ``visEventsOnce`` function, similar to ``visEvents``, but with event listener only once. 
You can try : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visEventsOnce(startStabilizing = "function() {
            this.moveTo({scale:0.1})}") %>%
  visPhysics(stabilization = FALSE)
````

**Comment by Tixierae** [comment]
I would be lost without your precious help. Thank you very much!

**Comment by bthieurmel** [comment]
Just to inform you I've just change the name / the process to do this (more simply for me). Remove ``visEventsOnce`` and add a new optionnal argument to ``visEvents`` : 
- `` type = "on"`` (default), and can be set to ``once`` or ``off``

And now ``visEvents`` can also be use with ``shiny/visNetworkProxy``.

Your example is now : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>%
  visEvents(type = "once", startStabilizing = "function() {
            this.moveTo({scale:0.1})}") %>%
  visPhysics(stabilization = FALSE)
````

**Comment by Tixierae** [comment]
Sounds good! Thanks for letting me know

**Comment by amithit** [comment]
I have a graph component in React app,

```
<Graph
   graph={this.state.graph}
   options={graph_options}
   events={this.events}
/>
```
I hope to make it automatically zoom in/out when the graph changes, just like in vis.js document use network.fit()

But how I can call this fit method?

**Comment by jdonnell01** [comment]
I tried to implement this and it seems that the startStabilizing event is never called. Is there a reason as to why this event wouldn't be called on draw?
