### ISSUE TITLE
How to assign nodes to a new group without redrawing the whole network?

### ISSUE THREAD

**Issue by tleja** [datastorm-open/visNetwork#50]
Hi, it's a great package! I have a large network, which I am partitioning into multiple groups. Is there a way to assign the nodes to a new group without redrawing the network? or, is there a way to re-colour the nodes based on the new group? See the minimal example below:

```
nodes <- data.frame(id = 1:5, group=c(1,1,1,2,2))
edges <- data.frame(from = c(1,2,2,3,3,4), to = c(1,3,4,5,1,3))

network <- visNetwork(nodes, edges)

new_group = c(1,2,2,3,3)
network <- visNodes(network, group=new_group) # or use color=new_group ?

network # the resulting graph doesn't reflect the 'new_group' arrangement
```

I would like to embed this solution into my shiny app, perhaps using `visNetworkProxy`. 
I thought of creating a `matrix` binding all group vectors together, where each column = a group vector. Then using a `sliderInput` in shiny to select a column index for each group vector:
```
visNetworkProxy("network") %>% visNodes(group = matrix[,input$matrix_index])
```
Hopefully this would re-colour the nodes and the legend based on the new group arrangement (without redrawing the whole network).

Any suggestions would be much appreciated!

**Comment by kmezhoud** [comment]
Hi,
I think you need to re-use ```visNetwork``` function
```
nodes <- data.frame(id = 1:5, label=1:5, group=c("A","A","A","B","B"))
edges <- data.frame(from = c(1,2,2,3,3,4), to = c(1,3,4,5,1,3))

visNetwork(nodes, edges)%>%
  visOptions(selectedBy = "group")

nodes$ngrp <- c("A", "B","B","C","C")
visNetwork(nodes, edges, width = "100%") %>%
  visOptions(selectedBy = "ngrp")
```

**Comment by tleja** [comment]
Unfortunately `visNetwork` redraws the whole graph. I have a large network which takes time to stabilise. I hope to find a solution that allows me to **regroup** or **re-colour** individual nodes after the graph has stabilised. 

For instance, something in line with the vis.js example of dynamically changing colour of node 1 after stabilisation: [http://visjs.org/examples/network/data/datasets.html] (http://visjs.org/examples/network/data/datasets.html)

Excerpt from javscript source code:
```
function changeNode1() {
     var newColor = '#' + Math.floor((Math.random() * 255 * 255 * 255)).toString(16);
     nodes.update([{id:1, color:{background:newColor}}]);
}
```

Any suggestions on how to adapt the above to the `visNetwork`, with an option to dynamically re-group the nodes, or re-colour based on the group arrangement?

**Comment by bthieurmel** [comment]
Hi,

I think it can be possible with ``visDataSet`` as you think. I'll have look when have time to try to add a new ``updateNodes`` function using ``shiny`` and ``visNetworkProxy``

**Comment by bthieurmel** [comment]
Initialize ``visUpdateNodes`` and ``visUpdateEdges`` function on github, for a use with ``shiny``.
You can have a look, and do what you want I hope.

``shiny::runApp(system.file("shiny", package = "visNetwork"))``

I think it's really a great new feature.

Thanks

**Comment by kmezhoud** [comment]
Hi,
Thanks for the add. Here a simple example that I use `visUpdateNodes'. but I did not find a way to select which nodes will be in the new group with `selectizeInput` after checking `add Gr2`the list of groups is not updated. I think we also `visUpgdateGroup`

server.R
```
shinyServer(
  function(input, output) {

    output$network <- renderVisNetwork({
      #  nodes <- data.frame(id = 1:10, label = paste("Label", 1:10),
      #                     group = sample(c("A", "B"), 10, replace = TRUE))
      #edges <- data.frame(from = c(2,5,10), to = c(1,2,10))

      withProgress(message = 'drawing the network...', value = 0.1, {
        Sys.sleep(0.25)

      nodes <- data.frame(id = 1:10,
                          label = paste("Node", 1:10),
                          value = c(10,5,3,7,2,3,2.6,2,9,2),
                          shape ="circle",
                          group= c("Gr1","Gr3"),
                          color= c("#DF0101", "blue")
      )

      edges <- data.frame(from = c(1,5,3,7,2,9,10,8,3,3,6),
                          to = c(5,3,5,1,5,1,2,3,7,4,9) )



      graphe <- visNetwork::visNetwork(nodes, edges, width = "100%")

      visNetwork::visOptions(graph= graphe, manipulation = TRUE,
                             selectedBy = "group",
                             highlightNearest = TRUE )

      })
    })

    observe({
      graph <- visNetwork::visNetworkProxy("network")
if(input$enableHierarchiId){
      #conditionalPanel("input.enableHierarchiId==true",
                       visHierarchicalLayout(graph, enabled= input$enableHierarchiId,
                                             direction = input$Hierarchi_AttId,
                                             sortMethod= input$MethodHierarchiId
                       )
        #)
}else if(input$changeGroupId){
  nodes <- data.frame(id = 1:12,
                      label = paste("Node", 1:12),
                      value = c(10,5,3,7,2,3,2.6,2,9,2,11,12),
                      shape ="circle",
                      group= c("Gr1","Gr2","Gr3"),
                      color= c("#DF0101","orange" ,"blue"))
      visNetwork::visUpdateNodes(graph, nodes)

}else{
      #conditionalPanel("input.enableHierarchiId==false",
        visNetwork::visPhysics(graph, solver = input$PhysicLayoutId )

#)
}

    })
  })
```
ui.R
```
shinyUI(fluidPage(
  titlePanel("VisNetwork + shiny"),

  sidebarLayout(
    sidebarPanel(
      h4("Edges Attributes:"),

      enableHierarchi <- c("FALSE","TRUE"),
      PhysicLayout <- c('barnesHut', 'repulsion', 'hierarchicalRepulsion', 'forceAtlas2Based'),
      MethodHierarchi <- c("hubsize", "directed"),
      Hierarchi_Att <- c("LR","RL","UD","DU"),

      wellPanel(

        checkboxInput("enableHierarchiId",label="Hierarchi", value = FALSE),


        selectizeInput("MethodHierarchiId",label="Layout Method", choices = MethodHierarchi,
                       selected= "hubsize", multiple = FALSE),

        selectizeInput("Hierarchi_AttId", label = "Direction", choices = Hierarchi_Att, multiple = FALSE),

        selectizeInput("PhysicLayoutId",label="Physics Options", choices = PhysicLayout,
                       selected= 'hierarchicalRepulsion', multiple = FALSE)
      ),

      checkboxInput("changeGroupId",label="add Gr2", value = FALSE),

      h6("or (not working)"),
      selectizeInput("changeGroupIdbis",label="Select node for Gr2", choices = nodes <- (id = 1:12), selected= NULL, multiple = TRUE),

      checkboxInput("RunId",label="Plot", value = FALSE)
    ),

    mainPanel(
      conditionalPanel(condition ="input.RunId==true",
                     visNetworkOutput("network")
                    )
     # if(input$RunId){
     #  visNetworkOutput("network")
     # }else{}

  )
)
))
```

**Comment by bthieurmel** [comment]
Yes. Some adjustments needed...!

**Comment by bthieurmel** [comment]
I've just add some code and fix some bug. But I think to add a better system/control for this in futur.

**Comment by kmezhoud** [comment]
@bthieurmel 
Maybe it is possible to add group through `visOptions(manipulation = TRUE)`.
Actually we can manipulate `Id` and `label` of nodes. If is possible to add  `group`?
Same thing for Edges.
Karim

**Comment by bthieurmel** [comment]
Linking to update nodes and options, I've just added the possibility to use ``visOptions`` with ``visNetworkProxy``, so you can now enable/disable/change options dynamically.
There is some new example in ``shiny::runApp(system.file("shiny", package = "visNetwork"))``.

You have now several way for changing groups and selection (the most efficient is to pass, if known, the values to visOptions).

New features on ``manipulation`` are not on top of my todo list.
