### ISSUE TITLE
identical styles between default layout engine (force based) and igraph

### ISSUE THREAD

**Issue by FrissAnalytics** [datastorm-open/visNetwork#56]
Hi!

How can I make layouts based on igraph (e.g. via visIgraphLayout) to be identical in terms of node and edge styling to those based on the default rendering engine (in visNetwork), which is a force layout? For instance, now I use two settings to create a similar look between the two, but it is quite cumbersome and it doesn't work well. 

To be clear, I would like to use the styling of visNetwork, with e.g. nodes styles set in the node dataframe, but use positions based on an igraph layout. 

Is this possible in an easy way?

kind regards, Herman

**Comment by bthieurmel** [comment]
It's not clear for me... Normally, if you use ``visNetwork`` with style / options, and then adding the ``visIgraphLayout``, it must be ok.

````
nodes <- data.frame(id = 1:3, shape = c("circle", "square", "triangle"),
                    color = c("red", "blue", "green"))
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges, width = "100%") %>%
  visEdges(dashes = T) %>%
  visIgraphLayout()
````

``visIgraphLayout`` normally just add the coordinates

**Comment by FrissAnalytics** [comment]
Hi,

I think you're right about the styles. The thing that remains is that the scaling of the network I guess, meaning, the font size and node sizes are often much smaller> normally you have to zoom in quite a lot. Is there anything that can be done about this? 

regards, Herman

**Comment by bthieurmel** [comment]
Yes, it's true. It's a little bit complicated to fix that because we have to disabled stabilization and physics to keep coordinates and layout using igraph...

**Comment by FrissAnalytics** [comment]
for those interested, currently (visNetwork <= 0.2.2) if you want your igraph layout to be similar in size to the standard force layout you have to multiply i.e. scale, node/icon/edge widths etc. by a factor around 6. Thus switching between igraph based layouts and force layouts requires you to keep track of a scaling variable, which is used each time to scale the nodes/edges/icons etc. 

It would be nice if this was done automatically by visNetwork, but a simple scaling seems to work as well...

**Comment by bthieurmel** [comment]
Hi Herman,

Size problem between ``igraph`` layout and ``vis.js`` layout is really more complicated than just a linear transformation. It's depends of the initial zoom set by ``vis.js`` rendering the network. (and so the range of the coordinates).
And this parameter is function of number of nodes & windows size....
I've try to implement a first fix, and I've just push a first proposition. 
Can you test and see with your use case ?

Thanks

**Comment by FrissAnalytics** [comment]
Hi,

thanks for the heads up! I'll take a look soon, this week, unfortunately, I'm pretty packed with work. The scaling strategy I explained so far for my current use case works reasonably well. Anyways, I'll try the new version of visNetwork and let you know!

**Comment by lordbitin** [comment]
Hi,

I think that my next question is related to this topic:

I am having troubles when rendering graphs with IgraphLayout. I am using this code

```{r}
                                 visIgraphLayout(
                                     layout = "layout_nicely",
                                     physics = F,
                                     smooth = T,
                                     type = "full",
                                     randomSeed = 1234
                                 )
```

When I render a large graph, it looks great:
![image](https://cloud.githubusercontent.com/assets/7083752/19647077/bfe55932-99fc-11e6-8fe5-fd5ce4a664b2.png)


But for smaller graphs, every node is collapsed to the center, no edges are visible:
![image](https://cloud.githubusercontent.com/assets/7083752/19647112/eb280fcc-99fc-11e6-8544-d76b43a57143.png)

I think this could be repaired by giving more range to the coordinates range given to the layout, but I do not know how to do that. 

Thanks!
