### ISSUE TITLE
dynamically add / remove multiple groups - ionicons

### ISSUE THREAD

**Issue by FrissAnalytics** [datastorm-open/visNetwork#58]
Hi,

Love your package! Small question: is it currently possible to add, remove *multiple* groups in visNetwork via a *single* function call, which includes the options to select FontAwesome icons? From the documentation it seems you have to add groups one at a time via visGroups. That construction uses the pipe operator, which makes it difficult to dynamically create e.g. a loop that adds multiple groups, without hard coding the individual visGroups statement. 

In vis.js there is the option to use setOptions, which you can feed a complete json object, in which you can update many things via a single function call. Perhaps I don't fully realize the current syntax of visNetwork, but I think such a 'general purpose' option would be powerful. In R it would boil down to create list of lists, in which for each module you can pass in whatever is available. 

Also, in the documentation it reads that you can use ionicons. I made may own addIonIcon function, based on your addFontAwesome function. For other users this can be a nice options as well I think. I believe currently only FontAwesome is available in your package, correct?

kind regards, Herman

**Comment by bthieurmel** [comment]
First, you can use the pipe or not, and so define simply a loop, for example : 

````
network <- visNetwork(nodes, edges)

for(gr in groups){
   network <- visGroups(network, groupname = gr, ... )
}
network
````

Then, in R, I make the choice to divide each part of options into single function (``visPhysics``, ``visGroups``, ...). Finally, each of these function define the full options, set in javascript with ``setOptions``. Actually, we don't have a ``visSetOptions`` but we can think about a simple function where you can pass what you want, at your own risk !

For ionicons, it's true. Currently, only ``FontAwesome`` is available with the R package, but I'll try to find time to add also ``ionicons``

**Comment by bthieurmel** [comment]
Just add ``addIonicons`` function.

**Comment by FrissAnalytics** [comment]
great! Somehow I didn't think of using these functions without the pipe. In the meantime I made my own add options function, precisely like you mentioned (pass what you want, at your own risk). Even though in this way there is some duplication in functionality over different functions, it's still a nice function to have in visNetwork I believe. 

The same holds true for initialization I guess. Even though your current set of functions allow you to set most options, it would come in handy to be able to pass an option list on construction of the network as well (this option is also available in vis.js directly).  

When I made my own option function to set the groups I ran into a problem using the icons. Basically I wrote a helper function that via an r dataframe could set all icons in the graph. 

The javascript now works and looks like this: 

```javascript
// add groups
Shiny.addCustomMessageHandler('addGroups', function(data){

  var el = document.getElementById("graph" + data.id);

  if(el){

    // get network
    var network = el.chart;

    var groups = data.groups;

    // fix icons
    for(var g in groups){
      groups[g].icon.code = eval("'" + "\\u" + groups[g].icon.code + "'");
    }

    // apply groups
    network.setOptions({ groups: groups});

    // redraw chart to apply css
    network.redraw();
  }
});

```
As you see I explicitly call eval to create the correct icon code. Somehow when the data is passed from R to json something happens to the icon code. When I use \uf.... it just doesn't work. I tried a lot of things with escaping etc, but in the end I settled for this (not so nice) way of doing it. 

I also call network.redraw to make sure the css is loaded. I believe in your current version sometimes the icons are not loaded i.e. sometimes you have to explicitly trigger a click event in the chart for the network to load in the icons. 

At the vis.js website they say that this happens when the browser fails to load the css the first time, which should be solved be a redraw. Hence, that is why I added it. Perhaps you can use it too. 

vis.js: http://visjs.org/examples/network/nodeStyles/icons.html
If a node is shown as a rectangle, it means the css is not loaded (or not yet loaded). A redraw will fix that.

**Comment by FrissAnalytics** [comment]
for those interested, in the latest version of visNetwork groups and icons can be defined directly in the node dataframe.

**Comment by bthieurmel** [comment]
For information, I've just add the global ``visSetOptions``, to pass directly a full list of network options.

**Comment by FrissAnalytics** [comment]
great!! super useful!
