### ISSUE TITLE
Does this support rules object?

### ISSUE THREAD

**Issue by ncdingari** [datastorm-open/visNetwork#6]
Such as arules

**Comment by timelyportfolio** [comment]
I do not see any built-in support for `arules` or other rules objects, but I think we can get a visualization by piggybacking on some of the helpful functionality from the package [`arulesViz`](http://cran.r-project.org/web/packages/arulesViz).  Using the example in the `arulesViz` [vignette](http://cran.r-project.org/web/packages/arulesViz/vignettes/arulesViz.pdf), you could do something like this.

```r
# visNetwork view of arules

library(arules)
library(arulesViz)
library(visNetwork)
library(igraph)

# using example from arulesViz vignette
#   http://cran.r-project.org/web/packages/arulesViz/vignettes/arulesViz.pdf

data("Groceries")
rules <- apriori(Groceries, parameter=list(support=0.001, confidence=0.5))

subrules2 <- head(sort(rules, by="lift"), 10)

ig <- plot( subrules2, method="graph", control=list(type="items") )

# saveAsGraph seems to render bad DOT for this case
tf <- tempfile( )
saveAsGraph( subrules2, file = tf, format = "dot" )
# clean up temp file if desired
#unlink(tf)

# let's bypass saveAsGraph and just use our igraph
ig_df <- get.data.frame( ig, what = "both" )
visNetwork(
  nodes = data.frame(
    id = ig_df$vertices$name
    ,value = ig_df$vertices$support # could change to lift or confidence
    ,ig_df$vertices
  )
  , edges = ig_df$edges
) %>% visEdges( style = "arrow" )

```

**Comment by AaronRanAn** [comment]
Hi dnchari, thanks for this awesome example. I tried the example code in r Studio, but I got an error msg: 

Error in visEdges(., style = "arrow") : unused argument (style = "arrow")

Any idea how to fix this? Thanks!

**Comment by timelyportfolio** [comment]
Not sure what might be the cause.  Do you have the newest `magrittr` installed?  Could you copy/paste `sessionInfo()`?

**Comment by dnchari** [comment]
Hi @AaronRanAn, that was @timelyportfolio 's example. It is working fine for me. As @timelyportfolio suggested, copy/paste your `sessionInfo()`

**Comment by AaronRanAn** [comment]
Thank you @dnchari and @timelyportfolio for the help! Great example @timelyportfolio. I think I had the latest magrittr installed. Here is my sessionInfo:

R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_0.7.1     visNetwork_0.0.4 arulesViz_1.0-0  magrittr_1.5     arules_1.1-6     Matrix_1.2-1    

loaded via a namespace (and not attached):
 [1] cluster_2.0.1        MASS_7.3-40          scatterplot3d_0.3-35 colorspace_1.2-6     lattice_0.20-31     
 [6] foreach_1.4.2        caTools_1.17.1       tools_3.2.0          vcd_1.4-0            seriation_1.1-0     
[11] KernSmooth_2.23-14   registry_0.2         htmltools_0.2.6      iterators_1.0.7      gtools_3.5.0        
[16] digest_0.6.8         lmtest_0.9-34        htmlwidgets_0.4      gclus_1.3.1          bitops_1.0-6        
[21] codetools_0.2-11     TSP_1.1-1            gdata_2.16.1         gplots_2.17.0        zoo_1.7-12

**Comment by timelyportfolio** [comment]
Ok, this changed in https://github.com/DataKnowledge/visNetwork/commit/e4250a9d80dfa893d4403b999bfab2b6b394927c#diff-a6ec04185bad175f59e321fca59b0eca , so the `style` is no longer an argument to `visEdges`.  You can remove the `style="arrow"` and it should work.

It seems other things have changed also, since the result is very different.  Perhaps @bthieurmel could point us to the changes to get the result similar to before.  Thanks.

**Comment by timelyportfolio** [comment]
Ok, it looks like this gets the original result with the newer syntax.

# visNetwork view of arules

library(arules)
library(arulesViz)
library(visNetwork)
library(igraph)

# using example from arulesViz vignette
#   http://cran.r-project.org/web/packages/arulesViz/vignettes/arulesViz.pdf

data("Groceries")
rules <- apriori(Groceries, parameter=list(support=0.001, confidence=0.5))

subrules2 <- head(sort(rules, by="lift"), 10)

ig <- plot( subrules2, method="graph", control=list(type="items") )

# saveAsGraph seems to render bad DOT for this case
tf <- tempfile( )
saveAsGraph( subrules2, file = tf, format = "dot" )
# clean up temp file if desired
#unlink(tf)

# let's bypass saveAsGraph and just use our igraph
ig_df <- get.data.frame( ig, what = "both" )
visNetwork(
  nodes = data.frame(
    id = ig_df$vertices$name
    ,value = ifelse(is.na(ig_df$vertices$support),0,ig_df$vertices$support) # could change to lift or confidence
    ,title = ifelse(ig_df$vertices$label == "",ig_df$vertices$name, ig_df$vertices$label)
    ,ig_df$vertices
  )
  , edges = ig_df$edges
) %>%
  visEdges( arrows = "to" ) %>%
  visOptions( highlightNearest = T )

**Comment by AaronRanAn** [comment]
Thank you so much @timelyportfolio! The new syntax works. I did notice there are other changes too. 

This is such an awesome package and look forward to more awesome tutorials and examples. Thanks again!
