### ISSUE TITLE
[bug] visIgraphLayout does not work because of "id" column in egde data frame

### ISSUE THREAD

**Issue by hnbeck** [datastorm-open/visNetwork#61]
The problem is that in my application of visNetwork I use a edge data frame with the column "id". I know from certain experiments that igraph can not handle this. If I delete this "id" column all works fine. The problem is that for manipulating graphs I need the "id" column, vis.js allocate ids to edges for identifying them for edit or delete..

**Comment by bthieurmel** [comment]
Hi, 
Can you give me more explanation / some example ? This seems ok for me : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), id = 1:2))
 
visNetwork(nodes, edges) %>%
  visIgraphLayout() %>%
  visEvents(select = "function(properties) {
     alert('selected edges: ' + properties.edges);}",)
````

**Comment by hnbeck** [comment]
ok, then I have to investigate more deeply. For my current stuff, deleting the "id" column in the edges framework is the only way.

**Comment by bthieurmel** [comment]
Can you use a specific layout ? If you can send me an example with this error, i'll fix that !

**Comment by hnbeck** [comment]
I've tried your example, and it worked. I don't use a specific layout. So it seems it is a special thing in may application or my data. BTW, the error message was "Some vertex names in edge list are not listed in vertex data frame".

**Comment by bthieurmel** [comment]
If you can send me an example of data which return this error, I'll have a look to a possible solution.
