### ISSUE TITLE
icon hover and highlight color

### ISSUE THREAD

**Issue by FrissAnalytics** [datastorm-open/visNetwork#62]
Hi,

is it currently possible to set a hover and highlight color on a node when using icons based on e.g. fontawesome? 

kind regards, Herman

**Comment by bthieurmel** [comment]
Related to ``vis.js`` documentation, It seems it's not actually possible

**Comment by FrissAnalytics** [comment]
for those interested, a workaround is to define js functions for e.g. `hoverNode` and `blurNode` in `visEvents`. For instance, if you want the tooltip to change on hover:

in shiny server.r add something like this:

```r
output$network1 <- renderVisNetwork({

	visNetwork(nodes = nodes, edges = edges) %>%

	visEvents(
		hoverNode	= "function(node){hoverNodeHelper(node);}",
		blurNode	= "function(node){blurNodeHelper(node');}"
	)
})
```

Then in javascript add something like this:

```javascript
function hoverNodeHelper(node){
  Shiny.onInputChange('hoverInfo', node);
  $('body').css("cursor","pointer");
}

function blurNodeHelper(node){
  Shiny.onInputChange('blurInfo', node);
  $('body').css("cursor","default");
}

```

changing the node color is a bit more involved. Essentially you can do it on the client side, using the node update functions to dynamically modify the icon color. For instance, in the hoverNodeHelper function you set it to red and on blurNodeHelper you set it back to its previous value. 

Another way is to send a signal to shiny via 'Shiny.onInputChange', and use 'visUpdateNodes' in combination with 'visNetworkProxy'. The latter is a bit more involved, but requires less js coding.

Note that in the latter case you can get the information on hover and blur via 'input$hoverInfo' and  'input$blurInfo', respectively. 

Finally, note that highlighting this way is only needed for icons, not for normal shapes. In the latter case you can define the hover color directly.
