### ISSUE TITLE
Hierarchy define level

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#63]
Hi!

I've noticed a difference in levels has changed between the latest and maybe two version back . I think this may be related to visjs in this issue:
https://github.com/almende/vis/issues/528

We had a layout of a graph where two nodes were on the same level from the top going down. Now two nodes are at different levels in the hierarchy. It's not technically inaccurate, I'm just curious if there is any additional custom layout that could specify the layout to be at a defined level?

**Comment by bthieurmel** [comment]
Not really clear for me... Can you send me an example ?

**Comment by bthieurmel** [comment]
Hi, 

Do you have already heard / test the ``level`` argument in nodes data.frame ? (You have to know the levels before...!) Simple example : 

````
nodes <- data.frame(id = 1:4, level = 1:4, label = 1:4)
edges <- data.frame(from = c(1:4), to = c(2,4,1,3))

visNetwork(nodes, edges) %>% visHierarchicalLayout()
````

In ``R``, I don't change anything, and let ``vis.js`` do the job.  Moreover, ``github 0.2.2`` use newest ``vis.js`` library than ``CRAN 0.2.1``, and you have new argument in ``visHierarchicalLayout``. You can have some tests...

````
nodes <- data.frame(id = 1:4, level = 1:4, label = 1:4)
edges <- data.frame(from = c(1:4), to = c(2,4,1,3))

visNetwork(nodes, edges) %>% 
  visHierarchicalLayout(blockShifting = FALSE,
                        edgeMinimization = FALSE, 
                        parentCentralization = FALSE)
````

**Comment by dockstreet** [comment]
Thanks! 

We weren't specifying levels before, and I guess something changed in the default layout in vis.js 

After specifying levels was able to set the placement in the hierarchy as desired.
