### ISSUE TITLE
How to specify local path for images?

### ISSUE THREAD

**Issue by mexindian** [datastorm-open/visNetwork#65]
In your example of how to use images on the nodes, you specify online images... but what if I want to use local images? a testcase could be: 

```
nodes <- data.frame(id = 1:4, 
                    shape = c("image", "circularImage"),
                    image = "hello.png",
                    label = "I'm an image")
```

I know that it might not be finding the images locally because the hierarchy is launching from localhost... but how to make localhost find the images stored in the same folder?

**Comment by bthieurmel** [comment]
Using a shiny Apps, you can put images in www directory, and then just pass the path after www/.

Without a shiny apps, it depends of your system and browser, and can needed some configuration.

http://www.websina.com/bugzero/kb/browser-file-url.html
http://stackoverflow.com/questions/12711584/how-to-specify-a-local-file-within-html-using-the-file-scheme

**Comment by mexindian** [comment]
Thanks for the response. I am not using Shiny, on a Win10 machine. I couldn't get it to work using the links you specified. (tried the `file:///` and `file://192.168.1.57/path` approach). For now, I'll just go without images.

One other thing, have you thought of adding a "Main Title" option? I could definitely use that.

**Comment by bthieurmel** [comment]
You can now adding an image (last github version), with a new ``main`` argument in ``visNetwork`` : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges, main = "visNetwork minimal example")
# css
visNetwork(nodes, edges, main = list(text = "visNetwork minimal example",
  style = "font-family:Comic Sans MS;color:#ff0000;font-size:15px;text-align:center;"))
````

**Comment by mexindian** [comment]
Nice. In your above comment did you mean "title" instead of "image"? Sorry I just wanted to clarify that you didn't ALSO solve the image problem? Thanks for the title!

**Comment by bthieurmel** [comment]
Yes, you're right. I add the title, but not fix the image problem (I think I can't do anything actually for this...)

**Comment by mexindian** [comment]
thanks anyway!

On 8 April 2016 at 16:22, B. Thieurmel <notifications@github.com> wrote:

> Yes, you're right. I add the title, but not fix the image problem (I think
> I can't do anything actually for this...)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/datastorm-open/visNetwork/issues/65#issuecomment-207500308>
>



-- 
--

~ शांति ~

+233 (0)20 758 4266
Skype: amit.kdr

**Comment by zhiboz** [comment]
One workaround is, from where your local image resides, launch an http server
`http-server`
or 
`python -m SimpleHTTPServer`

and then use in your R script

`image = 'http://127.0.0.1:<port>/hello.png'`

**Comment by mexindian** [comment]
For what it's worth, I circled back to this and decided to create a repository for images, suitable for usage in customized nodes. Check out this code... what do you think is a good way to announce it? (if at all... :))

```
path_to_images <- "https://raw.githubusercontent.com/mexindian/FilledBoxes/master/"

nodes <- data.frame(id = 1:4, 
                    shape = c("image", "circularImage"),
                    image = paste0(path_to_images,round(runif(4)*100,0),".",round(runif(4)*100,0), ".png"),
                    label = "I'm an image")

edges <- data.frame(from = c(2,4,3,3), to = c(1,2,4,2))

## Remember, it won't show up in RStudio... look on real web browser.
visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shapeProperties = list(useBorderWithImage = TRUE)) %>%
  visLayout(randomSeed = 2)
```
