### ISSUE TITLE
Using Proxy to select nodes

### ISSUE THREAD

**Issue by Norovis** [datastorm-open/visNetwork#66]
Hey,

I would like to know, whether it is possible to change the selected node by using the really nice proxy system of visNetwork. The reason for that is, that I want a search field, which set the focus on the given node and also select / highlight the node.
As I have not found such a function, I tried to use the nodesIdSelection, but even though the id is valid, visFocus works, and I get the nodesIdSelection field, the initial selection is not set. 

Is there some workaround or have I overseen a function which selects one or more nodes?

Thank you in advance
 ```
 observe({
    selected_items <- input$ui_search_box
    if (!is.null(selected_items)){
    isolate({
        id <- nodes[(as.character(nodes$label) %in% selected_items), 1]
      visNetworkProxy("mynetwork") %>%
        visOptions(highlightNearest = list(enabled = TRUE, degree = 1), nodesIdSelection = list(enabled = TRUE, selected = id[length(id)]))  %>%
        visFocus(id[length(id)], locked=FALSE)
    })
    }
  })
```

**Comment by bthieurmel** [comment]
Hi,

There are three methods to do selection ``selectNodes``, ``selectEdges``, & ``setSelection`` in ``vis.js``, but not actually implement in R with proxy... Wait a few days, and I'll add them.

Moreover, your code seems good and the initial selection not set with ``nodesIdSelection`` is another bug I'll try to fix.

**Comment by Norovis** [comment]
Wow, that was a fast answer.

And that's great. Thank you very very much

**Comment by bthieurmel** [comment]
I've just code and add ``visSelectNodes``, ``visSelectEdges`` and ``visSetSelection``, and add an example in the demo shiny application.

Please just note that this methods don't fire events, so we can't have for example ``highlightNearest`` with this selection...(click event). I'll look if it's possible.

**Comment by bthieurmel** [comment]
And I begin to fix the initial selection not set with ``nodesIdSelection``. But there is still some bad interaction if you change also ``highlightNearest``.... In my To do list !

**Comment by bthieurmel** [comment]
Normally, all bad interactions seems to be fix today with ``visNetworkProxy`` & ``visOptions``.

**Comment by ThoDuyNguyen** [comment]
The new feature is great. 
Thank you so much

**Comment by Norovis** [comment]
yes, that's great. Thank you very very much.

**Comment by bthieurmel** [comment]
For information, I've just add ``clickEvent`` option in ``visSelectNodes`` to enabled or not ``click`` event ( and ``highlightNearest``) using this function.
