### ISSUE TITLE
Replace/hide node image when not highlighted

### ISSUE THREAD

**Issue by elyasb** [datastorm-open/visNetwork#67]
Hi,

I am trying to use the "highlightNearest" and "selectedBy" visOptions for a network in which all nodes are circular images, but these options aren't visually effective because all the images remain visible. Is there a way to replace the node image (with an alternative greyed-out image) or completely hide the image when a node or group is highlighted? I couldn't find a solution in the documentation, and I was thinking one option might be to change the node options through visEvents, but I have had no luck so far.

**Comment by bthieurmel** [comment]
Hi,

You're right. It's a point I want to fix before submitting the dev version on CRAN : enabled ``highlightNearest`` & ``selectedBy`` with icons / image.
Hope can be done in the next weeks.

**Comment by bthieurmel** [comment]
It's (normally....) ok to use ``highlightNearest`` & ``selectedBy`` with ``icons`` and / or ``image``. Moreover, I add a new option to ``highlightNearest`` to enabled also when hover a node.
