### ISSUE TITLE
Using layout.norm with visIgraphLayout

### ISSUE THREAD

**Issue by jcarlen** [datastorm-open/visNetwork#68]
Hi, I wanted to use all the nice features of visNetwork but with the option to specify my own coordinates for graph points. 

The best way I saw to do this was through the visIgraph function and specifying layout = "layout.norm". However, this didn't work because no layout object could be specified with the existing function. (Unlike other [igraph layouts](http://www.inside-r.org/packages/cran/igraph/docs/layout) that take a graph argument, layout.norm has a layout argument.)

So, I made a couple quick modifications and now it works, eg.. 
\> visIgraph(g, layout = "layout.norm", layout.norm = Z) 
\> visIgraph(g) %>%
\+ visIgraphLayout(g, layout = "layout.norm", layout.norm = Z)

Modifications:

In visIgraph.R:
I added a "layout.norm = NULL" argument and passed this when visIgraphLayout is called: "visIgraphLayout(layout = layout, type = type, physics = physics, smooth = smooth, layout.norm = layout.norm)"

In visIgraphLayout:
I added a "layout.norm = NULL" argument and instead of just "coord <- ctrl$objs[[1]](ig)":

  if(layout == "layout.norm") {
      if (is.null(layout.norm)) {
          stop("layout.norm requires a layout.norm argument, a matrix with two or three columns")
      }
      coord <- ctrl$objs[[1]](layout.norm)
  } else {
      coord <- ctrl$objs[[1]](ig)
  }

I'll be playing around with it and if I run into any problems/need to change anything else I'll post a follow-up.

I hope this is the right forum for this -- I've never contributed to an active package. If there's a better avenue just let me know. Also, if there was a better way for me to specify coordinates with the existing code please let me know that too. Thanks!

**Comment by bthieurmel** [comment]
Hi,
In the ``0.2.2``, actually on github (coming soon on CRAN), I've already fix this (passing argument to layout) adding ``...``, so you can pass all additionnal layout argument.

You can test installing the dev version : 
``devtools::install_github("datastorm-open/visNetwork")``

**Comment by bthieurmel** [comment]
Ok, I've don't read all you comment before answering...! I'll fix the case for the use of ``layout.norm`` also, keeping only the ``...`` and some control inside the code. Perhaps you can send me a simple example (I don't know ``igraph`` very well....) ?

**Comment by bthieurmel** [comment]
I try to fix this special case on github. Adding an argument ``layoutMatrix`` (your ``layout.norm``). If you can test, it will be great !

Otherwise, if you know the coordinates, you can pass it directly in the ``nodes`` data.frame using ``x`` and ``y`` columns.

**Comment by jcarlen** [comment]
Hi, sorry for taking a while to get reply. A few things:

1) The layoutMatrix argument is working as expected. I checked it on my data, but here's some example code too:

#positions
x = c(1,2,3,4)
y = c(1,2,3,4)
nodes1 <- data.frame(id = c(1,2,3,4))
edges1 <- data.frame(from = c(1,2,3,4), to = c(2,3,4,1))
#convert to igraph
library(igraph)
igraph1 = graph.data.frame(edges1, directed=TRUE, vertices=nodes1)
#layoutmatrix
z = cbind(x,y)
visIgraph(igraph1, idToLabel = FALSE, type = "full") %>%
  visIgraphLayout(layout = "layout.norm", layoutMatrix = z, type = "full")

2) I tried passing coordinates via the x,y arguments of the `nodes` data.frame and it works, but default scaling puts the nodes right on top of each other. Would be nice if it scaled to window size.  

x = c(1,2,3,4) #default scaling not great, multiply by 100 to see separation
y = c(1,2,3,4) 
nodes1 <- data.frame(id = c(1,2,3,4), x = x, y = y)
edges1 <- data.frame(from = c(1,2,3,4), to = c(2,3,4,1))
visNetwork(nodes1, edges1) %>%
  visPhysics(enabled = FALSE)

3) Last thing: there's a typo in the documentation of visNodes / fixed 
""y" : Boolean. When false, the node will not move in the X direction."

Thanks!
