### ISSUE TITLE
Is hover styling supported?

### ISSUE THREAD

**Issue by obkhan** [datastorm-open/visNetwork#69]
Hi,

Admittedly I have not tried this yet, I was curious if hover styling is supported? 

https://github.com/almende/vis/issues/147

Thanks!

**Comment by bthieurmel** [comment]
Hi, 

Of course ! You can do everything possible in ``vis.js`` library. So you can change ``background`` and/or ``border`` color of a node, and color of a edges. An also use events to do more complicated things. Just don't forget to set ``visInteraction(hover = TRUE)``. A simple example (in the documentation also...) : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% 
  visNodes(color = list(hover = list(background = "green", border = "orange"))) %>%
  visInteraction(hover = TRUE)
````

**Comment by dockstreet** [comment]
Thanks so much! Much appreciated!

**Comment by wlandau** [comment]
What about hover text alignment? I am not sure how to impose a left text alignment using `visNodes()`.
