### ISSUE TITLE
legend can't display correctly

### ISSUE THREAD

**Issue by slzhao** [datastorm-open/visNetwork#70]
Hi,

Thanks for developing such a great package. It is very useful in my project.
I think there is a issue in the legend display. Would you please fix it? Thanks!

Here is the code from the vignette:
>require(visNetwork)
>nb <- 10
>nodes <- data.frame(id = 1:nb, label = paste("Label", 1:nb),
 group = sample(LETTERS[1:3], nb, replace = TRUE), value = 1:nb,
 title = paste0("\<p\>", 1:nb,"\<br\>Tooltip !\</p\>"), stringsAsFactors = FALSE)
>edges <- data.frame(from = trunc(runif(nb)*(nb-1))+1,
 to = trunc(runif(nb) * (nb-1))+1,
 value = rnorm(nb, 10), label = paste("Edge", 1:nb),
 title = paste0("\<p\>", 1:nb,"\<br\>Edge Tooltip !\</p\>"))
>visNetwork(nodes, edges, width = "100%") %>% visLegend()

Here is the result. I think there should be "A", "B", "C" in legend but I can only see two of them.
![image](https://cloud.githubusercontent.com/assets/1684109/15972409/f121fe7e-2f03-11e6-9908-1807676c92c7.png)

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] visNetwork_1.0.1

loaded via a namespace (and not attached):
[1] htmlwidgets_0.6 magrittr_1.5    htmltools_0.3.5 yaml_2.1.13    
[5] Rcpp_0.12.5     jsonlite_0.9.21 digest_0.6.9

**Comment by bthieurmel** [comment]
Hi,

It's really strange. Can't reproduce this on windows / linux.... (and never this before...!) Are you using RStudio and the viewer, or a web browser ? The legend don't appears well after resize (sometimes the initial render can be bad....)?

And what's happens if you do this : 

````
lnodes <- unique(nodes[, c("group"), drop = FALSE])
lnodes$label = lnodes$group

visLegend(useGroups = FALSE, addNodes = lnodes)
````

**Comment by slzhao** [comment]
I got the same result after running the above code.
By the way, I viewed it in Chrome/IE/RStudio viewer, it is the same, and it is the initial render.
Thanks!

**Comment by bthieurmel** [comment]
And so nothing better when you resize the viewer ? (Try to understand...!)

**Comment by slzhao** [comment]
It seems that I found the reason. It is not correct when setting height=400 or not setting height, and it is correct when setting height=800. 

>visNetwork(nodes, edges, width = "100%") %>% visLegend()
>visNetwork(nodes, edges, width = "100%",height=400) %>% visLegend()
>visNetwork(nodes, edges, width = "100%",height=800) %>% visLegend()

**Comment by bthieurmel** [comment]
Really strange ! Can set ``height = NULL``, or for ``20 to 2000`` and everything ok for me...

I've just do some modifications for test, if you can try with the github version ?

``devtools::install_github("datastorm-open/visNetwork")``

**Comment by slzhao** [comment]
Thanks for the update.
I tested the latest version from github and found that:
visNetwork(nodes, edges, width = "100%") %>% visLegend()   >>>> Correct
height=NULL, 300, 500, 800  >>>> Correct
visNetwork(nodes, edges, width = "100%",height=400) %>% visLegend() >>>> Not Correct

It's much better now and I can see the result correctly. Thanks!

**Comment by bthieurmel** [comment]
I was finally able to identify the problem. It's appear when a coordinate is set to zero. Normally, it's fix on the last update. So you can try, and (normally) see your legend even with a ``height=400``.

**Comment by slzhao** [comment]
Thanks! It works now even with a height=400.

**Comment by bthieurmel** [comment]
Good, and thanks for help me to correct this point.
