### ISSUE TITLE
CUSTOMIZATION OF DASHES - MISSING EXAMPLES/INFO

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#72]
I have a boolean vector for the dashes I need, in my visualization, but when the graph is generated, the dashes are not easy to distinguish. I understand there is an option regarding the dashes' gap length, but I see no documentation or examples on it. Is it possible to have some? How do you actually combine the TRUE/FALSE vector with custom gap and dash lengths?

**Comment by bthieurmel** [comment]
Hi,
It seems that there is a little bug in ``vis.js`` if we want to customize dashed globally, like this : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), dashes = c(T, F))

visNetwork(nodes, edges) %>% visEdges(dashes = c(10, 10, 2, 2)) # no effect
````

So I add some treatment to enable passing this individually : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3), dashes = c("[10,10,2,2]", "false"))

visNetwork(nodes, edges) 
````

It's not perfect, but have to play with data.frame R, and javascript syntax...

Available on ``1.0.2`` actually on github. Add also some examples in visEdges.
