### ISSUE TITLE
[enchancement] more options for the edges' endings

### ISSUE THREAD

**Issue by kagestrife** [datastorm-open/visNetwork#73]
Other than just an arrow, could we get a circle, a rectangular, etc? This may be trivial, but it's a really important part, due to the use of different symbols in various graphical standards (i.e. in biology)

**Comment by bthieurmel** [comment]
It's a good idea, but you have to ask this enhancement on ``vis.js`` github (https://github.com/almende/vis).

For the R package, you can do all the library propose, and more with some options (highlight, selected, ...), but I don't change the ``vis.js`` source.

**Comment by mojoaxel** [comment]
see https://github.com/almende/vis/issues/1993

**Comment by kagestrife** [comment]
@mojoaxel  @bthieurmel  Hello, do we have an update on this issue? I noticed the thread on the vis.js got closed and this one is reopened. Any info on the matter would be  valuable, thank you.

**Comment by mojoaxel** [comment]
There is now an implementation for this: https://github.com/almende/vis/pull/2066

**Comment by bthieurmel** [comment]
And now available in ``dev visNetwork 1.0.3``, newly linked to vis.js ``4.17.0``.

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% visEdges(arrows =list(to = list(enabled = TRUE, 
 scaleFactor = 2, type = 'circle')))
````

**Comment by gadepallivs** [comment]
thank you for implementing Circle is implemented thank you. The other most commonly used edge endings in biological pathways is  "|" for Inhibition.  I see some github issues on this, but could not understand if this has been implemented already.  `[Link to publication](https://www.researchgate.net/figure/Ingenuity-Path-Designer-representation-of-Toll-like-receptor-signaling-pathway-with_fig8_255737052)`

**Comment by fakesecret** [comment]
As asked or commented by gadepallivs and bthieurmel, the edge endpoint bar has been implmented in vis.js at https://github.com/almende/vis/pull/3444. it would be great that we have this option for edge arrow (endpoint) type. For instant, only arrow and circle are supported as stated by the doc of visEdge ->arrows -> to -> type: "Character. Default to 'arrow'. The type of endpoint. Also possible is 'circle'"

**Comment by gadepallivs** [comment]
@bthieurmel , from the example you gave...how to have a legend with the "circle". Also, any updates on implementation of "bar"
