### ISSUE TITLE
visNodes "color" param doesn't work when visOptions is used

### ISSUE THREAD

**Issue by crew102** [datastorm-open/visNetwork#74]
Greetings -

The `color` argument in `visNodes` **does not** seem to work when `visOptions` is also called alongside `visNodes` :   

```
library(shiny)
library(visNetwork)

server_visOpts <- function(input, output) {
    output$network <- renderVisNetwork({
        # minimal example
        nodes <- data.frame(id = 1:3, some_col = rep("A", 3))
        edges <- data.frame(from = c(1,2), to = c(1,3))

        visNetwork(nodes, edges) %>% 
            visOptions(selectedBy = "some_col",
                       highlightNearest = list(enabled = TRUE, degree = 2,
                                                           hover = TRUE)) %>% 
            visNodes(color = list(background = "orange", border = "darkblue",
                                  highlight = "yellow"),
                     shadow = list(enabled = FALSE)) 
    })
}

ui <- fluidPage(
    visNetworkOutput("network")
)

shinyApp(ui = ui, server = server_noVisOpts)
```

...but it **does** work when `visOptions` is not called alongside `visNodes`: 

```
server_noVisOpts <- function(input, output) {
    output$network <- renderVisNetwork({
        # minimal example
        nodes <- data.frame(id = 1:3, some_col = rep("A", 3))
        edges <- data.frame(from = c(1,2), to = c(1,3))

        visNetwork(nodes, edges) %>% 
            visNodes(color = list(background = "orange", border = "darkblue",
                                  highlight = "yellow"),
                     shadow = list(enabled = FALSE)) 
    })
}
shinyApp(ui = ui, server = server_noVisOpts)
```

Thanks,
Chris

**Comment by bthieurmel** [comment]
Hi,
It's a little bit more complicated, and seems there is still some bug to fix with the different possible levels of colors (group, nodes as global or nodes individually + full color or background + border +...) and highlightNearest options....! (really not simple to implement all case....)

Waiting for that, and in general, you can prefer : 

- using group
- set  also a "hover" color when highlightNearest hover is set to TRUE and you don't set a "global" color...

````
nodes <- data.frame(id = 1:3, some_col = rep("A", 3), group = "B")
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% 
  visOptions(selectedBy = "some_col", highlightNearest = list(enabled = TRUE, degree = 2,
                                                              hover = T)) %>% 
  visGroups(groupname = "B", color = list(background = "orange", border = "darkblue",
                        highlight = "yellow", hover = "yellow"),
           shadow = list(enabled = FALSE))
````

**Comment by crew102** [comment]
OK, thanks for the help. I look forward to applying visNetwork in the future.

**Comment by MarkRazmandi** [comment]
I would like to follow up on this if possible. I am greatly appreciative for your hard work on this package, however, it appears I cannot choose the colors of my nodes when I pass any arguments through visOptions. It defaults to the stock blue from the example. The reason this is relevant to me is my use of visNetwork in director presentations...

Thank you regardless, the package is wonderful!

**Comment by bthieurmel** [comment]
Can you send me an example of your case ? Using group, we need to use correct order definition. individual nodes definition  > group definition > global node definition....

Moreover, if you use ``highlightNearest`` or ``selectedBy``, a colum group equal to 1 is create if not in nodes data.

````
# minimal example
nodes <- data.frame(id = 1:3, color.background = c("red", "blue", "yellow"), 
                    color.highlight = "purple")
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% visOptions(highlightNearest = T) %>%
  visGroups(groupname = "1", color = list(border = "black"))
````

**Comment by bthieurmel** [comment]
I've just pushed some update / fix on this topic on github. Now, ``highlightNearest`` and/or ``selectedBy`` don't create a group column.

**Comment by markrazmandi** [comment]
Thank you kindly bthieurmel, I am presenting at a conference in two weeks using your package exclusively. I will ensure to extend credit!

**Comment by bthieurmel** [comment]
Thanks. So have a good conference !
