### ISSUE TITLE
highlightNearest, algorithm='hierarchical' messes up edge colors

### ISSUE THREAD

**Issue by jockbanan** [datastorm-open/visNetwork#75]
Hi! 
When `highlightNearest` is used in conjunction with `algorithm="hierarchical"`, the color of the edge can be compromised. In this example:

```
require(visNetwork, quietly = TRUE)
nodes <- data.frame(id=1:2, color.border=rep("#DD0000", 2), color.background=rep("#CCCCCC", 2))
edges <- data.frame(from = c(1), to=c(2), color=list(color=rep("#BBBBBB", 1), highlight=rep("#00DD00", 1)))
visNetwork(nodes, edges, width = "100%") %>%
    visOptions(highlightNearest = list(enabled = T, algorithm = "hierarchical", degree = list(from = 0, to = 2)))
```
- When the edge is clicked, it is highlighted in gray (fine). 
- When any of the nodes is clicked and then the edge is clicked, it is highlighted in blue (not fine, or can I control this color somehow?). 
- When a node is clicked and then unselected (i.e. I click away from any nodes or edges) the edge gets the color of the node border (red) and stays that way forever. (not fine). (setting `inherit=F` does not help)

Thanks
Adam

**Comment by jockbanan** [comment]
Actually, now I see that the blue color of the highlighted edge is also adopted from the node border.

**Comment by bthieurmel** [comment]
Hi,
Yes, it's true. ``algorithm="hierarchical"`` reset and reload edges, but actually don't look if edge have define color. 
TO DO...!

**Comment by bthieurmel** [comment]
I've just push some fix / new features on github to add edges color and label treatment using highlightNearest and selectedBy
