### ISSUE TITLE
highlightNearest, algorithm='hierarchical' only highlights one edge irrespective of depth

### ISSUE THREAD

**Issue by jockbanan** [datastorm-open/visNetwork#76]
In this example: 

```
require(visNetwork, quietly = TRUE)
nodes <- data.frame(id=1:3)
edges <- data.frame(from = c(1, 2), to=c(2, 3))
visNetwork(nodes, edges, width = "100%") %>%
    visOptions(highlightNearest = list(enabled = T, algorithm = "all", degree = 2))
```

If node 1 is clicked, both nodes 2 and 3 are highlighted (or not grayed out), but only the edge from 1 to 2 is highlighted. Irrespective of `degree` and depth of the graph, only edges from the clicked node are highlighted.

**Comment by bthieurmel** [comment]
Hi,

It's normal. Edges inherit of node, so only edges related to clicked node are also highlighted. Changing ``degree`` you can control the depth of "visible" network (not in gray). It's perhaps better to look at this example, changing ``depth`` : 

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

visNetwork(nodes, edges) %>% visOptions(highlightNearest = list(enabled = TRUE, degree = 1))
````

**Comment by jockbanan** [comment]
Ok, thanks, I get it. I can still achieve uniform edge behavior by 
`visInteraction(selectConnectedEdges = F)`
