### ISSUE TITLE
[enhancement] Allow to set selectable for nodes and edges separately

### ISSUE THREAD

**Issue by jockbanan** [datastorm-open/visNetwork#77]
Hi again!
I can disable the nodes and edges to be selectable by 

`visInteraction(selectable=F)`

but it would be lovely to have the possibility to make e.g. only nodes selectable and edges not.

Thanks!
Adam

**Comment by bthieurmel** [comment]
Hi,

Except for ``visOptions``, ``visLegend``, ``visIgraphLayout`` and some others ``R/shiny only`` addings, all the functionnalities are from the ``vis.js``  library & API. You can try to send an issue on related github https://github.com/almende/vis
