### ISSUE TITLE
[Feature Request] - Unfocus `visFocus` 

### ISSUE THREAD

**Issue by martinjhnhadley** [datastorm-open/visNetwork#78]
How might one undo the work of `visFocus`?

Consider a controller that allows users to focus on nodes, as per your example:

```r
observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFocus(id = input$Focus, scale = 4)
  })
```

The user then changes the controller to "focus on none", is there an equivalent of:

```r
observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visDefaultZoom()
  })
```

**Comment by bthieurmel** [comment]
Hi,

You can use ``visFit`` with ``nodes = NULL`` : 

````
observe({
    visNetworkProxy("network_proxy_nodes") %>%
      visFit(nodes = NULL)
})
````

You can find some examples in the package ``shiny::runApp(system.file("shiny", package = "visNetwork"))``

**Comment by martinjhnhadley** [comment]
That works beautifully - thanks! I should've checked those example, visFit is very smart.
