### ISSUE TITLE
Problem with network redraw

### ISSUE THREAD

**Issue by mmorine** [datastorm-open/visNetwork#79]
I'm having an issue with network redrawing after turning physics off.

My goal is to draw the initial network then turn off physics so that dragging a node will not trigger a new drawing and stabilization of the network (i.e., the network will stay stationary after dragging a node). Using the code below, nothing happens when I drag a node; the dragged node only moves to it's new position when I zoom in/out, or click again in the network pane.

```
nodes <- data.frame(id = 1:50, group=sample(1:10, 50, replace=T))
edges <- data.frame(from = sample(1:50, 200, replace=T), to = sample(1:50, 200, replace=T))

visNetwork(nodes, edges)  %>% visEvents(stabilizationIterationsDone="function () {network.setOptions( { physics: false } );}")
```

Note that the problem is the same even if I set {physics: true} in the above code, so it seems to be an issue of visEvents rather than turning physics off.

Thanks.

**Comment by bthieurmel** [comment]
Hi,

Just use  ``this`` rather than ``network`` in javascript event : 

````
require(visNetwork)

nodes <- data.frame(id = 1:50, group=sample(1:10, 50, replace=T))
edges <- data.frame(from = sample(1:50, 200, replace=T), to = sample(1:50, 200, replace=T))

visNetwork(nodes, edges)  %>% visEvents(stabilizationIterationsDone="function () {this.setOptions( { physics: false } );}")
````

**Comment by mmorine** [comment]
Excellent, works perfectly - thanks!
