### ISSUE TITLE
visNetworkProxy return edge/node list & properties to be used to collapse / expand

### ISSUE THREAD

**Issue by dockstreet** [datastorm-open/visNetwork#82]
Hi,

I was wondering if it is possible to return the entire list of nodes & edges and their properties (such as hidden) from visNetworkProxy? 

I can currently use reactive values to cache a dataframe with their properties, so I can inspect the dataframe that holds the edges & nodes and mainipulate it & pass it in to visUpdateNodes/visUpdateEdges. 

I couldn't find an visAddNodes/visAddEdges method? 

I can create a JSON objects which holds many properties and store it with "ID" and retrieve a single object via Shiny.onInputChanged and pass the whole JSON object back which is handy too. This method will only work though for one node/edge selected.

Part of my use case for this is being able to collapse / expand related nodes on a hover over or click, my approach may not be the most efficient. 

Thanks for any/all feedback!

**Comment by bthieurmel** [comment]
HI,

Two things : 

- ``visUpdateNodes`` & ``visUpdateEdges`` can be use to add nodes/edges if you pass new id. You can have a look to the "demo application" ``shiny::runApp(system.file("shiny", package = "visNetwork"))``

- there isn't actually function to get from shiny all nodes/edges data, but we can add it in the next version (not before september)

**Comment by dockstreet** [comment]
Excellent! Thanks for showing me how to add nodes & edges with visUpdateNodes & visUpdateEdges. 

Looking forward to being able to visGetNodes/visGetEdges or some other mechanism/function +1

**Comment by bthieurmel** [comment]
``visGetNodes`` and  ``visGetEdges`` are now available in github dev version. You can try, and find example in the shiny app.
