### ISSUE TITLE
Can the network output save as pdf or svg format

### ISSUE THREAD

**Issue by jiajiayb** [datastorm-open/visNetwork#84]
Hi, I really like the visNetwork package. One issue I encountered is that, sometimes I need the pdf or svg format of the output network instead of the default png picture format. I just wonder if there is any solution for this. Thank you!

**Comment by bthieurmel** [comment]
Hi, actually there is no solution using the package only. Perhaps in a next version....!

**Comment by anz000** [comment]
Great Package. Exporting to pdf option would be great.

**Comment by Tixierae** [comment]
For small networks and without fancy options (icons or images for nodes) you can export an igraph version of the graph to PDF using base R

**Comment by bthieurmel** [comment]
I've just add a pdf export options.

**Comment by skanskan** [comment]
Hello.

Any news about the option to export to svg or vectorial pdf?
Any other workaround?

**Comment by skanskan** [comment]
Could you please provide a simple example with the export vectorial pdf option, please?

**Comment by jcrodriguez1989** [comment]
I have the same question as @skanskan . 
the generated pdf looks just like a screen capture.

**Comment by skanskan** [comment]
As visnetwork is based on vis I also asked this at its github site.  https://github.com/almende/vis/issues/723
And as you can see I received some rude responses telling me that if I want that option I should develop them myself.
That's why, sadly, I'm moving to Diagrammer.

**Comment by anz000** [comment]
I didn't go through the whole conversation, but I didn't think that was a rude response :) . May be that's just me. It's a community effort, and all people chip in. The people who contribute to these programs probably have their own jobs, and they just do it because they like coding or just contribute on something good. 

Getting back to creating vectorized images from visNetwork, I found a workaround by getting the network details and converting to DOT format, then creating vector images from DOT version. This way, the network topology (or position) is fixed, but the graphical representation changes. It did the job for me.

**Comment by skanskan** [comment]
@anz000 Could you provide a simple example, please?

**Comment by jcrodriguez1989** [comment]
@skanskan 
He is translating the graph from visNetwork to a Dot graph. And using the Dot R library, you can export this dot graph to svg or ps.
However, visually it will look different.

A simple idea would be:

```
> nodes <- data.frame(id=c('a','b','c','d'));
> edges <- data.frame(from=c('a', 'a', 'b'), to=c('b', 'c', 'd'));
> edges
  from to
1    a  b
2    a  c
3    b  d

> library('visNetwork');
> visNetwork(nodes, edges);

> dotGraph <- paste0('digraph { ', 
+     paste(
+         apply(edges,1,paste, collapse=' -> '),
+     collapse='; '),
+ ';}');

> library('DOT');
> dot(dotGraph, file="myfile.svg");
```

**Comment by skanskan** [comment]
@jcrodriguez1989 Thanks.
The output looks like a Diagrammer graph.
What would be the advantage of using this DOT method instead of the Diagrammer one?

I hope some day we could save a Visnetwork graph with the positioning of the nodes and other beautiful features.

Saludos

**Comment by qade544** [comment]
Really great package! I am wondering anyone who have resolved this question that exporting pdf or svg? Thanks a lot here~~

Bests,
Shisheng

**Comment by AlexanderBartholomaeus** [comment]
Any update here? The export to vector SVG or PDF would be really need! I really like the package but without proper exporting I need to find something else

**Comment by YanglabWCH** [comment]
Also want to ask: any update here? Hope some more capable coder could resolve this export to vector SVG or PDF!!! Many thanks here.

**Comment by MikaQiao** [comment]
Same question with me: any update here? It is really helpful to export with SVG or PDF.

**Comment by bugriy** [comment]
Need to export to SVG. Any progress here?
