### ISSUE TITLE
Tooltip styling

### ISSUE THREAD

**Issue by vjm261** [datastorm-open/visNetwork#89]
Hi,

I have a HTML styled table for my node title/tooltip. When I use the same code in a Shiny app the tooltip background changed from white to a odd beige color. I can change the HTML table background but not the tooltip color. 

Is there any documentation for the tooltip styling or can you suggest a work-around.

Thanks!

**Comment by bthieurmel** [comment]
Hi.
Don't find documentation on that, but ``vis.js`` use ``vis.css`` file, on which we can find the tooltip css. Perhaps you can try to change/overwrite this ? : 

`````
div.vis-network-tooltip {
  position: absolute;
  visibility: hidden;
  padding: 5px;
  white-space: nowrap;

  font-family: verdana;
  font-size:14px;
  color:#000000;
  background-color: #f5f4ed;

  -moz-border-radius: 3px;
  -webkit-border-radius: 3px;
  border-radius: 3px;
  border: 1px solid #808074;

  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);
  pointer-events: none;
}
````

**Comment by bthieurmel** [comment]
It's now possible wth ``1.0.3 dev version`` using ``visInteraction`` :

````
nodes <- data.frame(id = 1:10, 
 title = '<a target="_blank" href="https://github.com/datastorm-open/visNetwork">github</a>')
edges <- data.frame(from = round(runif(8)*10), to = round(runif(8)*10))

# custom tooltip
visNetwork(nodes, edges) %>%
visInteraction(tooltipStyle = 'position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;
 font-family: cursive;font-size:18px;font-color:purple;background-color: red;')
````

**Comment by lordbitin** [comment]
Great!
