### ISSUE TITLE
visUpdateNodes: inconsistencies when updating group properties

### ISSUE THREAD

**Issue by 7brunner** [datastorm-open/visNetwork#91]
I want to create an app where the colours of nodes change dynamically based on which node is selected (the idea is to show the output of a contagion model, where the highlighted nodes are the ones that would experience contagious defaults from the selected node - so it's not always just all the directly connected nodes that should be highlighted). In principle this should be possible by updating the group properties of the nodes with `visUpdateNodes`, however, it seems to behave strangely:

If I simply udpate the group properties of the nodes, then the app will "remember" the previously colored nodes - i.e. every node that was coloured once will remain coloured, even if it shouldn't be under the currently selected node. I managed to create a workaround with a second observer-function that resets all the group properties. This works if I run the app on my local Windows machine from RStudio, but strangely, it does not work when I run it on my (Linux-based) server. There, the app simply does not colour the nodes at all (even though you sometimes see a quick spark of colours, which indicates that the code was executed, but then the second oberserver function was called again and cleared the properties). The example below demonstrates the problem:

global.R:

    id <- c(1,2,3,4,5)
    group <- rep("",5)
    nodes <- data.frame(id,group)

    from <- c(1,1,1,2,2,2,3)
    to <- c(2,3,4,1,3,5,5)
    edges <- data.frame(from,to)

    def1 <- c("","Default","Default","","")
    def2 <- c("","","Default","Default","")
    def3 <- c("","","","Default","")
    def4 <- c("","","","","Default")
    def5 <- c("","","","","")

    defs <- data.frame(def1,def2,def3,def4,def5)

server.R:

    library(shiny)
    shinyServer(function(input, output) {
      output$netplot <- renderVisNetwork({
        visNetwork(nodes,edges)%>% 
          visGroups(
            groupname = "Default", color = list(
              background = "red"
            )
          ) %>%
          visOptions(
            nodesIdSelection = list(
              enabled = TRUE
            )
          )
      })
      observe({
        if (!is.null(input$netplot_selected)) {
          nodes$group <- rep("A",5)
          visNetworkProxy("netplot") %>% visUpdateNodes(nodes)      
        }
      })
      observe({
        if (!is.null(input$netplot_selected)) {
          if(input$netplot_selected!="") {
            newgroup <- defs[,as.numeric(input$netplot_selected)]      
            nodes$group <- newgroup
          }
        }   
        visNetworkProxy("netplot") %>% visUpdateNodes(nodes)   
      })
    })

ui.R: 

    library(visNetwork)
    shinyUI(fluidPage(mainPanel(visNetworkOutput("netplot"))))

**Comment by bthieurmel** [comment]
Perhaps a bad interaction between your two observers. You can try that : 

````
require(visNetwork)
require(shiny)

id <- c(1,2,3,4,5)
group <- rep("A",5)
nodes <- data.frame(id,group)

from <- c(1,1,1,2,2,2,3)
to <- c(2,3,4,1,3,5,5)
edges <- data.frame(from,to)

def1 <- c("A","Default","Default","A","A")
def2 <- c("A","A","Default","Default","A")
def3 <- c("A","A","A","Default","A")
def4 <- c("A","A","A","A","Default")
def5 <- c("A","A","A","A","A")

defs <- data.frame(def1,def2,def3,def4,def5)

server <- function(input, output) {
  output$netplot <- renderVisNetwork({
    visNetwork(nodes,edges)%>%
      visGroups(
        groupname = "Default", color = list(
          background = "red"
        )
      ) %>%
      visOptions(
        nodesIdSelection = list(
          enabled = TRUE
        )
      )
  })
  # observe({
  #   if (!is.null(input$netplot_selected)) {
  #     nodes$group <- rep("A",5)
  #     visNetworkProxy("netplot") %>% visUpdateNodes(nodes)
  #   }
  # })
  observe({
    if (!is.null(input$netplot_selected)) {
      if(input$netplot_selected!="") {
        newgroup <- defs[,as.numeric(input$netplot_selected)]
        nodes$group <- newgroup
      }
    } 
    visNetworkProxy("netplot") %>% visUpdateNodes(nodes)
  })
}

ui <- fluidPage(mainPanel(visNetworkOutput("netplot")))

shinyApp(ui = ui, server = server)
````

**Comment by 7brunner** [comment]
Yes, that's what I had originally - with this code, the app seems to "remember" the node colouring, i.e. nodes that were coloured once will remain coloured, even if their group property is empty in the newly assigned group property vector.

**Comment by bthieurmel** [comment]
Yes, it seems use ``group = ""`` is a bad idea. Prefer use ``group = "empty"`` or another code. Seems to work for me with the previous code using "A" rather than ""

**Comment by 7brunner** [comment]
Alright, that was an easy fix - great, thanks!
