### ISSUE TITLE
Node Size scale

### ISSUE THREAD

**Issue by mexindian** [datastorm-open/visNetwork#92]
So it seems there's a maximum difference between biggest and smallest node (as set by `value`). Is there anyway to change this maximum difference? I have a dense network (3k nodes), and when even one of these nodes is very huge, the rest of the nodes look like they are all the same size. See a screenshot below:

![image](https://cloud.githubusercontent.com/assets/8094091/18280796/662ddd50-7428-11e6-92ba-38de2b50a23d.png)

Due to the number of nodes, it can be hard to identify the big guys... hence my question... can we alter the scale to allow truly huge nodes be viewed bigger?

**Comment by bthieurmel** [comment]
using ``value``, you can also play with ``scaling`` : 

````
nodes <- data.frame(id = 1:3, value = c(10,20,30))
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges) %>% visNodes(scaling = list(min = 20, max = 50))

````

**Comment by mexindian** [comment]
Exactly correct. Apologies for having missed this in the documentation.
