### ISSUE TITLE
visIgraphLayout() throws error if node id column isn't upfront

### ISSUE THREAD

**Issue by luke-a** [datastorm-open/visNetwork#93]
Consider 

```
library(visNetwork)
set.seed(1)
nnodes <- nnedges <- 25
nodes <- data.frame(label = letters[nnodes], id = 1:nnodes)
edges <- data.frame(from = sample(1:nnodes, nnedges, replace = T), 
                   to = sample(1:nnodes, nnedges, replace = T))

visNetwork(nodes, edges) %>% 
 visIgraphLayout()
# Error in igraph::graph_from_data_frame(graph$x$edges, directed = TRUE,  : 
#   Duplicate vertex names

visNetwork(nodes[,c("id", "label")], edges) %>% 
 visIgraphLayout()
# works
```

So currently, one has to make sure the id column comes in the nodes data frame first, and thus when passing `graph$x$nodes` to the `vertices` argument. Otherwise `igraph::graph_from_data_frame` may throw an error because of non-unique vertice ids. (Note that `visNetwork()` accepts data frames that have the `id` column not as the first column; so this may cause problems.) 

For example, replacing
```
 ig <- igraph::graph_from_data_frame(graph$x$edges, directed = TRUE, 
                                     vertices = graph$x$nodes)
```
by 
```
 ig <- igraph::graph_from_data_frame(graph$x$edges, directed = TRUE, 
                  vertices = graph$x$nodes[,c("id", setdiff(names(graph$x$nodes), "id"))])
```
in `visIgraphLayout` fixes the issue. 

_(I'm rather new to github; is this the right way to report an issue? Or should one file a "pull request"?)_

**Comment by bthieurmel** [comment]
Thanks for your feedback. Fix now in dev version.
