### ISSUE TITLE
Node labels are overriding node IDs in 'nodesIdSelection'

### ISSUE THREAD

**Issue by incivile** [datastorm-open/visNetwork#94]
Hello,

I'm using node labels to show the "node size". I want to also use 'nodesIdSelection' and I would like to use the node IDs (since it's unique and the sizes are not), but I'm not able to figure it out - the labels are overriding the IDs. Here is an example:

```
nodes = data.frame(id = 1:6, level = c(1, 2, 3, 3, 4, 2), label = LETTERS[11:16])
edges = data.frame(from = c(1, 2, 2, 4, 6), to = c(2, 3, 4, 5, 4))
visNetwork(nodes, edges) %>%
    visOptions(nodesIdSelection = list(enabled = TRUE, values = nodes$id))
```

As you can see, in the drop-down menu there are still the labels. Is it a bug or am I missing something?

Thank you for your help.

**Comment by bthieurmel** [comment]
Hi,
It's a choice I made (use Labels rather than id if possible). I've just add a new options ``useLabels = T`` in ``visOptions``.
Available actually on dev/github version.
