### ISSUE TITLE
Undirected network multiple edges

### ISSUE THREAD

**Issue by abhik1368** [datastorm-open/visNetwork#95]
I have an undirected network with multiple types of edges with different colors, it also has edge labels. When I put the network I dont see the different edges . I think somehow those are getting overlapped on top of each other . Is it possible to separate out the edges distinctly?

**Comment by bthieurmel** [comment]
Hi,

Perhaps you can try two things : 

- first be sure you are using ``smooth`` ``dynamic`` edges
- and reduce ``springConstant`` parameter in ``visPhysics``. Can also change the solver...

````
nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                    group = sample(LETTERS[1:3], 15, replace = TRUE))

edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                    to = trunc(runif(15)*(15-1))+1)

edges$color <- "black"
edges$label <- "first"
edges_bis <- edges
edges_bis$color <- "red"
edges_bis$label <- "second"

visNetwork(nodes, rbind(edges, edges_bis,edges)) %>%
  visEdges(smooth = list(enabled = T, type = 'dynamic')) %>%
  visPhysics(solver = "barnesHut", 
             barnesHut = list(springConstant = 0.002))
````

**Comment by abhik1368** [comment]
Thanks,  Certainly it works great !!
