### ISSUE TITLE
enable html in label

### ISSUE THREAD

**Issue by mexindian** [datastorm-open/visNetwork#96]
This one is easy! :)

I want to embed links in the network. Theoretically, I can use either the tooltip or the title.
![image](https://cloud.githubusercontent.com/assets/8094091/18589413/a34ffbb4-7bf8-11e6-9364-0b96b1d8dcc5.png)

**Tooltip**: I can embed html, but when I move my mouse to hover over the tooltip, the tooltip moves and therefore I can't click on the link!
**title**: HTML is not enabled

Maybe the easiest would be to just offer HTML embedding in the title?

**Comment by bthieurmel** [comment]
No easy, and not for me but for ``vis.js``. Can already find issue for this (https://github.com/almende/vis/issues/1936). Actually no solution.

**Comment by mexindian** [comment]
Ajj.. a pity. What about specifying the tooltip "pops up" location? Or implementing a delay? It seems the tootip behavior on vis.js is different than ours? https://github.com/almende/vis/issues/1435 makes it look possible... not sure for visNetwork tho?

**Comment by bthieurmel** [comment]
Yes, think it's possible with some modification. I'll have a look.

**Comment by bthieurmel** [comment]
Done in new 1.0.3 on github, for tootip, adding a delay. You can test.

``
nodes <- data.frame(id = 1:3, title = '<a target="_blank" href="http://www.w3schools.com">Visit W3Schools</a>')
edges <- data.frame(from = c(1,2), to = c(1,3))

visNetwork(nodes, edges)
``

**Comment by mexindian** [comment]
Confirmed! Works in Chrome, IE and Edge! Nice job, and thanks!

**Comment by wodsworth** [comment]
How to have different links for each node?
