### ISSUE TITLE
visOptions selectedBy bug?

### ISSUE THREAD

**Issue by byandell** [datastorm-open/visNetwork#97]
Hi,
I found two apparent bugs with visOptions. 

1. The help page refers to a data.frame column "group", which does not exist. Changing to "level" resolves this.
2. If nodes is a tbl_df rather than a data.frame, there is an error message, and the "Select by level" menu on the viewer is messed up (one character per line of literal R).

thanks,
Brian
---------
**set up data**
> nodes = data.frame(id = 1:6, level = c(1, 2, 3, 3, 4, 2))
> edges = data.frame(from = c(1, 2, 2, 4, 6), to = c(2, 3, 4, 5, 4))

**this does not work** 
> visNetwork(nodes, edges) %>% 
+     visOptions(selectedBy = "group")
Warning message:
In visOptions(., selectedBy = "group") :
  Can't find 'group' in node data.frame

**this works**
> visNetwork(nodes, edges) %>% 
+     visOptions(selectedBy = "level")

**this does not work** 
> visNetwork(tbl_df(nodes), edges) %>% 
+     visOptions(selectedBy = "level")
Warning message:
Unknown column 'group'

**Comment by bthieurmel** [comment]
Hi,

First one is not a bug. This help says :  ``"variable" : Character. Column name of selection variable.`` so you can use any variable in node data.frame. In the example I put in the package, this is "group" column.

For the second point, I've just fix some bad interaction we can have using ``dplyr`` or ``data.table`` with some data.frame operations...

**Comment by voxnonecho** [comment]
@bthieurmel I confirm 819f83820794c99a997fc7981fdcdb15320b90ae fixed the `tbl_df` interaction issue.

**Comment by byandell** [comment]
Great. Thanks!
Brian

**Comment by byandell** [comment]
Hi,
I thought I would just check the example for visOptions again. Below are the warning messages I get. I think the problem is that nodes$group is assigned near the end of the example, so there are 4 examples of use where "group" is undefined.
Brian

> example(visOptions)
Warning messages:
1: In visOptions(., selectedBy = "group") :
  Can't find 'group' in node data.frame
2: In visOptions(., selectedBy = list(variable = "group", selected = "A")) :
  Can't find 'group' in node data.frame
3: In visOptions(., selectedBy = list(variable = "group", selected = "C",  :
  Can't find 'group' in node data.frame
4: In visOptions(., selectedBy = list(variable = "group", style = "width: 200px; height: 26px;\n   background: #f8f8f8;\n   color: darkblue;\n   border:none;\n   outline:none;")) :
  Can't find 'group' in node data.frame

=================
From help page for visOptions:

##########################
# selectedBy
##########################

visNetwork(nodes, edges) %>%
 visOptions(selectedBy = "group")

# add a default value ?
visNetwork(nodes, edges) %>%
 visOptions(selectedBy = list(variable = "group", selected = "A"))

# subset on values ?
visNetwork(nodes, edges) %>%
 visOptions(selectedBy = list(variable = "group",
   selected = "C",
   values = c("A", "C")))

# add some style
visNetwork(nodes, edges) %>%
 visOptions(selectedBy = list(variable = "group", style = 'width: 200px; height: 26px;
   background: #f8f8f8;
   color: darkblue;
   border:none;
   outline:none;'))

# can also be on new column
nodes$sample <- sample(c("sample 1", "sample 2"), nrow(nodes), replace = TRUE)
visNetwork(nodes, edges) %>%
 visOptions(selectedBy = "sample")

# and with multiple groups ?
nodes$group <- sample(c("group 1", "group 2", "group 1, group 2, group 3"),
 nrow(nodes), replace = TRUE)

visNetwork(nodes, edges) %>%
 visOptions(selectedBy = list(variable = "group", multiple = TRUE))



________________________________


From: Brian Yandell <brian.yandell@wisc.edu<mailto:brian.yandell@wisc.edu>>
Date: Thursday, September 22, 2016 at 10:21 AM
To: datastorm-open/visNetwork <reply@reply.github.com<mailto:reply@reply.github.com>>, datastorm-open/visNetwork <visNetwork@noreply.github.com<mailto:visNetwork@noreply.github.com>>
Cc: Brian Yandell <brian.yandell@wisc.edu<mailto:brian.yandell@wisc.edu>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [datastorm-open/visNetwork] visOptions selectedBy bug? (#97)

Great. Thanks!
Brian

**Comment by bthieurmel** [comment]
Thanks. I'll correct that. It's due to  a bad interaction with a recent example .
