### ISSUE TITLE
visNetworkProxy - problem updating edges and old edges not being deleted

### ISSUE THREAD

**Issue by peacemachine** [datastorm-open/visNetwork#99]
Hi,

I am trying to replicate this model: http://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/  ... the idea is to dynamically alter the graph probabilistically.

However, I have several problems connected to visNetworkProxy:

1/ when I attempt to modify the edges and nodes,  it simply added additional edges to the nodes rather than replace them. I could not find any way to delete the old edges, for instance by using visRemoveEdges. How is it possible to do this?

2/ I could not find a way to control the starting x-y position of the "anchor" nodes but make the ball nodes float. How can I do this?

I don't know if there is a bug in visNetwork or in my code. I've spent hours looking at the visNetworkProxy shiny examples and can't figure it out. Very grateful for your help as your package is the only one in R that seems to be able to do what I would like, and it seems awesome.

Apologies for the code not displaying properly - it's my first comment and it mangles it a bit. 

Thank you,

Antony

require(shiny)
require(visNetwork)
#devtools::install_github("datastorm-open/visNetwork")

anchors <- 1:4
num.balls <- 10

nodes <- data.frame(
  id = 1:num.balls,
  size = 15,
  shape = c("circle"),
  shadow = FALSE,
  fixed = FALSE
)

anchor.range <- (1+num.balls):(length(props)+num.balls)
anchornodes <- data.frame(
  id = anchor.range,
  size = 15,
  shape = c("square"),
  shadow = FALSE,
  fixed = TRUE
)

nodes <- rbind.data.frame(nodes, anchornodes)

edges <- data.frame(
  from = nodes$id, 
  to = nodes$id,
  physics = TRUE
)

props <- c(1,1,1,1)
props <- props * (num.balls / sum(props))
cumprops <- round(cumsum(props))
cumprops <- c(0, cumprops)

for (a in 1:num.balls) {
  for (b in 1:(length(cumprops)-1)) {
    if (a <= cumprops[b+1] & a > cumprops[b]) {
      edges$to[a] <- num.balls + b
    }
  }
}

nodes$group <- edges$to
node.colors <- c("blue", "darkred", "purple", "lightgreen")
nodes$color <- node.colors[nodes$group - num.balls]

server <- function(input, output) {
  
  output$network <- renderVisNetwork({
    visNetwork(nodes, edges, width = "100%")
  })
  
  observe({
    
    #Reassign edges of balls to different anchors
    props <- c(input$anchor_1, 1, 1, 1)
    props <- props * (num.balls / sum(props))
    cumprops <- round(cumsum(props))
    cumprops <- c(0, cumprops)
    for (a in 1:num.balls) {
      for (b in 1:(length(cumprops)-1)) {
        if (a <= cumprops[b+1] & a > cumprops[b]) {
          edges$to[a] <- num.balls + b
        }
      }
    }
    
    #Change the group the balls belong to the new anchor and alter color
    nodes$group <- edges$to
    node.colors <- c("blue", "darkred", "purple", "lightgreen")
    nodes$color <- node.colors[nodes$group - num.balls]
    
    #Update the network
    visNetworkProxy("network") %>%
      visUpdateNodes(nodes = nodes)  %>%
      visUpdateEdges(edges = edges)
  })
  
}

ui <- fluidPage(
  fluidRow(
    column(
      width = 2,
      sliderInput("anchor_1",
                  label = h6("Anchor 1"), min = 0, max = 4, value = 1, step = 0.05)
    ),
    column(
      width = 10,
      visNetworkOutput("network", height = "600px")
    )
  )
)

shinyApp(ui = ui, server = server)

**Comment by bthieurmel** [comment]
A first answer : to control edges as nodes (update/remove, ...), just add an id to edges also, and then pass the id with ``visUpdateEdges`` and ``visRemoveEdges``.

**Comment by peacemachine** [comment]
Thank you, that solves the updating. I simply added an id to each of the edges and modified the graph by %>% visUpdateEdges(edges = new.edges)

However, I have two related problems:
(1) I cannot find a way to get the nodes to group tightly together, despite trying all the physics options. When they do, they overlap massively, and the avoidOverlap function seems ineffective at preventing this.
(2) I cannot find a way to get the nodes of a particular group to gather in a particular fixed part of the screen.

It would be great if you could help, as otherwise dreading trying to implement it using D3 directly!
Does your package have the functionality to be able to do this, and if so, how?

Many thanks!

Antony

**Comment by bthieurmel** [comment]
Hi,

You can disabled physics on nodes to fix them. This is done for example using ``visIgraphLayout``, computing coordinate before rendering and then disable physics on nodes.

``
visNetwork(nodes, edges, width = "100%") %>%
      visIgraphLayout()
``

You can also do this after stabilization, for example like this : 

``
visNetwork(nodes, edges, width = "100%") %>%
  visEvents(stabilized = "function() {
    this.setOptions({nodes : {physics : false}})}")
``

Send me an example, I can have a look.
